### ISSUE TITLE
[Possible Upstream] Using Cinnamon with Multiple GPUs

### ISSUE THREAD

**Issue by agrubb86** [linuxmint/cinnamon#10175]
```
 * Cinnamon version (cinnamon --version)
  4.8.6
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 Gentoo
 * Graphics hardware *and* driver used
 AMD Renoir + AMD RX 5500M - both amdgpu
 * 32 or 64 bit
 64bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 
Cinnamon warning: Log level 8: gdk_display_get_screen: assertion 'screen_num == 0' failed
Cinnamon warning: Log level 8: gdk_screen_get_setting: assertion 'GDK_IS_SCREEN (screen)' failed
(cinnamon:3118): Gdk-ERROR **: 12:25:46.267: The program 'cinnamon' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadMatch (invalid parameter attributes)'.
  (Details: serial 637 error_code 8 request_code 7 (core protocol) minor_code 0)
Traceback (most recent call last):
  File "/usr/bin/cinnamon-launcher", line 72, in <module>
    os.execvp(FALLBACK_COMMAND, (FALLBACK_COMMAND,) + FALLBACK_ARGS)
  File "/usr/lib/python3.9/os.py", line 574, in execvp
    _execvpe(file, args)
  File "/usr/lib/python3.9/os.py", line 616, in _execvpe
    raise last_exc
  File "/usr/lib/python3.9/os.py", line 607, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory
 ```

**Issue**
Cinnamon goes into fallback mode

**Steps to reproduce**

1. Create an Xorg configuration with multiple screens in ServerLayout
2. Start Cinnamon

**Expected behaviour**
Cinnamon starts normally

**Other information**
I've seen this issue #4276 but because it's quite old, I wanted to see if the situation was different, or if I'm possibly going about configuring my setup the wrong way. My setup is laptop screen running from the integrated graphics and external screen connected to dedicated graphics via HDMI. I put the Xorg configurations in the next section.

**Both monitors used, display extended, can move mouse across screens, different resolutions (laptop 1080p, external 1440p), Cinnamon crashes**
```
Section "ServerLayout"
    Identifier "Main Layout"
    Screen     0 "Screen0"
    Screen     1 "Screen1" RightOf "Screen0"
EndSection

Section "Monitor"
    Identifier  "HDMI"
EndSection

Section "Monitor"
    Identifier  "EDP"
EndSection

Section "Screen"
  Identifier "Screen1"
  Device "Device0"
  Monitor "HDMI"
EndSection

Section "Screen"
  Identifier "Screen0"
  Device "Device1"
  Monitor "EDP"
EndSection

Section "Device"
   Identifier   "Device0"
   Option "Monitor-HDMI-A-0" "HDMI"
   Driver   "amdgpu"
   BusID  "PCI:3:0:0"
EndSection

Section "Device"
   Identifier   "Device1"
   Option "Monitor-eDP" "EDP"
   Driver   "amdgpu"
   BusID  "PCI:8:0:0"
EndSection
```

**Only HDMI monitor used, Cinnamon works**
```
Section "ServerLayout"
    Identifier "Main Layout"
    Screen     1 "Screen1"
EndSection

Section "Monitor"
    Identifier  "HDMI"
EndSection

Section "Screen"
  Identifier "Screen1"
  Device "Device0"
  Monitor "HDMI"
EndSection

Section "Device"
   Identifier   "Device0"
   Option "Monitor-HDMI-A-0" "HDMI"
   Driver   "amdgpu"                   
   BusID  "PCI:3:0:0"
EndSection
```

**Comment by spocthier83** [comment]
Same bug as #9906 ?

**Comment by skipdashu** [comment]
Same problem trying to set up xorg for box with two GPUs for BOINC.

[(https://forums.linuxmint.com/viewtopic.php?t=404389)]
