### ISSUE TITLE
Recent update resurects the old problem of Settings not opening

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#10399]
```
 * Cinnamon version: 5.0.6
 * Distribution - Mint 20.2
 * Graphics hardware *and* driver used: Intel; Mesa/
 * 32 or 64 bit: 64.
 ```

**Issue**

```
$ cinnamon-settings
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 22, in <module>
    gi.require_version('Gtk', '3.0')
AttributeError: module 'gi' has no attribute 'require_version'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 12, in <module>
    import os, glob, subprocess, os.path, time, pwd, sys, requests_unixsocket
  File "/usr/lib/python3/dist-packages/requests_unixsocket/__init__.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

Original exception was:
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 22, in <module>
    gi.require_version('Gtk', '3.0')
AttributeError: module 'gi' has no attribute 'require_version'
```

**Steps to reproduce**

It seems to me that one of the following updates caused the problem.

![image](https://user-images.githubusercontent.com/47056543/137661690-2b27d5d8-faaf-44cc-9f3c-4b45f6f69030.png)

**Comment by LinuxOnTheDesktop** [comment]
The problem owes to the _Cinnamon_ package and specifically, I guess, to this change:

> cinnamon-settings: Remove ~/.local and /usr/local from python's module search paths.

Still, perhaps my Python stuff is setup wrongly somehow.

**Comment by LinuxOnTheDesktop** [comment]
Ah: duplicate of #10397.

And . .
```
$ pip3 list | grep -i pil
Pillow                            7.0.0
$ python3 -c "import sys; print(sys.path)"
['', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/<myUsername>/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.8/dist-packages']
$ python3 --version
Python 3.8.10
```
I add: I got things working again by commenting out
```
from bin import util
util.strip_syspath_locals()
```

in /usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py and /usr/share/cinnamon/cinnamon-settings/xlet-settings.py.

**Comment by yehudade** [comment]
Given the move to `usrmerge`, why is `/usr/local` being stripped?

https://www.freedesktop.org/wiki/Software/systemd/TheCaseForTheUsrMerge/

For reference, the change was made in PR #10224

**Comment by leigh123linux** [comment]
@yehudade  /usr/local is excluded to prevent users from breaking settings with their useless python installs.
