### ISSUE TITLE
cinnamon-menu-editor fails to run when python 3.10+ is in use

### ISSUE THREAD

**Issue by miliarch** [linuxmint/cinnamon#10526]
```
 * Cinnamon version: Cinnamon 5.0.7
 * Distribution: Arch Linux
 ```

**Issue**

cinnamon-menu-editor fails to run when python 3.10+ is installed as the system python version

When running from the configure menu, failure is silent, there is no user feedback to indicate that a failure has occurred.

When running directly:
```
Traceback (most recent call last):
  File "/usr/bin/cinnamon-menu-editor", line 12, in <module>
    from cme import MainWindow
  File "/usr/share/cinnamon/cinnamon-menu-editor/cme/MainWindow.py", line 34, in <module>
    from cme.MenuEditor import MenuEditor
  File "/usr/share/cinnamon/cinnamon-menu-editor/cme/MenuEditor.py", line 23, in <module>
    from cme import util
  File "/usr/share/cinnamon/cinnamon-menu-editor/cme/util.py", line 22, in <module>
    from collections import Sequence
ImportError: cannot import name 'Sequence' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

**Steps to reproduce**

1. Ensure python 3.10+ is installed
2. Run cinnamon-menu-editor in terminal
3. Observe failure to launch

**Expected behaviour**

The cinnamon-menu-editor interface appears

**Other information**

According to [Python 3.9 Documentation](https://docs.python.org/3.9/library/collections.html):
>Deprecated since version 3.3, will be removed in version 3.10: Moved [Collections Abstract Base Classes](https://docs.python.org/3.9/library/collections.abc.html#collections-abstract-base-classes) to the [collections.abc](https://docs.python.org/3.9/library/collections.abc.html#module-collections.abc) module. For backwards compatibility, they continue to be visible in this module through Python 3.9.

This is the cause of the `Sequence` class failing to import from `collections` - `collections.abc` contains the module today.

**Comment by miliarch** [comment]
Aha - this seems to already be fixed in master:
https://github.com/linuxmint/cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-menu-editor/cme/util.py
```
import sys
if sys.version_info[:2] >= (3, 8):
    from collections.abc import Sequence
else:
    from collections import Sequence
```

Dupe of:
https://github.com/linuxmint/cinnamon/pull/10370

I've confirmed that change works on my own system. Now I suppose it's a waiting game for Arch specific packages to be updated =)
