### ISSUE TITLE
Cinnamon-menu-editor bug

### ISSUE THREAD

**Issue by SL-Pirate** [linuxmint/cinnamon#10527]
```
 * Cinnamon version  5.0.7
 * Distribution - Arch linux
 * 64 bit

**Issue**
```
Traceback (most recent call last):
  File "/usr/bin/cinnamon-menu-editor", line 12, in <module>
    from cme import MainWindow
  File "/usr/share/cinnamon/cinnamon-menu-editor/cme/MainWindow.py", line 34, in <module>
    from cme.MenuEditor import MenuEditor
  File "/usr/share/cinnamon/cinnamon-menu-editor/cme/MenuEditor.py", line 23, in <module>
    from cme import util
  File "/usr/share/cinnamon/cinnamon-menu-editor/cme/util.py", line 22, in <module>
    from collections import Sequence
ImportError: cannot import name 'Sequence' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```


**Steps to reproduce**
Run `cinnamon-menu-editor` from the terminal
pressing open menu editor from menu configure program does nothing

**Comment by SL-Pirate** [comment]
Now it's working fine again. TY
<3
