### ISSUE TITLE
org.cinnamon.CalendarServer  Traceback...

### ISSUE THREAD

**Issue by misterhsp** [linuxmint/cinnamon#10639]
Cinnamon version (5.2.7)

In Debian SID always shows the following in the journal shortly after starting Cinnamon. Reproducible

```
org.cinnamon.CalendarServer[4302]: Traceback (most recent call last):
org.cinnamon.CalendarServer[4302]:   File "/usr/libexec/cinnamon-calendar-server.py", line 136, in got_registry_callback
org.cinnamon.CalendarServer[4302]:     self.update_status()
org.cinnamon.CalendarServer[4302]:   File "/usr/libexec/cinnamon-calendar-server.py", line 198, in update_status
org.cinnamon.CalendarServer[4302]:     enabled_sources = self.registry.list_enabled(EDataServer.SOURCE_EXTENSION_CALENDAR)
org.cinnamon.CalendarServer[4302]: AttributeError: 'NoneType' object has no attribute 'list_enabled'

```

**Comment by mtwebster** [comment]
Can you run:
```
cinnamon-calendar-server
```
And paste the entire output? I'm curious if there were any additional warnings prior to that traceback.

Thanks

**Comment by misterhsp** [comment]
```
holgi@hsp1~ $ LANG=C cinnamon-calendar-server 
g-dbus-error-quark: Error calling StartServiceByName for org.gnome.evolution.dataserver.Sources5: Failed to execute program org.gnome.evolution.dataserver.Sources5: No such file or directory (23)
Traceback (most recent call last):
  File "/usr/libexec/cinnamon-calendar-server.py", line 136, in got_registry_callback
    self.update_status()
  File "/usr/libexec/cinnamon-calendar-server.py", line 198, in update_status
    enabled_sources = self.registry.list_enabled(EDataServer.SOURCE_EXTENSION_CALENDAR)
AttributeError: 'NoneType' object has no attribute 'list_enabled'

```
