### ISSUE TITLE
getDiskSize size fssIze

### ISSUE THREAD

**Issue by themrigi** [linuxmint/cinnamon#10633]
https://github.com/linuxmint/cinnamon/blob/ef463cc0aaedd714f2956daab227aeda1d87897e/files/usr/share/cinnamon/cinnamon-settings/modules/cs_info.py#L60

lsblk from util-linux 2.27.1;
lsblk --json --output size --bytes --nodeps

`out = getProcessOut(("lsblk", "--json", "--output", "fssIze", "--bytes", "--nodeps"))
    jsonobj = loads(''.join(out))`
    
ubuntu 20.04, lsblk from util-linux 2.34;
lsblk --json --output **fssIze** --bytes --nodeps

`
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 730, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 431, in __init__
    self.go_to_sidepage(cat, path, user_action=False)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 188, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 212, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_info.py", line 148, in on_module_selected
    infos = createSystemInfos()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_info.py", line 120, in createSystemInfos
    diskSize, multipleDisks = getDiskSize()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_info.py", line 60, in getDiskSize
    jsonobj = loads(''.join(out))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

**Comment by leigh123linux** [comment]
Use the template next time to provide the required info.

**Comment by themrigi** [comment]
sorry. I didn't know the template was more important than the problem.
