### ISSUE TITLE
Window borders cannot be changed

### ISSUE THREAD

**Issue by walkingbeard** [linuxmint/cinnamon#10676]
```
 * Cinnamon 5.2.7
 * Mint 20.3
 * Nvidia GTK 770 / nvidia driver 470
 * 64 bit
 * [~/.xsession-errors](https://github.com/linuxmint/cinnamon/files/8089583/xsession-errors.txt)
 ```

**Issue**
Window border theme cannot be changed in Settings->Themes. No matter which I choose it always looks the same. Dark mode is respected, however.
![arc-dark](https://user-images.githubusercontent.com/83006/154507335-574e2fb4-e715-4357-9261-509ac92f6dcd.png)

**Steps to reproduce**
I have no idea.

**Expected behaviour**
Window border theme should change when a new one is selected in Settings->Themes.

**Other information**
- No errors are reported when running `cinnamon-settings themes` in the terminal.
- Driver manager also does not load, and running from the terminal produces this:
```
Checking Internet connectivity...
  --> Internet connection detected.
WARNING:root:_pkg_get_support nvidia-driver-390: package has invalid Support Legacyheader, cannot determine support level
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintdrivers/mintdrivers.py", line 555, in show_drivers
    brand_icon.set_from_pixbuf(self.get_device_icon(self.devices[device]))
  File "/usr/lib/linuxmint/mintdrivers/mintdrivers.py", line 516, in get_device_icon
    return (GdkPixbuf.Pixbuf.new_from_file_at_size("/usr/share/linuxmint/mintdrivers/icons/%s.svg" % icon, 48, -1))
gi.repository.GLib.Error: gdk-pixbuf-error-quark: Couldn’t recognise the image file format for file “/usr/share/linuxmint/mintdrivers/icons/nvidia.svg” (3)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_linuxmint_mintdrivers_mintdrivers.py.0.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintdrivers/mintdrivers.py", line 555, in show_drivers
    brand_icon.set_from_pixbuf(self.get_device_icon(self.devices[device]))
  File "/usr/lib/linuxmint/mintdrivers/mintdrivers.py", line 516, in get_device_icon
    return (GdkPixbuf.Pixbuf.new_from_file_at_size("/usr/share/linuxmint/mintdrivers/icons/%s.svg" % icon, 48, -1))
gi.repository.GLib.Error: gdk-pixbuf-error-quark: Couldn’t recognise the image file format for file “/usr/share/linuxmint/mintdrivers/icons/nvidia.svg” (3)
```
The Driver Manager window remains open, showing "Looking for hardware drivers..."

**Comment by walkingbeard** [comment]
Closing after two years. I don't even remember this.
