### ISSUE TITLE
Multi window switch on taskbar

### ISSUE THREAD

**Issue by sonichy** [linuxmint/cinnamon#10917]
```
 * Cinnamon 5.4.2
 * Arch
 * 64 bit
 ```

**Steps to reproduce**
Multi windows (such as >2 terminal), window icon will display number of windows on top-left.
Click window icon on taskbar, show or hide just a window.

**Expected behaviour**
Switch between windows like other Linux taskbar.

**Comment by alicavus** [comment]
I had same issue with `expo@cinnamon.org` and `workspace-switcher@cinnamon.org` .  I was not able to switch between workspaces, cinnamon hangs on expo view (hot corner) when there is not any windows open. Cinnamon was crashing when closing a workspace. 

My `xsession-errors` files have multiple lines:
<pre>(cinnamon:1275): Clutter-CRITICAL **: 06:49:44.505: clutter_input_focus_set_cursor_location: assertion 'clutter_input_focus_is_focused (focus)' failed
Bug in window manager: Workspace does not exist to index!
** Message: 06:53:24.358: updates_checker.vala:101: 0 updates found
Exception in thread Thread-2 (wait_for_process):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/bin/cinnamon-launcher", line 87, in wait_for_process
    os.execvp(FALLBACK_COMMAND, (FALLBACK_COMMAND,) + FALLBACK_ARGS)
  File "/usr/lib/python3.10/os.py", line 574, in execvp
    _execvpe(file, args)
  File "/usr/lib/python3.10/os.py", line 616, in _execvpe
    raise last_exc
  File "/usr/lib/python3.10/os.py", line 607, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory
None: no process found
</pre>

Some laptops have ghost display(s), second VGA output is activated despite is not plugged to second output. This was the case in my issue. I switched off ghost display and all is working as expexted.
![](https://i.ibb.co/kDcCnfn/Screenshot-from-2022-07-10-09-37-35.png)

**Comment by sonichy** [comment]
My mean is window not workspace !
