### ISSUE TITLE
Removing workspace crashes cinnamon

### ISSUE THREAD

**Issue by trourance** [linuxmint/cinnamon#10941]
```
Cinnamon 5.4.2
Manjaro Linux
Advanced Micro Devices, Inc. [AMD/ATI] Renoir (rev d1) (prog-if 00 [VGA controller])
amdgpu
64 bit
~/.xsession-errors
 ```
```
(cinnamon:15236): Gjs-CRITICAL **: 23:29:21.811: Object .Gjs_fake_group (0x557130002b30), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x55712dd121c0 ==
#0   55712e8fd948 i   /usr/share/cinnamon/js/ui/dnd.js:528 (21f52641d7e0 @ 1308)
#1   7ffc549d1b10 b   resource:///org/gnome/gjs/modules/script/_legacy.js:83 (3c2beaf33c90 @ 69)
#2   7ffc549d2260 b   /usr/share/cinnamon/js/ui/dnd.js:199 (21f52641dab0 @ 89)
#3   7ffc549d2340 b   resource:///org/gnome/gjs/modules/script/_legacy.js:83 (3c2beaf33c90 @ 69)
#4   7ffc549d2400 b   /usr/share/cinnamon/js/ui/dnd.js:57 (21f52641de20 @ 18)

(cinnamon:15236): Gjs-CRITICAL **: 23:29:21.813: Object .Gjs_fake_group (0x557130002b30), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x55712dd121c0 ==
#0   55712e8fda40 i   /usr/share/cinnamon/js/ui/dnd.js:659 (21f52641d650 @ 47)
#1   7ffc549d1100 b   resource:///org/gnome/gjs/modules/script/_legacy.js:83 (3c2beaf33c90 @ 69)
#2   55712e8fd948 i   /usr/share/cinnamon/js/ui/dnd.js:539 (21f52641d7e0 @ 1499)
#3   7ffc549d1b10 b   resource:///org/gnome/gjs/modules/script/_legacy.js:83 (3c2beaf33c90 @ 69)
#4   7ffc549d2260 b   /usr/share/cinnamon/js/ui/dnd.js:199 (21f52641dab0 @ 89)
#5   7ffc549d2340 b   resource:///org/gnome/gjs/modules/script/_legacy.js:83 (3c2beaf33c90 @ 69)
#6   7ffc549d2400 b   /usr/share/cinnamon/js/ui/dnd.js:57 (21f52641de20 @ 18)
Bug in window manager: Workspace does not exist to index!
Exception in thread Thread-2 (wait_for_process):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/bin/cinnamon-launcher", line 87, in wait_for_process
    os.execvp(FALLBACK_COMMAND, (FALLBACK_COMMAND,) + FALLBACK_ARGS)
  File "/usr/lib/python3.10/os.py", line 574, in execvp
    _execvpe(file, args)
  File "/usr/lib/python3.10/os.py", line 616, in _execvpe
    raise last_exc
  File "/usr/lib/python3.10/os.py", line 607, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type
None: aucun processus trouvé
```

**Issue**
When a workspace is removed, cinnamon crashes and ask if you want to restart it.

**Steps to reproduce**
- Start cinnamon with 2 initial workspaces
- Add a new workspace using the "+"
- Remove the second workspace in-between

**Expected behaviour**
Don't crash and remove the selected workspace

**Comment by Araya2001** [comment]
Currently having the same issue on Cinnamon 5.4.3

**Comment by MartNytrm** [comment]
Can confirm this issue on on 5.15.55-1-MANJARO, Cinnamon 5.4.3-1, NVIDIA 470.129.06.
Additionally: For me, cinnamon hangs/crashes all the time when using two workspaces and going into "show all workspace" overview via screen edge. Using three workspaces just works fine.

**Comment by JosephMcc** [comment]
These issues should now be fixed when you get the updates on your distro.
