### ISSUE TITLE
Error when I try to open cinnamon-settings

### ISSUE THREAD

**Issue by Vykynger** [linuxmint/cinnamon#10994]
```
 * Cinnamon 4.6.7
 * Distribution  Alma Linux 8.6
 * No Graphics Card but Intel 12. Gen internal graphics
 * 64 bit

**Issue**
When I try to start cinnamon-settings via terminal I get the following python Traceback:
bash-4.4$ cinnamon-settings
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 27, in <module>
    import SettingsWidgets
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 11, in <module>
    from xapp.SettingsWidgets import SettingsWidget, SettingsLabel
  File "/usr/lib/python3.6/site-packages/xapp/SettingsWidgets.py", line 428, in <module>
    class FontButton(SettingsWidget):
  File "/usr/lib/python3.6/site-packages/xapp/SettingsWidgets.py", line 432, in FontButton
    def __init__(self, label, level=(Gtk.FontChooserLevel.STYLE | Gtk.FontChooserLevel.SIZE), size_group=None, dep_key=None, tooltip=""):
  File "/usr/lib64/python3.6/site-packages/gi/overrides/__init__.py", line 39, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib64/python3.6/site-packages/gi/module.py", line 145, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Gtk' object has no attribute 'FontChooserLevel'


**Steps to reproduce**
Unfortunately, I don't know what caused this issue, as I did not try to open the cinnamon settings for a while. It might be because I installed and subsequently removed dolphin. Another thing I did just before this issue occurred was to start a x2go session with the PC as a server. As desktop for this X2Go session, I used IceWM. I really hope that you can help me, as I could not really find any helpful advice online. Only the following Mint forum page: https://forums.linuxmint.com/viewtopic.php?t=316782


**Expected behaviour**
Open Cinnamon Settings


**Other information**
none, but feel free to ask me.

**Comment by KittyMae** [comment]
I have the same issue :(
Any progress?

**Comment by leigh123linux** [comment]
Cinnamon-4.xx is no longer supported, report the issue to the repo that supplies cinnamon.

gtk3 provides the missing attribute

```
AttributeError: 'gi.repository.Gtk' object has no attribute 'FontChooserLevel'
```
