### ISSUE TITLE
Creation of new user failed when using symbols in cinnamon-settings-user app and the applet crashes as well

### ISSUE THREAD

**Issue by fjrg76-com** [linuxmint/cinnamon#11157]
```
 * Cinnamon version: 5.2.7
 * Mint 20.3
 * 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
[xsession-errors_partial.txt](https://github.com/linuxmint/cinnamon/files/9523408/xsession-errors_partial.txt)

 ```

### Issue
1.- A new user cannot be created in cinnamon-settings-user applet if the user name or the full name use any of the (allowed) symbols: .,- or _

2.- A user can be actually created using the _ symbol (but not with the . symbol); however, after deleting it immediately the applet crashes:

(cinnamon-settings-users.py:206033): accountsservice-CRITICAL **: 22:25:17.035: act_user_get_user_name: assertion 'ACT_IS_USER (user)' failed
Segmentation fault (core dumped)

### Steps to reproduce
Write in a console:
$ sudo cinnamon-settings-users 

and when the applet shows up write any user name that includes the symbols ., -, _, for example user.1, or user_1

The applet stablishes that such symbols are the only ones allowed to be used in the user name.

If you could create a user, delete it immediately in order the applet to crash.

### Expected behaviour
A user name that includes any of these symbols (., -, _) must be created using the Cinnamon's User and groups applet.

The applet shouldn't crash.

### Other information

New user creation:

Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings-users/cinnamon-settings-users.py", line 897, in on_user_addition
    new_user = self.accountService.create_user(username, fullname, account_type)
gi.repository.GLib.Error: act_user_manager_error: GDBus.Error:org.freedesktop.Accounts.Error.Failed: running '/usr/sbin/adduser' failed: El proceso hijo terminó con el código 1 (0)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No existe el archivo o el directorio: '/var/crash/_usr_share_cinnamon_cinnamon-settings-users_cinnamon-settings-users.py.0.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings-users/cinnamon-settings-users.py", line 897, in on_user_addition
    new_user = self.accountService.create_user(username, fullname, account_type)
gi.repository.GLib.Error: act_user_manager_error: GDBus.Error:org.freedesktop.Accounts.Error.Failed: running '/usr/sbin/adduser' failed: El proceso hijo terminó con el código 1 (0)

**Comment by alchiweb** [comment]
If there is a '.' (dot character), "create_user" of the accountService (UserManager of AccountsService) throw an exception.
So, we could (in the 'cinnamon-settings-users.py' file):
 - catch the exception like this:
```python
     def on_user_addition(self, event):
        dialog = NewUserDialog(self.window)
        response = dialog.run()
        if response == Gtk.ResponseType.OK:
            try:
                if dialog.account_type_combo.get_active() == 1:
                    account_type = AccountsService.UserAccountType.ADMINISTRATOR
                else:
                    account_type = AccountsService.UserAccountType.STANDARD
                fullname = dialog.realname_entry.get_text()
                username = dialog.username_entry.get_text()
                new_user = self.accountService.create_user(username, fullname, account_type)
                new_user.set_password_mode(AccountsService.UserPasswordMode.NONE)
                pixbuf = GdkPixbuf.Pixbuf.new_from_file_at_size("/usr/share/cinnamon/faces/user-generic.png", 48, 48)
                description = "<b>%s</b>\n%s" % (GLib.markup_escape_text(fullname), GLib.markup_escape_text(username))
                piter = self.users.append(None, [new_user, pixbuf, description])
                # Add the user to his/her own group and sudo if Administrator was selected
                if dialog.account_type_combo.get_active() == 1:
                    subprocess.call(["usermod", username, "-G", "%s,sudo,nopasswdlogin" % username])
                else:
                    subprocess.call(["usermod", username, "-G", "%s,nopasswdlogin" % username])
                self.load_groups()
            except Exception as detail:
                print(detail)
        dialog.destroy()
```
But the dialog box will close without user alert message...
 - change the RegEx ` '[^a-z0-9_.-]'` by `'[^a-z0-9_-]'`
 - change the comments (don't forget all the locales files...):
```python
label.set_markup(_("The username must consist of only:\n    - lower case letters (a-z)\n    - numerals (0-9)\n    - '-' and '_' characters"))
```
