### ISSUE TITLE
Cinnamon lockscreen goes away withput password entry with error `Method Lock is not implemented on interface org.cinnamon.ScreenSaver`

### ISSUE THREAD

**Issue by ipaqmaster** [linuxmint/cinnamon#11253]
```
 * Cinnamon 5.4.12 (community/cinnamon -- Archlinux official repo)
 * Distribution - Archlinux
 * Intel Xe Integrated Graphics (Have experienced this on a variety of hardware combinations)
 * 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

### Issue

```
$ cinnamon-screensaver-command -l
Traceback (most recent call last):
  File "/usr/bin/cinnamon-screensaver-command", line 98, in _on_proxy_ready
    self.perform_action()
  File "/usr/bin/cinnamon-screensaver-command", line 115, in perform_action
    self.proxy.call_lock_sync(self.message)
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method Lock is not implemented on interface org.cinnamon.ScreenSaver (19)

```

### Steps to reproduce

1. Run `cinnamon-screensaver-command -l`
2. Move mouse or press any key. No password will be required and above error will be spit out.

### Expected behaviour

Password prompt appears before revealing desktop after successful entry.

### Other information

Been experiencing this on and off for a while on various PCs over the past few months.

I have also experienced this behavior in some brand new fresh Archlinux installs over the past few months.

**Comment by rcalixte** [comment]
@ipaqmaster Can you include the output of `cinnamon-screensaver-command --version`? I'm not able to reproduce your problem on any of my machines. My output is below:

```bash
$ cinnamon-screensaver-command --version
cinnamon-screensaver 5.4.4
```

Additionally, can you confirm that all dependencies are installed for the `cinnamon-screensaver` package?

**Comment by ipaqmaster** [comment]
```
$ cinnamon-screensaver-command --version
cinnamon-screensaver 5.4.4
```


Yep same here. Something seems to constantly upset cinnamon's lockscreen every few months,

**Comment by rcalixte** [comment]
This does appear to be a consistent issue with Arch and Arch-based distros:
#8685
linuxmint/cinnamon-screensaver#194

It also appears to be an issue with some of the dependencies. I don't have an educated guess to offer as to which unfortunately. There are [13 dependencies currently listed for the cinnamon-screensaver package](https://archlinux.org/packages/community/x86_64/cinnamon-screensaver), I would see if you can get them rebuilt, maybe starting with the GObject ones based on the exception you pasted above. Then possibly work through the remainder of the Python dependencies and then finally cinnamon-screensaver itself. (I'm not sure if the builds happen based on tags/releases or git.)

**Comment by quartchug** [comment]
When I let the screensaver activate by itself, it recognizes the system settings that shut off lockscreen, and so when I move the mouse the screensaver just disappears, which is all good.
However, when I activate the screensaver using ctrl-alt-L, it overrides the system settings. It requires a password when I move the mouse.

System:
  Kernel: 5.15.0-78-generic x86_64 bits: 64 compiler: gcc v: 11.3.0 Desktop: Cinnamon 5.8.4
    tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop System: ASUS product: N/A v: N/A serial: <superuser required>
  Mobo: ASUSTeK model: ROG CROSSHAIR X670E HERO v: Rev 1.xx serial: <superuser required>
    UEFI: American Megatrends v: 1415 date: 05/16/2023
CPU:
  Info: 16-core model: AMD Ryzen 9 7950X bits: 64 type: MT MCP arch: Zen 3 rev: 2 cache:
    L1: 1024 KiB L2: 16 MiB L3: 64 MiB
  Speed (MHz): avg: 3065 high: 3928 min/max: 3000/5880 boost: enabled cores: 1: 2751 2: 3261
    3: 3599 4: 2878 5: 2800 6: 2879 7: 2771 8: 2875 9: 2880 10: 2879 11: 3597 12: 3599 13: 3597
    14: 2879 15: 2878 16: 2881 17: 2879 18: 3597 19: 3928 20: 2798 21: 2876 22: 2879 23: 2854
    24: 2796 25: 2877 26: 2880 27: 3598 28: 2879 29: 3599 30: 2879 31: 2879 32: 2881
    bogomips: 287981
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: NVIDIA driver: nvidia v: 535.86.05 pcie: speed: 2.5 GT/s lanes: 16 ports: active: none
    off: DP-1 empty: DP-2,DP-3,HDMI-A-1 bus-ID: 01:00.0 chip-ID: 10de:2684
  Device-2: AMD vendor: ASUSTeK driver: N/A pcie: speed: 16 GT/s lanes: 16 bus-ID: 6c:00.0
    chip-ID: 1002:164e
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: nvidia
    unloaded: fbdev,modesetting,nouveau,vesa gpu: nvidia display-ID: :0 screens: 1
  Screen-1: 0 s-res: 4558x1908 s-dpi: 145
  Monitor-1: DP-0 res: 4558x1908 dpi: 145 diag: 864mm (34")
  OpenGL: renderer: NVIDIA GeForce RTX 4090/PCIe/SSE2 v: 4.6.0 NVIDIA 535.86.05
    direct render: Yes
Audio:
  Device-1: NVIDIA driver: snd_hda_intel v: kernel pcie: speed: 16 GT/s lanes: 16 bus-ID: 01:00.1
    chip-ID: 10de:22ba
  Device-2: AMD vendor: ASUSTeK driver: snd_hda_intel v: kernel pcie: speed: 16 GT/s lanes: 16
    bus-ID: 6c:00.1 chip-ID: 1002:1640
  Device-3: ASUSTek USB Audio type: USB driver: hid-generic,snd-usb-audio,usbhid bus-ID: 3-11:4
    chip-ID: 0b05:1a53
  Sound Server-1: ALSA v: k5.15.0-78-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel Wi-Fi 6 AX210/AX211/AX411 160MHz driver: iwlwifi v: kernel pcie: speed: 5 GT/s
    lanes: 1 bus-ID: 08:00.0 chip-ID: 8086:2725
  IF: wlp8s0 state: down mac: <filter>
  Device-2: Intel Ethernet I225-V vendor: ASUSTeK driver: igc v: kernel pcie: speed: 5 GT/s
    lanes: 1 port: N/A bus-ID: 09:00.0 chip-ID: 8086:15f3
  IF: eno1 state: up speed: 1000 Mbps duplex: full mac: <filter>
  IF-ID-1: vmnet1 state: unknown speed: N/A duplex: N/A mac: <filter>
  IF-ID-2: vmnet8 state: unknown speed: N/A duplex: N/A mac: <filter>
Bluetooth:
  Device-1: Intel AX210 Bluetooth type: USB driver: btusb v: 0.8 bus-ID: 3-6:3 chip-ID: 8087:0032
  Report: hciconfig ID: hci0 rfk-id: 0 state: down bt-service: enabled,running rfk-block:
    hardware: no software: yes address: <filter>
Drives:
  Local Storage: total: 12.74 TiB used: 55.97 GiB (0.4%)
  ID-1: /dev/nvme0n1 vendor: Kingston model: SFYRD2000G size: 1.82 TiB speed: 63.2 Gb/s lanes: 4
    serial: <filter> temp: 32.9 C
  ID-2: /dev/nvme1n1 vendor: Kingston model: SFYRD4000G size: 3.64 TiB speed: 63.2 Gb/s lanes: 4
    serial: <filter> temp: 29.9 C
  ID-3: /dev/sda vendor: Western Digital model: WD8003FFBX-68B9AN0 size: 7.28 TiB
    speed: 6.0 Gb/s serial: <filter>
Partition:
  ID-1: / size: 5.43 TiB used: 55.93 GiB (1.0%) fs: ext4 dev: /dev/sda4
  ID-2: /boot/efi size: 96 MiB used: 34.8 MiB (36.3%) fs: vfat dev: /dev/nvme0n1p1
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 0 KiB (0.0%) priority: -2 file: /swapfile
Sensors:
  System Temperatures: cpu: N/A mobo: N/A gpu: nvidia temp: 42 C
  Fan Speeds (RPM): N/A gpu: nvidia fan: 0%
Repos:
  Packages: 2459 apt: 2446 flatpak: 13
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http: //packages.linuxmint.com victoria main upstream import backport
    2: deb http: //archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
    3: deb http: //archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/vivaldi.list
    1: deb [arch=amd64] https: //repo.vivaldi.com/stable/deb/ stable main
Info:
  Processes: 533 Uptime: 3d 20h 31m Memory: 124.94 GiB used: 5.63 GiB (4.5%) Init: systemd v: 249
  runlevel: 5 Compilers: gcc: 11.4.0 alt: 11/12 Client: Cinnamon v: 5.8.4 inxi: 3.3.13
