### ISSUE TITLE
Computer crashes after launching a program

### ISSUE THREAD

**Issue by joschi2k** [linuxmint/cinnamon#11560]
Hello there,
i am realtivly new with Linux, so pls bare with me.

I am using an Finite Element program "tochnog" with a UMAT subroutine. The program works totally fine (without Umat) on the computer till the moment i wanna use the umat.so subroutine, wich is located in /usr/lib and compiled with gnu. 3 seconds after i start the program, the screen goes black and nothing works anymore, not even the reset button of the computer. Only option is to use the power switch to get it running again.

The strange thing is that the exact same programme with same configurations works on our other linux computers flawless, which means it can't be the fault of the files or the compiling.
I allready opened an issues at :
[https://forums.linuxmint.com/viewtopic.php?t=393313](url)

There it was suggested it could be a problem with my cinnamon version.

Sytem information: 
`System:
  Kernel: 5.4.0-144-generic x86_64 bits: 64 Desktop: Cinnamon 5.2.7 
  Distro: Linux Mint 20.3 Una 
Machine:
  Type: Desktop Mobo: Micro-Star model: TRX40 PRO WIFI (MS-7C60) v: 1.0 
  serial: <filter> UEFI: American Megatrends LLC. v: 2.75 date: 01/15/2021 
CPU:
  Topology: 64-Core (8-Die) model: AMD Ryzen Threadripper 3990X bits: 64 
  type: MT MCP MCM L2 cache: 32.0 MiB 
  Speed: 2198 MHz min/max: 2200/2900 MHz Core speeds (MHz): 1: 2197 2: 2199 
  3: 1878 4: 2199 5: 2196 6: 2198 7: 2195 8: 2199 9: 2200 10: 2197 11: 2195 
  12: 2196 13: 2199 14: 2808 15: 2200 16: 2196 17: 2199 18: 2200 19: 2198 
  20: 2197 21: 2198 22: 2199 23: 2197 24: 2199 25: 2196 26: 2201 27: 2196 
  28: 2196 29: 2197 30: 2200 31: 2197 32: 2195 33: 2201 34: 2198 35: 2195 
  36: 2198 37: 2199 38: 2197 39: 2200 40: 2199 41: 2195 42: 2196 43: 2197 
  44: 2196 45: 2198 46: 2200 47: 2199 48: 2199 49: 2199 50: 2183 51: 2703 
  52: 2195 53: 2189 54: 2187 55: 2198 56: 2200 57: 2193 58: 2198 59: 2198 
  60: 2200 61: 2200 62: 2196 63: 2193 64: 2199 65: 2199 66: 2199 67: 2195 
  68: 2200 69: 2196 70: 2201 71: 2197 72: 2199 73: 2199 74: 2194 75: 2199 
  76: 2199 77: 2198 78: 2197 79: 2198 80: 2199 81: 2196 82: 2200 83: 2200 
  84: 2200 85: 2201 86: 2196 87: 2196 88: 2199 89: 2197 90: 2201 91: 2196 
  92: 2196 93: 2202 94: 2198 95: 2201 96: 2196 97: 2197 98: 2201 99: 1867 
  100: 1866 101: 1862 102: 2800 103: 2199 104: 2199 105: 2194 106: 2196 
  107: 1863 108: 2195 109: 2199 110: 2194 111: 2197 112: 2194 113: 2200 
  114: 2200 115: 2200 116: 2194 117: 2199 118: 1864 119: 2195 120: 2196 
  121: 2190 122: 2698 123: 2186 124: 2190 125: 2199 126: 2197 127: 2198 
  128: 2196 
Graphics:
  Device-1: NVIDIA GP106GL [Quadro P2000] driver: nvidia v: 470.161.03 
  Display: x11 server: X.Org 1.20.13 driver: nvidia 
  unloaded: fbdev,modesetting,nouveau,vesa resolution: 1920x1080~60Hz 
  OpenGL: renderer: Quadro P2000/PCIe/SSE2 v: 4.6.0 NVIDIA 470.161.03 
Audio:
  Device-1: NVIDIA GP106 High Definition Audio driver: snd_hda_intel 
  Device-2: AMD Starship/Matisse HD Audio driver: N/A 
  Device-3: Micro Star USB Audio type: USB 
  driver: hid-generic,snd-usb-audio,usbhid 
  Sound Server: ALSA v: k5.4.0-144-generic 
Network:
  Device-1: Intel I211 Gigabit Network driver: igb 
  IF: eno1 state: down mac: <filter> 
  Device-2: Intel I211 Gigabit Network driver: igb 
  IF: enp69s0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
  Device-3: Intel Wi-Fi 6 AX200 driver: iwlwifi 
  IF: wlo2 state: down mac: <filter> 
Drives:
  Local Storage: total: 5.01 TiB used: 2.37 TiB (47.3%) 
  ID-1: /dev/nvme0n1 vendor: Gigabyte model: GP-ASM2NE6100TTTD 
  size: 931.51 GiB 
  ID-2: /dev/nvme1n1 vendor: Gigabyte model: GP-ASM2NE6500GTTD 
  size: 465.76 GiB 
  ID-3: /dev/sda vendor: Samsung model: SSD 860 PRO 512GB size: 476.94 GiB 
  ID-4: /dev/sdb vendor: Seagate model: ST4000VN008-2DR166 size: 3.64 TiB 
Partition:
  ID-1: / size: 467.89 GiB used: 47.52 GiB (10.2%) fs: ext4 dev: /dev/sda5 
Sensors:
  System Temperatures: cpu: 46.1 C mobo: N/A gpu: nvidia temp: 34 C 
  Fan Speeds (RPM): N/A gpu: nvidia fan: 46% 
Info:
  Processes: 1257 Uptime: 1h 13m Memory: 31.34 GiB used: 2.15 GiB (6.9%) 
  Shell: bash inxi: 3.0.38 `

The two other computers on witch the "UMAT" is working:
Computer1:
`fachgebiet@Tochnog4:~$ inxi -Fz
System:
  Kernel: 5.4.0-135-generic x86_64 bits: 64 Desktop: Cinnamon 5.0.7 
  Distro: Linux Mint 20.2 Uma 
Machine:
  Type: Server Mobo: ASUSTeK model: Z10PE-D8 WS v: Rev 1.xx serial: <filter> 
  UEFI [Legacy]: American Megatrends v: 3304 date: 06/22/2016 
CPU:
  Topology: 2x 10-Core model: Intel Xeon E5-2640 v4 bits: 64 
  type: MT MCP SMP L2 cache: 50.0 MiB 
  Speed: 2594 MHz min/max: 1200/3400 MHz Core speeds (MHz): 1: 2594 2: 2594 
  3: 2594 4: 2594 5: 2594 6: 2594 7: 2594 8: 2594 9: 2594 10: 2594 11: 2594 
  12: 2594 13: 2594 14: 2594 15: 2594 16: 2594 17: 2594 18: 2594 19: 2594 
  20: 2594 21: 2594 22: 2594 23: 2594 24: 2594 25: 2594 26: 2594 27: 2594 
  28: 2594 29: 2594 30: 2594 31: 2594 32: 2594 33: 2594 34: 2594 35: 2594 
  36: 2594 37: 2594 38: 2594 39: 2594 40: 2594 
Graphics:
  Device-1: NVIDIA GK208B [GeForce GT 710] driver: nvidia v: 450.216.04 
  Device-2: ASPEED Graphics Family driver: ast v: kernel 
  Display: x11 server: X.Org 1.20.13 driver: modesetting,nvidia 
  unloaded: fbdev,nouveau,vesa resolution: 1920x1080~60Hz 
  OpenGL: renderer: GeForce GT 710/PCIe/SSE2 v: 4.6.0 NVIDIA 450.216.04 
Audio:
  Device-1: Intel C610/X99 series HD Audio driver: snd_hda_intel 
  Device-2: NVIDIA GK208 HDMI/DP Audio driver: snd_hda_intel 
  Sound Server: ALSA v: k5.4.0-135-generic 
Network:
  Device-1: Intel I210 Gigabit Network driver: igb 
  IF: enp6s0 state: down mac: <filter> 
  Device-2: Intel I210 Gigabit Network driver: igb 
  IF: enp7s0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
Drives:
  Local Storage: total: 3.98 TiB used: 532.91 GiB (13.1%) 
  ID-1: /dev/sda vendor: SK Hynix model: HFS250G32TND-N1A2A size: 232.89 GiB 
  ID-2: /dev/sdb vendor: Western Digital model: WD40E31X-00HY4A0 
  size: 3.64 TiB 
  ID-3: /dev/sdc vendor: SK Hynix model: HFS120G32TND-N1A2A size: 111.79 GiB 
Partition:
  ID-1: / size: 165.29 GiB used: 45.82 GiB (27.7%) fs: ext4 dev: /dev/sda1 
Sensors:
  System Temperatures: cpu: 46.0 C mobo: N/A gpu: nvidia temp: 49 C 
  Fan Speeds (RPM): N/A gpu: nvidia fan: 50% 
Info:
  Processes: 585 Uptime: 71d 17h 27m Memory: 62.79 GiB 
  used: 29.20 GiB (46.5%) Shell: bash inxi: 3.0.38 
`
Computer 2:
`fachgebiet@Tochnog3:~$ inxi -Fz
System:
  Kernel: 5.4.0-137-generic x86_64 bits: 64 Desktop: Cinnamon 5.0.7 
  Distro: Linux Mint 20.2 Uma 
Machine:
  Type: Desktop Mobo: ASUSTeK model: Z10PE-D16 WS v: Rev 1.xx 
  serial: <filter> UEFI [Legacy]: American Megatrends v: 3703 
  date: 04/25/2018 
CPU:
  Topology: 2x 6-Core model: Intel Xeon E5-2620 v3 bits: 64 type: MT MCP SMP 
  L2 cache: 30.0 MiB 
  Speed: 2594 MHz min/max: 1200/3200 MHz Core speeds (MHz): 1: 2594 2: 2594 
  3: 2594 4: 2594 5: 2594 6: 2594 7: 2594 8: 2594 9: 2594 10: 2594 11: 2594 
  12: 2594 13: 2594 14: 2594 15: 2594 16: 2594 17: 2594 18: 2594 19: 2594 
  20: 2594 21: 2594 22: 2594 23: 2594 24: 2594 
Graphics:
  Device-1: NVIDIA GF119 [GeForce GT 610] driver: nouveau v: kernel 
  Display: x11 server: X.Org 1.20.13 driver: modesetting 
  unloaded: fbdev,vesa resolution: 1920x1080~60Hz 
  OpenGL: renderer: NVD9 v: 4.3 Mesa 21.2.6 
Audio:
  Device-1: Intel C610/X99 series HD Audio driver: snd_hda_intel 
  Device-2: NVIDIA GF119 HDMI Audio driver: snd_hda_intel 
  Sound Server: ALSA v: k5.4.0-137-generic 
Network:
  Device-1: Intel I210 Gigabit Network driver: igb 
  IF: enp4s0 state: down mac: <filter> 
  Device-2: Intel I210 Gigabit Network driver: igb 
  IF: enp5s0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
Drives:
  Local Storage: total: 3.31 TiB used: 229.67 GiB (6.8%) 
  ID-1: /dev/sda vendor: Samsung model: SSD 860 PRO 256GB size: 238.47 GiB 
  ID-2: /dev/sdb vendor: Crucial model: CT250BX100SSD1 size: 232.89 GiB 
  ID-3: /dev/sdc vendor: Samsung model: SSD 830 Series size: 119.24 GiB 
  ID-4: /dev/sdd vendor: Seagate model: ST3000NM0033-9ZM178 size: 2.73 TiB 
Partition:
  ID-1: / size: 233.18 GiB used: 32.65 GiB (14.0%) fs: ext4 dev: /dev/sda5 
Sensors:
  System Temperatures: cpu: 58.0 C mobo: N/A gpu: nouveau temp: 34 C 
  Fan Speeds (RPM): N/A 
Info:
  Processes: 414 Uptime: 47d 1h 01m Memory: 62.79 GiB 
  used: 22.61 GiB (36.0%) Shell: bash inxi: 3.0.38 `

### Crash report

`==================================================================
 Info                                                              
===================================================================
           PID: 4355 (cinnamon)
           UID: 1001 (fachgebiet)
           GID: 1001 (fachgebiet)
        Signal: 6 (ABRT)
     Timestamp: Fri 2023-03-10 15:32:24 CET (4 days ago)
  Command Line: cinnamon --replace
    Executable: /usr/bin/cinnamon
 Control Group: /user.slice/user-1001.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1001.slice
       Session: c2
     Owner UID: 1001 (fachgebiet)
       Boot ID: 30d20bf60da94f25a7f91a46dd11d7bf
    Machine ID: dafd9a61376b4676aa8b190bc1ed4b43
      Hostname: Abaqus1
       Storage: /var/lib/systemd/coredump/core.cinnamon.1001.30d20bf60da94f25a7f91a46dd11d7bf.4355.1678458744000000000000.lz4
       Message: Process 4355 (cinnamon) of user 1001 dumped core.
                
                Stack trace of thread 4355:
                #0  0x00007f1d8a44600b __GI_raise (libc.so.6 + 0x4300b)
                #1  0x00007f1d8a425859 __GI_abort (libc.so.6 + 0x22859)
                #2  0x00007f1d48400ea1 n/a (libgtop-2.0.so.11 + 0x7ea1)
                #3  0x00007f1d484010fe n/a (libgtop-2.0.so.11 + 0x80fe)
                #4  0x00007f1d48405abf n/a (libgtop-2.0.so.11 + 0xcabf)
                #5  0x00007f1d4840224f n/a (libgtop-2.0.so.11 + 0x924f)
                #6  0x00007f1d483fee4d glibtop_get_cpu_l (libgtop-2.0.so.11 + 0x5e4d)
                #7  0x00007f1d891ccff5 n/a (libffi.so.7 + 0x6ff5)
                #8  0x00007f1d891cc40a n/a (libffi.so.7 + 0x640a)
                #9  0x00007f1d8a2a6b04 n/a (libcjs.so.0 + 0x40b04)
                #10 0x00007f1d8a2a6fcc n/a (libcjs.so.0 + 0x40fcc)
                #11 0x00007f1d86edb81d n/a (libmozjs-78.so.0 + 0x16081d)
                #12 0x00007f1d86edc543 n/a (libmozjs-78.so.0 + 0x161543)
                #13 0x00007f1d874bcdcf n/a (libmozjs-78.so.0 + 0x741dcf)
                #14 0x000029cdcd3cdc5d n/a (n/a + 0x0)
===================================================================
 GDB Log                                                           
===================================================================
[New LWP 4355]
[New LWP 4619]
[New LWP 4432]
[New LWP 4621]
[New LWP 4509]
[New LWP 4617]
[New LWP 4618]
[New LWP 4443]
[New LWP 4620]
[New LWP 4622]
[New LWP 3817810]
[New LWP 4623]
[New LWP 4624]
Core was generated by `cinnamon --replace'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f1d8a44600b in ?? ()
[Current thread is 1 (LWP 4355)]

===================================================================
 GDB Backtrace                                                     
===================================================================
[New LWP 4355]
[New LWP 4619]
[New LWP 4432]
[New LWP 4621]
[New LWP 4509]
[New LWP 4617]
[New LWP 4618]
[New LWP 4443]
[New LWP 4620]
[New LWP 4622]
[New LWP 3817810]
[New LWP 4623]
[New LWP 4624]
Core was generated by `cinnamon --replace'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f1d8a44600b in ?? ()
[Current thread is 1 (LWP 4355)]
#0  0x00007f1d8a44600b in ?? ()
#1  0x0000000000000000 in ?? ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
[New LWP 4355]
[New LWP 4619]
[New LWP 4432]
[New LWP 4621]
[New LWP 4509]
[New LWP 4617]
[New LWP 4618]
[New LWP 4443]
[New LWP 4620]
[New LWP 4622]
[New LWP 3817810]
[New LWP 4623]
[New LWP 4624]
Core was generated by `cinnamon --replace'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f1d8a44600b in ?? ()
[Current thread is 1 (LWP 4355)]

Thread 13 (LWP 4624):
#0  0x00007f1d89366376 in ?? ()
No symbol table info available.
#1  0x000000000005093a in ?? ()
No symbol table info available.
#2  0x0000008100000004 in ?? ()
No symbol table info available.
#3  0x0000000000000001 in ?? ()
No symbol table info available.
#4  0x000055b6d28b7470 in ?? ()
No symbol table info available.
#5  0x0000000000000004 in ?? ()
No symbol table info available.
#6  0x00000000000a1275 in ?? ()
No symbol table info available.
#7  0x000055b6d28b7474 in ?? ()
No symbol table info available.
#8  0x000055b6d30c5468 in ?? ()
No symbol table info available.
#9  0x00007f1d89366050 in ?? ()
No symbol table info available.
#10 0x00007f1d8072b960 in ?? ()
No symbol table info available.
#11 0x00007f1d87c41fc0 in ?? ()
No symbol table info available.
#12 0x0000000000000000 in ?? ()
No symbol table info available.

Thread 12 (LWP 4623):
#0  0x00007f1d89366376 in ?? ()
No symbol table info available.
#1  0x0000000000050939 in ?? ()
No symbol table info available.
#2  0x0000008100000004 in ?? ()
No symbol table info available.
#3  0x0000000000000001 in ?? ()
No symbol table info available.
#4  0x000055b6d28b7470 in ?? ()
No symbol table info available.
#5  0x0000000000000004 in ?? ()
No symbol table info available.
#6  0x00000000000a1273 in ?? ()
No symbol table info available.
#7  0x000055b6d28b7474 in ?? ()
No symbol table info available.
#8  0xb0c87499004ab900 in ?? ()
No symbol table info available.
#9  0x00007f1d89366050 in ?? ()
No symbol table info available.
#10 0x00007f1d8092a960 in ?? ()
No symbol table info available.
#11 0x000055b6db74bfa0 in ?? ()
No symbol table info available.
#12 0x0000000000000000 in ?? ()
No symbol table info available.

Thread 11 (LWP 3817810):
#0  0x00007f1d8a51b73d in ?? ()
No symbol table info available.
#1  0x00007f1d8aa3a746 in ?? ()
No symbol table info available.
#2  0x00000000000127f3 in ?? ()
No symbol table info available.
#3  0x0000000034d2cc34 in ?? ()
No symbol table info available.
#4  0x000000000000000e in ?? ()
No symbol table info available.
#5  0x000000003b9ac5d4 in ?? ()
No symbol table info available.
#6  0x00007f1d4b7fda70 in ?? ()
No symbol table info available.
#7  0xb0c87499004ab900 in ?? ()
No symbol table info available.
#8  0x0000000000000001 in ?? ()
No symbol table info available.
#9  0x0000000000000001 in ?? ()
No symbol table info available.
#10 0x00000011a4c60a55 in ?? ()
No symbol table info available.
#11 0x000055b6d29097d0 in ?? ()
No symbol table info available.
#12 0x000055b6d29097e8 in ?? ()
No symbol table info available.
#13 0x00007f1d8a9bd581 in ?? ()
No symbol table info available.
#14 0x0000000000003a98 in ?? ()
No symbol table info available.
#15 0x000055b6d29097d0 in ?? ()
No symbol table info available.
#16 0x00000011a4c60a55 in ?? ()
No symbol table info available.
#17 0x0000000000000002 in ?? ()
No symbol table info available.
#18 0x0000000000000000 in ?? ()
No symbol table info available.

Thread 10 (LWP 4622):
#0  0x00007f1d89366376 in ?? ()
No symbol table info available.
#1  0x0000000000050937 in ?? ()
No symbol table info available.
#2  0x000000818a499e8b in ?? ()
No symbol table info available.
#3  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 9 (LWP 4620):
#0  0x00007f1d89366376 in ?? ()
No symbol table info available.
#1  0x0000000000050938 in ?? ()
No symbol table info available.
#2  0x0000008100000004 in ?? ()
No symbol table info available.
#3  0x0000000000000001 in ?? ()
No symbol table info available.
#4  0x000055b6d28b7470 in ?? ()
No symbol table info available.
#5  0x0000000000000004 in ?? ()
No symbol table info available.
#6  0x00000000000a1271 in ?? ()
No symbol table info available.
#7  0x000055b6d28b7474 in ?? ()
No symbol table info available.
#8  0xb0c87499004ab900 in ?? ()
No symbol table info available.
#9  0x00007f1d89366050 in ?? ()
No symbol table info available.
#10 0x00007f1d80f27960 in ?? ()
No symbol table info available.
#11 0x00007f1d5c0d4180 in ?? ()
No symbol table info available.
#12 0x0000000000000000 in ?? ()
No symbol table info available.

Thread 8 (LWP 4443):
#0  0x00007f1d8a51599f in ?? ()
No symbol table info available.
#1  0x000055b6d2919390 in ?? ()
No symbol table info available.
#2  0x000055b6d2919390 in ?? ()
No symbol table info available.
#3  0x0000000000000003 in ?? ()
No symbol table info available.
#4  0xffffffff00000001 in ?? ()
No symbol table info available.
#5  0x000055b6d2917680 in ?? ()
No symbol table info available.
#6  0x00007f1d8a9ed36e in ?? ()
No symbol table info available.
#7  0x0000000000000001 in ?? ()
No symbol table info available.
#8  0x00000001d2917650 in ?? ()
No symbol table info available.
#9  0xffffffff7fffffff in ?? ()
No symbol table info available.
#10 0xb0c87499004ab900 in ?? ()
No symbol table info available.
#11 0x000055b6d2917680 in ?? ()
No symbol table info available.
#12 0x000055b6d2917778 in ?? ()
No symbol table info available.
#13 0x000055b6d2917770 in ?? ()
No symbol table info available.
#14 0x000055b6d291777c in ?? ()
No symbol table info available.
#15 0x00007ffce9c4dddf in ?? ()
No symbol table info available.
#16 0x00007ffce9c4de70 in ?? ()
No symbol table info available.
#17 0x00007f1d832e2bc0 in ?? ()
No symbol table info available.
#18 0x00007f1d8a9ed6f3 in ?? ()
No symbol table info available.
#19 0x000055b6d2902e80 in ?? ()
No symbol table info available.
#20 0x000055b6d2917650 in ?? ()
No symbol table info available.
#21 0x0000000000000000 in ?? ()
No symbol table info available.

Thread 7 (LWP 4618):
#0  0x00007f1d89366376 in ?? ()
No symbol table info available.
#1  0x0000000000050935 in ?? ()
No symbol table info available.
#2  0x0000008100000004 in ?? ()
No symbol table info available.
#3  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 6 (LWP 4617):
#0  0x00007f1d89366376 in ?? ()
No symbol table info available.
#1  0x0000000000050932 in ?? ()
No symbol table info available.
#2  0x0000008100000004 in ?? ()
No symbol table info available.
#3  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 5 (LWP 4509):
#0  0x00007f1d8a51599f in ?? ()
No symbol table info available.
#1  0x000055b6d2a16b60 in ?? ()
No symbol table info available.
#2  0x000055b6d2a16b60 in ?? ()
No symbol table info available.
#3  0x0000000000000001 in ?? ()
No symbol table info available.
#4  0xffffffff00000001 in ?? ()
No symbol table info available.
#5  0x000055b6d2994550 in ?? ()
No symbol table info available.
#6  0x00007f1d8a9ed36e in ?? ()
No symbol table info available.
#7  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 4 (LWP 4621):
#0  0x00007f1d89366376 in ?? ()
No symbol table info available.
#1  0x0000000000050934 in ?? ()
No symbol table info available.
#2  0x000000818a499e8b in ?? ()
No symbol table info available.
#3  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 3 (LWP 4432):
#0  0x00007f1d8a51599f in ?? ()
No symbol table info available.
#1  0x000055b6d2907960 in ?? ()
No symbol table info available.
#2  0x000055b6d2907960 in ?? ()
No symbol table info available.
#3  0x0000000000000002 in ?? ()
No symbol table info available.
#4  0x00000f9f00000001 in ?? ()
No symbol table info available.
#5  0x000055b6d2909d80 in ?? ()
No symbol table info available.
#6  0x00007f1d8a9ed36e in ?? ()
No symbol table info available.
#7  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 2 (LWP 4619):
#0  0x00007f1d89366376 in ?? ()
No symbol table info available.
#1  0x0000000000050936 in ?? ()
No symbol table info available.
#2  0x0000008100000004 in ?? ()
No symbol table info available.
#3  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 1 (LWP 4355):
#0  0x00007f1d8a44600b in ?? ()
No symbol table info available.
#1  0x0000000000000000 in ?? ()
No symbol table info available.
#0  0x00007f1d8a44600b in ?? ()
#1  0x0000000000000000 in ?? ()
`

Thank you for any idea regarding this problem.
Regards Josch

**Comment by rcalixte** [comment]
@joschi2k Can you include the dependencies and their versions for the systems you're compiling this software on?

**Comment by joschi2k** [comment]
@rcalixte Hey rcalixte,I have compiled the software on computer 1, see above. Or what do you mean exactly?

**Comment by rcalixte** [comment]
@joschi2k Normally when you compile software, there are local dependencies. Across different systems and distributions, those software versions can differ. Do you have a list of the dependencies and what versions are on each system that you're compiling? If someone else were to try to compile this software to replicate your issue, what would they need?

**Comment by mtwebster** [comment]
If you have any third-party applets on your panel that are of the system-monitor variety (showing cpu, memory use, etc...), disable them and restart Cinnamon (Alt-f2, r, enter).
