### ISSUE TITLE
"Account Details" don't open if /usr/share/cinnamon/faces contain symlinks

### ISSUE THREAD

**Issue by danimesq** [linuxmint/cinnamon#11644]

**Comment by clefebvre** [comment]
Hi @danimesq

I can't reproduce the issue, the tool opens up fine for me:

![image](https://github.com/linuxmint/cinnamon/assets/1138515/46c86beb-e6f7-4344-9b1e-c7123dc2bf46)

Can you show me the list of files with permissions in your `/usr/share/cinnamon/faces`?

Also, what error do you get in the output, when you run the tool from the command line with `cinnamon-settings user`?

**Comment by danimesq** [comment]
`cinnamon-settings user`'s output:

> Using pam module (python3-pampy)
> /usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:442: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
>   self.window.set_wmclass(wm_class, wm_class)
> Loading User module
> Could not load thumbnail file '/usr/share/cinnamon/faces/cinnamon': Couldn’t recognize the image file format for file “/usr/share/cinnamon/faces/cinnamon”
> Traceback (most recent call last):
>   File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 793, in <module>
>     window = MainWindow()
>              ^^^^^^^^^^^^
>   File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 314, in __init__
>     if self.load_sidepage_as_standalone():
> n load_sidepage_as_standalone
>     self.go_to_sidepage(sp_data.sp, user_action=False)
>   File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 174, in go_to_sidepage
>     sidePage.build()
>   File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 212, in build
>     self.module.on_module_selected()
>   File "/usr/share/cinnamon/cinnamon-settings/modules/cs_user.py", line 72, in on_module_selected
>     self.face_button.add_picture(path, self._on_face_menuitem_activated)
>   File "/usr/share/cinnamon/cinnamon-settings/bin/ChooserButtonWidgets.py", line 160, in add_picture
>     surface = self.create_scaled_surface(path)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/share/cinnamon/cinnamon-settings/bin/ChooserButtonWidgets.py", line 125, in create_scaled_surface
>     if pixbuf:
>        ^^^^^^
> UnboundLocalError: cannot access local variable 'pixbuf' where it is not associated with a value

Remember some avatars the script is trying to open, are symlinks!

**Comment by SparkyBluefang** [comment]
Reading the stack trace, it has nothing to do specifically with symlinks.The error is caused by trying to load a non-image into a pixbuf. If the symlink points at a valid image file, it works perfectly fine. I can reproduce that error simply by creating an empty file in that directory.
> touch /usr/share/cinnamon/faces/foobar

What distribution and cinnamon packages/version are you using? The reported file is not something that appears to be a part of the cinnamon sources:
https://github.com/linuxmint/cinnamon/tree/f84c97dabbc4179a02ec04399d424d19cd482344/files/usr/share/cinnamon/faces
