### ISSUE TITLE
If flatpak is purged form the system software manager won't start

### ISSUE THREAD

**Issue by tnm-** [linuxmint/Cinnamon#11671]
### Distribution

Mint 21.1

### Package version

5.6.8

### Graphics hardware in use

Doesn't matter

### Frequency

Always

### Bug description

Software manager depends on some folders/files tied to flatpak. I think this may be related/continuation to this "abandoned" bugreport:
https://github.com/linuxmint/mint21-beta/issues/164

### Steps to reproduce

$ sudo apt remove --autoremove flatpak
$ sudo apt purge flatpak
$ mintinstall
MintInstall: Detected system architecture: 'x86_64'
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 958, in do_activate
    if self.installer.init_sync():
  File "/usr/lib/python3/dist-packages/mintcommon/installer/installer.py", line 246, in init_sync
    if self._fp_remotes_have_changed():
  File "/usr/lib/python3/dist-packages/mintcommon/installer/installer.py", line 326, in _fp_remotes_have_changed
    fp_remotes = self.list_flatpak_remotes()
  File "/usr/lib/python3/dist-packages/mintcommon/installer/installer.py", line 492, in list_flatpak_remotes
    return _flatpak.list_remotes()
  File "/usr/lib/python3/dist-packages/mintcommon/installer/_flatpak.py", line 897, in list_remotes
    fp_sys = get_fp_sys()
  File "/usr/lib/python3/dist-packages/mintcommon/installer/_flatpak.py", line 72, in get_fp_sys
    _fp_sys = Flatpak.Installation.new_system(None)
gi.repository.GLib.GError: g-io-error-quark: While opening repository /var/lib/flatpak/repo: opening repo: opendir(/var/lib/flatpak/repo): No such file or directory (1)

### Expected behavior

Software manager/mintinstall starts even if flatpak has been purged

### Additional information

If I manually create the folder mintinstall still doesn't start.

$ sudo mkdir -p /var/lib/flatpak/repo
$ mintinstall
MintInstall: Detected system architecture: 'x86_64'
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 958, in do_activate
    if self.installer.init_sync():
  File "/usr/lib/python3/dist-packages/mintcommon/installer/installer.py", line 246, in init_sync
    if self._fp_remotes_have_changed():
  File "/usr/lib/python3/dist-packages/mintcommon/installer/installer.py", line 326, in _fp_remotes_have_changed
    fp_remotes = self.list_flatpak_remotes()
  File "/usr/lib/python3/dist-packages/mintcommon/installer/installer.py", line 492, in list_flatpak_remotes
    return _flatpak.list_remotes()
  File "/usr/lib/python3/dist-packages/mintcommon/installer/_flatpak.py", line 897, in list_remotes
    fp_sys = get_fp_sys()
  File "/usr/lib/python3/dist-packages/mintcommon/installer/_flatpak.py", line 72, in get_fp_sys
    _fp_sys = Flatpak.Installation.new_system(None)
gi.repository.GLib.GError: g-io-error-quark: While opening repository /var/lib/flatpak/repo: opening repo: opendir(objects): No such file or directory (1)

Reinstalling flatpak, then removing (but not purging!) solves the issue:

**Comment by mtwebster** [comment]
Remove gir1.2-flatpak-1.0 as well as flatpak.

**Comment by tnm-** [comment]
Thanks, that did solve it.
But I still think this should be handled a bit more graceful. Either with a clearer error message or by mintinstall checking for the presence of flatpak before trying to load it.
First search results on "how to remove flatpak" instruct the user the purge flatpak as well (not just remove), but do not instruct to remove gir1.2-flatpak-1.0 at the same time, so it is an unexpected sideeffect that software manager breaks.

Also now mintinstall warns about flatpak and gir1.2 missing:
"mint-common (WARN): No flatpak support, install flatpak and gir1.2-flatpak-1.0 and restart mintinstall to enable it."
Why would the desire to not use flatpak warrant a warning? :)
