### ISSUE TITLE
Linuxmint Update 21.2 Settings->Themes not available

### ISSUE THREAD

**Issue by lbm-services** [linuxmint/cinnamon#11821]
### Distribution

Linuxmint 21.2

### Package version

5.8.4

### Graphics hardware in use

Intel WhiskeyLake-U GT2 [UHD Graphics 620]

### Frequency

Always

### Bug description

Cannot open themes settings, neither via GUI nor cli.
cinnamon-settings output:

(cinnamon-settings.py:3036): Gtk-WARNING **: 22:32:36.815: Theme parsing error: gtk.css:12:0: Expected a valid selector

(cinnamon-settings.py:3036): Gtk-WARNING **: 22:32:36.815: Theme parsing error: gtk.css:14:0: Expected a valid selector
Using PAM module (python3-pam)
Loading Themes module
/home/hli/.local/share/themes does not exist! Skipping
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 733, in button_press
    self.side_view_nav(widget, None, category)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 165, in side_view_nav
    self.go_to_sidepage(sidePage, user_action=True)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 174, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 212, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py", line 297, in on_module_selected
    widget.sync_initial_switch_state()
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 329, in sync_initial_switch_state
    if editor.get_declaration(self.selector, decl_name):
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 190, in get_declaration
    rs, _ = self.get_ruleset(selector)
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 180, in get_ruleset
    if self._serialize_selector(rs) == selector_css:
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 155, in _serialize_selector
    at_css += self._serialize_prelude(rule.prelude)
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 168, in _serialize_prelude
    at_css += cv.value
AttributeError: 'ParseError' object has no attribute 'value'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/var/crash/_usr_share_cinnamon_cinnamon-settings_cinnamon-settings.py.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 733, in button_press
    self.side_view_nav(widget, None, category)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 165, in side_view_nav
    self.go_to_sidepage(sidePage, user_action=True)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 174, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 212, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py", line 297, in on_module_selected
    widget.sync_initial_switch_state()
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 329, in sync_initial_switch_state
    if editor.get_declaration(self.selector, decl_name):
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 190, in get_declaration
    rs, _ = self.get_ruleset(selector)
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 180, in get_ruleset
    if self._serialize_selector(rs) == selector_css:
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 155, in _serialize_selector
    at_css += self._serialize_prelude(rule.prelude)
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 168, in _serialize_prelude
    at_css += cv.value
AttributeError: 'ParseError' object has no attribute 'value'
Loading Themes module
/home/hli/.local/share/themes does not exist! Skipping
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 165, in side_view_nav
    self.go_to_sidepage(sidePage, user_action=True)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 174, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 212, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py", line 297, in on_module_selected
    widget.sync_initial_switch_state()
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 329, in sync_initial_switch_state
    if editor.get_declaration(self.selector, decl_name):
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 190, in get_declaration
    rs, _ = self.get_ruleset(selector)
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 180, in get_ruleset
    if self._serialize_selector(rs) == selector_css:
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 155, in _serialize_selector
    at_css += self._serialize_prelude(rule.prelude)
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 168, in _serialize_prelude
    at_css += cv.value
AttributeError: 'ParseError' object has no attribute 'value'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/var/crash/_usr_share_cinnamon_cinnamon-settings_cinnamon-settings.py.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 165, in side_view_nav
    self.go_to_sidepage(sidePage, user_action=True)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 174, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 212, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py", line 297, in on_module_selected
    widget.sync_initial_switch_state()
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 329, in sync_initial_switch_state
    if editor.get_declaration(self.selector, decl_name):
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 190, in get_declaration
    rs, _ = self.get_ruleset(selector)
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 180, in get_ruleset
    if self._serialize_selector(rs) == selector_css:
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 155, in _serialize_selector
    at_css += self._serialize_prelude(rule.prelude)
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 168, in _serialize_prelude
    at_css += cv.value
AttributeError: 'ParseError' object has no attribute 'value'
Loading Themes module
/home/hli/.local/share/themes does not exist! Skipping
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 733, in button_press
    self.side_view_nav(widget, None, category)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 165, in side_view_nav
    self.go_to_sidepage(sidePage, user_action=True)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 174, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 212, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py", line 297, in on_module_selected
    widget.sync_initial_switch_state()
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 329, in sync_initial_switch_state
    if editor.get_declaration(self.selector, decl_name):
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 190, in get_declaration
    rs, _ = self.get_ruleset(selector)
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 180, in get_ruleset
    if self._serialize_selector(rs) == selector_css:
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 155, in _serialize_selector
    at_css += self._serialize_prelude(rule.prelude)
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 168, in _serialize_prelude
    at_css += cv.value
AttributeError: 'ParseError' object has no attribute 'value'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/var/crash/_usr_share_cinnamon_cinnamon-settings_cinnamon-settings.py.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 733, in button_press
    self.side_view_nav(widget, None, category)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 165, in side_view_nav
    self.go_to_sidepage(sidePage, user_action=True)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 174, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 212, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py", line 297, in on_module_selected
    widget.sync_initial_switch_state()
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 329, in sync_initial_switch_state
    if editor.get_declaration(self.selector, decl_name):
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 190, in get_declaration
    rs, _ = self.get_ruleset(selector)
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 180, in get_ruleset
    if self._serialize_selector(rs) == selector_css:
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 155, in _serialize_selector
    at_css += self._serialize_prelude(rule.prelude)
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 168, in _serialize_prelude
    at_css += cv.value
AttributeError: 'ParseError' object has no attribute 'value'
Loading Fonts module

### Steps to reproduce

open settings and click on "themes"

### Expected behavior

Themes available

**Comment by claudiux** [comment]
Can't reproduce this issue.

**Comment by claudiux** [comment]
Please try to create manually the `/home/hli/.local/share/themes` folder with this command:

`mkdir -p /home/hli/.local/share/themes`

**Comment by lbm-services** [comment]
.themes is empty anyway. I created ~/.local/share/themes
the error message looks like this now:

(cinnamon-settings.py:3530): Gtk-WARNING **: 00:08:16.242: Theme parsing error: gtk.css:12:0: Expected a valid selector

(cinnamon-settings.py:3530): Gtk-WARNING **: 00:08:16.242: Theme parsing error: gtk.css:14:0: Expected a valid selector
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:442: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.window.set_wmclass(wm_class, wm_class)
Loading Themes module
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 793, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 314, in __init__
    if self.load_sidepage_as_standalone():
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 448, in load_sidepage_as_standalone
    self.go_to_sidepage(sp_data.sp, user_action=False)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 174, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 212, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py", line 297, in on_module_selected
    widget.sync_initial_switch_state()
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 329, in sync_initial_switch_state
    if editor.get_declaration(self.selector, decl_name):
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 190, in get_declaration
    rs, _ = self.get_ruleset(selector)
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 180, in get_ruleset
    if self._serialize_selector(rs) == selector_css:
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 155, in _serialize_selector
    at_css += self._serialize_prelude(rule.prelude)
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 168, in _serialize_prelude
    at_css += cv.value
AttributeError: 'ParseError' object has no attribute 'value'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/var/crash/_usr_share_cinnamon_cinnamon-settings_cinnamon-settings.py.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 793, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 314, in __init__
    if self.load_sidepage_as_standalone():
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 448, in load_sidepage_as_standalone
    self.go_to_sidepage(sp_data.sp, user_action=False)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 174, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 212, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py", line 297, in on_module_selected
    widget.sync_initial_switch_state()
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 329, in sync_initial_switch_state
    if editor.get_declaration(self.selector, decl_name):
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 190, in get_declaration
    rs, _ = self.get_ruleset(selector)
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 180, in get_ruleset
    if self._serialize_selector(rs) == selector_css:
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 155, in _serialize_selector
    at_css += self._serialize_prelude(rule.prelude)
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 168, in _serialize_prelude
    at_css += cv.value
AttributeError: 'ParseError' object has no attribute 'value'

**Comment by lbm-services** [comment]
now I created /var/crash/ and made it writeable, now the message is this:

(cinnamon-settings.py:9076): Gtk-WARNING **: 00:17:35.359: Theme parsing error: gtk.css:12:0: Expected a valid selector

(cinnamon-settings.py:9076): Gtk-WARNING **: 00:17:35.359: Theme parsing error: gtk.css:14:0: Expected a valid selector
Using PAM module (python3-pam)
Loading Themes module
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 733, in button_press
    self.side_view_nav(widget, None, category)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 165, in side_view_nav
    self.go_to_sidepage(sidePage, user_action=True)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 174, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 212, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py", line 297, in on_module_selected
    widget.sync_initial_switch_state()
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 329, in sync_initial_switch_state
    if editor.get_declaration(self.selector, decl_name):
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 190, in get_declaration
    rs, _ = self.get_ruleset(selector)
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 180, in get_ruleset
    if self._serialize_selector(rs) == selector_css:
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 155, in _serialize_selector
    at_css += self._serialize_prelude(rule.prelude)
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 168, in _serialize_prelude
    at_css += cv.value
AttributeError: 'ParseError' object has no attribute 'value'

**Comment by lbm-services** [comment]
[_usr_share_cinnamon_cinnamon-settings_cinnamon-settings.py.1000.crash.gz](https://github.com/linuxmint/cinnamon/files/12353500/_usr_share_cinnamon_cinnamon-settings_cinnamon-settings.py.1000.crash.gz)

**Comment by fredcw** [comment]
Maybe one of your theme files is corrupted. What gtk and cinnamon themes are you using?

What happens if you reset your themes to default values?

`dconf reset /org/cinnamon/desktop/interface/gtk-theme`

`dconf reset /org/cinnamon/theme/name`

**Comment by lbm-services** [comment]
no change after execution of your suggestions. Themes is still unavailable.
I used a standard theme before the upgrade, and noticed no corruption whatsoever.
This problem is connected to the upgrade. It is quite annoying because I hate the new mouse pointer and cannot change it.

**Comment by fredcw** [comment]
I don't know what the problem is but you can change your cursor theme with:

`gsettings set org.cinnamon.desktop.interface cursor-theme "'Adwaita'"`

(The single and double quotation marks are needed) Other options are breeze_cursors, DMZ-Black, Yaru

I think it's safer to use gsettings command rather than dconf. To change your icon theme:

`gsettings set org.cinnamon.desktop.interface icon-theme "'Mint-Y'"`

**Comment by lbm-services** [comment]
> I don't know what the problem is but you can change your cursor theme with:
> 
> `gsettings set org.cinnamon.desktop.interface cursor-theme "'Adwaita'"`
> 
> (The single and double quotation marks are needed) Other options are breeze_cursors, DMZ-Black, Yaru
> 
> I think it's safer to use gsettings command rather than dconf. To change your icon theme:
> 
> `gsettings set org.cinnamon.desktop.interface icon-theme "'Mint-Y'"`

This was helpful. I could change theme and mouse pointer. But Themes settings tab is still unavailable.

**Comment by leigh123linux** [comment]
Maybe ~/.config/gtk-3.0/gtk.css has been corrupted.

**Comment by lbm-services** [comment]
> Maybe ~/.config/gtk-3.0/gtk.css has been corrupted

Yes. Solution:

`cp /usr/share/themes/Mint-X-Aqua/gtk-3.0/gtk.css .config/gtk-3.0/`

**Comment by fredcw** [comment]
The css styles in `.config/gtk-3.0/gtk.css` are applied after the css from your currently selected theme. By copying the file above, you will not now be able to change the gtk theme in theme settings. The best thing to do is to just delete `~/.config/gtk-3.0/gtk.css` as it's only needed if you want to override something in the currently selected gtk theme.

**Comment by clefebvre** [comment]
I wouldn't mind seeing the content of it before you delete it.
