### ISSUE TITLE
Report on testing of blur experimental feature on themes

### ISSUE THREAD

**Issue by anaximeno** [linuxmint/cinnamon#11822]
### Distribution

Mint 21.2

### Package version

Cinnamon 5.8.4

### Frequency

Always

### Bug description

I've been testing the experimental blur effect a bit and it worked well for most of the places I applied it:

![Screenshot from 2023-08-10 23-00-19](https://github.com/linuxmint/cinnamon/assets/63073056/a868f0c1-c091-40e5-8154-117d8aaaf15c)

The only place I had a problem was when trying to apply the blur effect with the component with the **#overview** id:

![Screenshot from 2023-08-10 23-00-48](https://github.com/linuxmint/cinnamon/assets/63073056/9abc8548-c9c6-49cb-ac2c-79112e483482)

### Steps to reproduce

Add a background blur effect to **#overview** in cinnamon.css, reload Cinnamon, and try to open the scale view, Cinnamon will probably crash.

### Expected behavior

Maybe should not break the system in that case, unless it is something actually expected in that case.

### Additional information

Crash Trace ==> https://termbin.com/vj4j

**Comment by fredcw** [comment]
I've also found that cinnamon crashes if the blur effect is used in other circumstances:

When blur is applied to the panel and the panel is on the left or right side of the screen but not on top or bottom.

When blur is applied to the menu applet background (and Cinnamenu applet, but I haven't tested other applets) and the menu applet is opened and touches the left or right hand side of the screen when opened from a bottom panel or touches the bottom edge of the screen when opened from a side panel.

<details>

<summary>.xsession-errors:</summary>

```
munmap_chunk(): invalid pointer
Exception in thread Thread-1 (wait_for_process):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/bin/cinnamon-launcher", line 88, in wait_for_process
    os.execvp(FALLBACK_COMMAND, (FALLBACK_COMMAND,) + FALLBACK_ARGS)
  File "<frozen os>", line 574, in execvp
  File "<frozen os>", line 616, in _execvpe
  File "<frozen os>", line 607, in _execvpe
FileNotFoundError: [Errno 2] No such file or directory

(nm-applet:886): Gdk-CRITICAL **: 05:16:46.470: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

(xapp-sn-watcher:864): GLib-GObject-CRITICAL **: 05:17:13.452: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(xapp-sn-watcher:864): GLib-GIO-CRITICAL **: 05:17:13.452: g_dbus_interface_skeleton_flush: assertion 'G_IS_DBUS_INTERFACE_SKELETON (interface_)' failed

(xapp-sn-watcher:864): GLib-GObject-CRITICAL **: 05:17:13.452: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(xapp-sn-watcher:864): GLib-GIO-CRITICAL **: 05:17:13.452: g_dbus_interface_skeleton_flush: assertion 'G_IS_DBUS_INTERFACE_SKELETON (interface_)' failed

(xapp-sn-watcher:864): GLib-GObject-CRITICAL **: 05:17:13.452: invalid (NULL) pointer instance

(xapp-sn-watcher:864): GLib-GObject-CRITICAL **: 05:17:13.452: g_signal_emit_by_name: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
cinnamon-session[598]: WARNING: t+32.86363s: Detected that screensaver has left the bus
mutter-Message: 05:17:26.003: Enabling experimental feature 'x11-randr-fractional-scaling'

(cinnamon:1241): mutter-WARNING **: 05:17:26.133: Property 'libinput Accel Profile Enabled Default' for device 'PixArt USB Optical Mouse' returned 3 items, expected 2

(cinnamon:1241): mutter-WARNING **: 05:17:26.133: Property 'libinput Accel Profiles Available' for device 'PixArt USB Optical Mouse' returned 3 items, expected 2

(cinnamon:1241): mutter-WARNING **: 05:17:26.145: Property 'libinput Accel Profile Enabled Default' for device 'PixArt USB Optical Mouse' returned 3 items, expected 2

(cinnamon:1241): mutter-WARNING **: 05:17:26.146: Property 'libinput Accel Profiles Available' for device 'PixArt USB Optical Mouse' returned 3 items, expected 2

```
</details>

**Comment by anaximeno** [comment]
I also noticed the visual artifacts you said in the other issue, and also some times when you over certain applets in the panel (having  transparence and blur applied applied) some blemishes are left in the painting of that section. I haven't tested the bumpmaps yet to see how they are working.

**Comment by JosephMcc** [comment]
I tried the blur effect out awhile ago after it was merged. My conclusion was that in it's current state it was basically unusable. While I haven't tried to reproduce the issues shown here, just the amount of visual artifacts it causes when actually trying to use made me give  up on it.

**Comment by c3401789** [comment]
Same issue but only when applied to the menu popup, I know it's not a proper fix but was able to stop the crashes by disabling Effects on menus. 

Hardware: Dell XPS 9520
Operating System: Fedora Linux 41 (Sway)
Cinnamon Version: 6.2.9
Kernel: 6.12.4-200
Proc: 12th Gen Intel Core i7-12700H
Ram: 15.3 GiB
Graphics: Iris Xe Graphics - Alder Lake-P GT2
Graphics: Nvidia GA107m [GeForce RTX 3050 Ti Mobile]
Display: Wayland

**Comment by Akopov4** [comment]
issue is still reproducible:
Kernel: 6.8.0-100-generic arch: x86_64 bits: 64 compiler: gcc v: 13.3.0 clocksource: tsc
Desktop: Cinnamon v: 6.6.6 tk: GTK v: 3.24.41 wm: Muffin v: 6.6.3 vt: 7 dm: LightDM v: 1.30.0
Distro: Linux Mint 22.3 Zena base: Ubuntu 24.04 noble`
CPU: 13th Gen Intel© Core™ i7-1355U × 10
Grapics: Intel Corporation Raptor Lake-P [UHD Graphics]
Display server:   X11
