### ISSUE TITLE
Cinamon Panel Settings does not open: ValueError: invalid literal for int() with base 10:

### ISSUE THREAD

**Issue by michimussato** [linuxmint/cinnamon#11850]
### Distribution

Manjaro 23.0.0

### Package version

Cinnamon 5.8.4

### Graphics hardware in use

Intel TigerLake-LP GT2 [Iris Xe Graphics]

### Frequency

Always

### Bug description

Cinnamon settings panel does not appear neither from GUI nor from command line.

Behavior from GUI:
nothing happens

Behavior from command line:
```lang=python
$ cinnamon-settings panel
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:445: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.window.set_wmclass(wm_class, wm_class)
Loading Panel module
<class 'str'>
28.00
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 796, in <module>
    window = MainWindow()
             ^^^^^^^^^^^^
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 317, in __init__
    if self.load_sidepage_as_standalone():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 451, in load_sidepage_as_standalone
    self.go_to_sidepage(sp_data.sp, user_action=False)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 177, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 212, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 221, in on_module_selected
    self.on_panel_list_changed()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 300, in on_panel_list_changed
    panel_page = PanelSettingsPage(panel_id, self.settings, position)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 63, in __init__
    widget = PanelRange(dimension_text, "org.cinnamon", "panels-height", self.panel_id, _("Smaller"), _("Larger"), mini=20, maxi=60, show_value=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 566, in __init__
    self.connect_to_settings(schema, key)
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 386, in connect_to_settings
    self.on_setting_changed()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 582, in on_setting_changed
    value = self.get_value()
            ^^^^^^^^^^^^^^^^
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 409, in get_value
    return self.unstringify(value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 579, in unstringify
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '28.00'
```

### Steps to reproduce

Execute `cinnamon-settings panel`

### Expected behavior

Cinnamon panel settings window should appear.

### Additional information

Possible fix:

change https://github.com/linuxmint/cinnamon/blob/b6744f144753a162d82ad60afebd573d0a96b572/files/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py#L577

to

`return int(float(value))`

**Comment by michimussato** [comment]
You are right indeed. However, I don't remember setting that value with a float instead of int;
`/usr/bin/gsettings set org.cinnamon panels-height "['1:28', '2:28']"`
