### ISSUE TITLE
Cinnamon randomly crashes after changing active app in taskbar

### ISSUE THREAD

**Issue by anonymix007** [linuxmint/cinnamon#11897]
### Distribution

Arch

### Package version

5.8.4

### Graphics hardware in use

7950x/6900hs iGPU

### Frequency

Quite often

### Bug description

Switching to another app in taskbar sometimes causes Cinnamon to crash

### Steps to reproduce

1. Open Geany (any other app will probably work as well)
2. Open Chromium
3. Repeat a few times quickly

### Expected behavior

Cinnamon shouldn't crash

### Additional information

[.xsession-errors](https://github.com/linuxmint/cinnamon/files/13060450/xsession-errors.zip)
[Stack traces](https://github.com/linuxmint/cinnamon/files/13060451/cin-debug.zip)

**Comment by anonymix007** [comment]
I think it happens more frequently if I press icons near the border. Another stack trace from 6900hs laptop:
```
Thread 1 (Thread 0x7f736ada1fc0 (LWP 54208) "cinnamon"):
#0  0x00007f737171483c in  () at /usr/lib/libc.so.6
#1  0x00007f73716c4668 in raise () at /usr/lib/libc.so.6
#2  0x00007f73716ac4b8 in abort () at /usr/lib/libc.so.6
#3  0x00007f7371c450ee in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007f7371ca6180 in g_assertion_message_expr () at /usr/lib/libglib-2.0.so.0
#5  0x00007f7371c811cf in  () at /usr/lib/libglib-2.0.so.0
#6  0x00007f7371cdf2b7 in  () at /usr/lib/libglib-2.0.so.0
#7  0x00007f7371c81b47 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#8  0x00007f73718fe579 in meta_run () at /usr/lib/libmuffin.so.0
#9  0x000055b67339c566 in  ()
#10 0x00007f73716adcd0 in  () at /usr/lib/libc.so.6
#11 0x00007f73716add8a in __libc_start_main () at /usr/lib/libc.so.6
#12 0x000055b67339c6b5 in  ()
```
[xsession-errors.zip](https://github.com/linuxmint/cinnamon/files/13061360/xsession-errors.zip)

There are quite a bit more of these `g_closure_unref: assertion 'closure->ref_count > 0' failed`:
```

** (csd-power:12893): WARNING **: 20:10:55.192: in an undefined state we are not charging or discharging and the batteries are also not charged

** (csd-power:12893): WARNING **: 20:10:55.192: in an undefined state we are not charging or discharging and the batteries are also not charged

(cinnamon:105123): GLib-GObject-CRITICAL **: 20:12:12.210: g_closure_unref: assertion 'closure->ref_count > 0' failed
Window manager warning: Ping serial 97766742 was reused for window 0x60001ac, previous use was for window 0x6000020.

(cinnamon:105123): GLib-GObject-CRITICAL **: 20:12:13.205: g_closure_unref: assertion 'closure->ref_count > 0' failed
Window manager warning: Ping serial 97766956 was reused for window 0x60001ac, previous use was for window 0x6000020.
**
GLib:ERROR:../glib/glib/gmain.c:3505:g_main_dispatch: assertion failed: (source->context == context)
Exception in thread Thread-2 (wait_for_process):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/bin/cinnamon-launcher", line 88, in wait_for_process
    os.execvp(FALLBACK_COMMAND, (FALLBACK_COMMAND,) + FALLBACK_ARGS)
  File "<frozen os>", line 574, in execvp
  File "<frozen os>", line 616, in _execvpe
  File "<frozen os>", line 607, in _execvpe
FileNotFoundError: [Errno 2] No such file or directory
None: no process found
```

**Comment by anonymix007** [comment]
I guess things are generally more stable now

**Comment by JosephMcc** [comment]
Closing this. There really isn't enough here for us to work with. If you can find reproducable steps and provide a proper backtrace from a recent version of Cinnamon, please open a new issue.
