### ISSUE TITLE
apt update in Mint 19.3 reports an error

### ISSUE THREAD

**Issue by PSLLSP** [linuxmint/cinnamon#12055]
### Distribution

Mint 19.3 amd64

### Package version

apt

### Graphics hardware in use

NA

### Frequency

Always

### Bug description

This is a new bug, it was not there...

```
root@mint:~# cat /etc/issue
Linux Mint 19.3 Tricia \n \l
```
```
root@mint:~# apt update
Hit:1 http://archive.canonical.com/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease                                        
Hit:3 http://security.ubuntu.com/ubuntu bionic-security InRelease                              
Hit:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease                                
Hit:5 http://archive.ubuntu.com/ubuntu bionic-backports InRelease        
Ign:6 http://packages.linuxmint.com tricia InRelease                     
Hit:7 http://packages.linuxmint.com tricia Release 
Traceback (most recent call last):                
  File "/usr/lib/cnf-update-db", line 8, in <module>
    from CommandNotFound.db.creator import DbCreator
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/creator.py", line 11, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'
Reading package lists... Done
E: Problem executing scripts APT::Update::Post-Invoke-Success 'if /usr/bin/test -w /var/lib/command-not-found/ -a -e /usr/lib/cnf-update-db; then /usr/lib/cnf-update-db > /dev/null; fi'
E: Sub-process returned an error code
```

I know I should update to newer version of Linux Mint... ;-) This is a headless server, reliable one...

### Steps to reproduce

apt update

### Expected behavior

No error...

**Comment by leigh123linux** [comment]
https://github.com/linuxmint/linuxmint/issues

**Comment by PSLLSP** [comment]
New [issue](https://github.com/linuxmint/linuxmint/issues/643) created in different repository...
