### ISSUE TITLE
Calendar applet causes Cinnamon to crash

### ISSUE THREAD

**Issue by anttitleppanen** [linuxmint/Cinnamon#12241]
### Distribution

Debian 12

### Package version

5.6.8

### Frequency

Always

### Bug description

Cinnamon calendar applet causes Cinnamon to go to fallback mode.

### Steps to reproduce

By enabling the calendar applet from Applet settings.

### Expected behavior

Cinnamon does not crash and the calendar app works.

### Additional information

Suddenly Cinnamon crashed on startup on 6 June 2024. After experimenting I found that disabling the calendar app solves the issue.
.xsession-errors (after enabling the calendar)
```


(cinnamon:1681): St-CRITICAL **: 18:40:14.041: cr_parser_new_from_buf: assertion 'a_buf && a_len' failed

(cinnamon:1681): St-CRITICAL **: 18:40:14.042: cr_declaration_parse_list_from_buf: assertion 'parser' failed
Gjs-Message: 18:40:30.780: JS LOG: [LookingGlass/info] Reloading applet: systray@cinnamon.org/3
Gjs-Message: 18:40:30.788: JS LOG: [LookingGlass/info] Reloading applet: xapp-status@cinnamon.org/4
Gjs-Message: 18:40:30.801: JS LOG: [LookingGlass/info] Reloading applet: notifications@cinnamon.org/5
Gjs-Message: 18:40:30.806: JS LOG: [LookingGlass/info] Reloading applet: printers@cinnamon.org/6
Gjs-Message: 18:40:30.809: JS LOG: [LookingGlass/info] Reloading applet: removable-drives@cinnamon.org/7
Gjs-Message: 18:40:30.810: JS LOG: [LookingGlass/info] Reloading applet: keyboard@cinnamon.org/8
Gjs-Message: 18:40:30.813: JS LOG: [LookingGlass/info] Reloading applet: favorites@cinnamon.org/9
Gjs-Message: 18:40:30.814: JS LOG: [LookingGlass/info] Reloading applet: network@cinnamon.org/10
Gjs-Message: 18:40:30.817: JS LOG: [LookingGlass/info] Reloading applet: sound@cinnamon.org/11
Gjs-Message: 18:40:30.834: JS LOG: [LookingGlass/info] Reloading applet: power@cinnamon.org/12
Gjs-Message: 18:40:30.838: JS LOG: [LookingGlass/info] Reloading applet: user@cinnamon.org/14
Gjs-Message: 18:40:30.841: JS LOG: [LookingGlass/info] Reloading applet: batterymonitor@pdcurtis/20
Gjs-Message: 18:40:30.845: JS LOG: [LookingGlass/info] Reloading applet: temperature@fevimu/21

(cinnamon:1681): St-CRITICAL **: 18:40:30.847: cr_parser_new_from_buf: assertion 'a_buf && a_len' failed

(cinnamon:1681): St-CRITICAL **: 18:40:30.847: cr_declaration_parse_list_from_buf: assertion 'parser' failed
Gjs-Message: 18:40:30.848: JS LOG: [LookingGlass/info] Reloading applet: sysmonitor@orcus/22
Gjs-Message: 18:40:30.866: JS LOG: [LookingGlass/info] Adding systray: network (16x16px)
Gjs-Message: 18:40:30.869: JS LOG: [LookingGlass/info] Adding systray: parcellite (24x24px)
Gjs-Message: 18:40:30.870: JS LOG: [LookingGlass/info] Adding systray: input-method (24x24px)
Gjs-Message: 18:40:31.038: JS LOG: [LookingGlass/info] Adding systray: network (16x16px)
Gjs-Message: 18:40:31.040: JS LOG: [LookingGlass/info] Adding systray: parcellite (24x24px)
Gjs-Message: 18:40:31.042: JS LOG: [LookingGlass/info] Adding systray: input-method (24x24px)
Gjs-Message: 18:40:31.116: JS LOG: [LookingGlass/info] Hiding systray: network
Gjs-Message: 18:40:31.117: JS LOG: [LookingGlass/info] Adding systray: parcellite (24x24px)
Gjs-Message: 18:40:31.119: JS LOG: [LookingGlass/info] Adding systray: input-method (24x24px)
Gjs-Message: 18:40:31.122: JS LOG: [LookingGlass/info] Hiding systray: network
Gjs-Message: 18:40:31.123: JS LOG: [LookingGlass/info] Adding systray: parcellite (24x24px)
Gjs-Message: 18:40:31.126: JS LOG: [LookingGlass/info] Adding systray: input-method (24x24px)
Gjs-Message: 18:40:31.171: JS LOG: [LookingGlass/info] Hiding systray: network
Gjs-Message: 18:40:31.173: JS LOG: [LookingGlass/info] Adding systray: parcellite (24x24px)
Gjs-Message: 18:40:31.174: JS LOG: [LookingGlass/info] Adding systray: input-method (24x24px)
Gjs-Message: 18:40:31.176: JS LOG: [LookingGlass/info] Hiding systray: network
Gjs-Message: 18:40:31.177: JS LOG: [LookingGlass/info] Adding systray: parcellite (24x24px)
Gjs-Message: 18:40:31.179: JS LOG: [LookingGlass/info] Adding systray: input-method (24x24px)
Gjs-Message: 18:40:31.181: JS LOG: [LookingGlass/info] Hiding systray: network
Gjs-Message: 18:40:31.182: JS LOG: [LookingGlass/info] Adding systray: parcellite (24x24px)
Gjs-Message: 18:40:31.184: JS LOG: [LookingGlass/info] Adding systray: input-method (24x24px)
Gjs-Message: 18:40:31.187: JS LOG: [LookingGlass/info] Hiding systray: network
Gjs-Message: 18:40:31.188: JS LOG: [LookingGlass/info] Adding systray: parcellite (24x24px)
Gjs-Message: 18:40:31.189: JS LOG: [LookingGlass/info] Adding systray: input-method (24x24px)
Gjs-Message: 18:40:31.191: JS LOG: [LookingGlass/info] Hiding systray: network
Gjs-Message: 18:40:31.192: JS LOG: [LookingGlass/info] Adding systray: parcellite (24x24px)
Gjs-Message: 18:40:31.194: JS LOG: [LookingGlass/info] Adding systray: input-method (24x24px)
Gjs-Message: 18:40:31.195: JS LOG: [LookingGlass/info] Hiding systray: network
Gjs-Message: 18:40:31.197: JS LOG: [LookingGlass/info] Adding systray: parcellite (24x24px)
Gjs-Message: 18:40:31.199: JS LOG: [LookingGlass/info] Adding systray: input-method (24x24px)
Gjs-Message: 18:40:31.201: JS LOG: [LookingGlass/info] Hiding systray: network
Gjs-Message: 18:40:31.202: JS LOG: [LookingGlass/info] Adding systray: parcellite (24x24px)
Gjs-Message: 18:40:31.203: JS LOG: [LookingGlass/info] Adding systray: input-method (24x24px)
Gjs-Message: 18:40:31.206: JS LOG: [LookingGlass/info] Hiding systray: network
Gjs-Message: 18:40:31.207: JS LOG: [LookingGlass/info] Adding systray: parcellite (24x24px)
Gjs-Message: 18:40:31.208: JS LOG: [LookingGlass/info] Adding systray: input-method (24x24px)
Gjs-Message: 18:40:31.210: JS LOG: [LookingGlass/info] Hiding systray: network
Gjs-Message: 18:40:31.211: JS LOG: [LookingGlass/info] Adding systray: parcellite (24x24px)
Gjs-Message: 18:40:31.212: JS LOG: [LookingGlass/info] Adding systray: input-method (24x24px)
Gjs-Message: 18:40:31.214: JS LOG: [LookingGlass/info] Hiding systray: network
Gjs-Message: 18:40:31.215: JS LOG: [LookingGlass/info] Adding systray: parcellite (24x24px)
Gjs-Message: 18:40:31.217: JS LOG: [LookingGlass/info] Adding systray: input-method (24x24px)
Gjs-Message: 18:40:31.219: JS LOG: [LookingGlass/info] Hiding systray: network
Gjs-Message: 18:40:31.220: JS LOG: [LookingGlass/info] Adding systray: parcellite (24x24px)
Gjs-Message: 18:40:31.222: JS LOG: [LookingGlass/info] Adding systray: input-method (24x24px)
Gjs-Message: 18:40:31.224: JS LOG: [LookingGlass/info] Hiding systray: network
Gjs-Message: 18:40:31.226: JS LOG: [LookingGlass/info] Adding systray: parcellite (24x24px)
Gjs-Message: 18:40:31.228: JS LOG: [LookingGlass/info] Adding systray: input-method (24x24px)
Gjs-Message: 18:40:31.230: JS LOG: [LookingGlass/info] Hiding systray: network
Gjs-Message: 18:40:31.231: JS LOG: [LookingGlass/info] Adding systray: parcellite (24x24px)
Gjs-Message: 18:40:31.233: JS LOG: [LookingGlass/info] Adding systray: input-method (24x24px)
Gjs-Message: 18:40:31.235: JS LOG: [LookingGlass/info] Hiding systray: network
Gjs-Message: 18:40:31.236: JS LOG: [LookingGlass/info] Adding systray: parcellite (24x24px)
Gjs-Message: 18:40:31.237: JS LOG: [LookingGlass/info] Adding systray: input-method (24x24px)
Gjs-Message: 18:40:31.240: JS LOG: [LookingGlass/info] Hiding systray: network
Gjs-Message: 18:40:31.241: JS LOG: [LookingGlass/info] Adding systray: parcellite (24x24px)
Gjs-Message: 18:40:31.243: JS LOG: [LookingGlass/info] Adding systray: input-method (24x24px)
Gjs-Message: 18:40:31.245: JS LOG: [LookingGlass/info] Hiding systray: network
Gjs-Message: 18:40:31.245: JS LOG: [LookingGlass/info] Adding systray: parcellite (24x24px)
Gjs-Message: 18:40:31.247: JS LOG: [LookingGlass/info] Adding systray: input-method (24x24px)
Gjs-Message: 18:40:31.249: JS LOG: [LookingGlass/info] Hiding systray: network
Gjs-Message: 18:40:31.250: JS LOG: [LookingGlass/info] Adding systray: parcellite (24x24px)
Gjs-Message: 18:40:31.251: JS LOG: [LookingGlass/info] Adding systray: input-method (24x24px)
Gjs-Message: 18:40:31.253: JS LOG: [LookingGlass/info] Hiding systray: network
Gjs-Message: 18:40:31.254: JS LOG: [LookingGlass/info] Adding systray: parcellite (24x24px)
Gjs-Message: 18:40:31.256: JS LOG: [LookingGlass/info] Adding systray: input-method (24x24px)
Gjs-Message: 18:40:31.258: JS LOG: [LookingGlass/info] Hiding systray: network
Gjs-Message: 18:40:31.259: JS LOG: [LookingGlass/info] Adding systray: parcellite (24x24px)
Gjs-Message: 18:40:31.260: JS LOG: [LookingGlass/info] Adding systray: input-method (24x24px)
Gjs-Message: 18:40:31.434: JS LOG: [LookingGlass/info] Hiding systray: network
Gjs-Message: 18:40:31.436: JS LOG: [LookingGlass/info] Adding systray: parcellite (24x24px)
Gjs-Message: 18:40:31.438: JS LOG: [LookingGlass/info] Adding systray: input-method (24x24px)
Gjs-Message: 18:40:31.441: JS LOG: [LookingGlass/info] Hiding systray: network
Gjs-Message: 18:40:31.442: JS LOG: [LookingGlass/info] Adding systray: parcellite (24x24px)
Gjs-Message: 18:40:31.445: JS LOG: [LookingGlass/info] Adding systray: input-method (24x24px)

(cinnamon:1681): St-CRITICAL **: 18:40:32.035: cr_parser_new_from_buf: assertion 'a_buf && a_len' failed

(cinnamon:1681): St-CRITICAL **: 18:40:32.035: cr_declaration_parse_list_from_buf: assertion 'parser' failed

** (csd-power:1491): CRITICAL **: 18:40:32.202: abs_to_percentage: assertion 'max > min' failed
Gjs-Message: 18:40:32.209: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: telegramdesktop (:1.61/org/x/StatusIcon/Icon_4)
Gjs-Message: 18:40:32.218: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: safeeyes (:1.61/org/x/StatusIcon/Icon_2)
Gjs-Message: 18:40:32.227: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: blueman (:1.61/org/x/StatusIcon/Icon)
Gjs-Message: 18:40:32.239: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: kde connect indicator (:1.61/org/x/StatusIcon/Icon_3)
Gjs-Message: 18:40:32.253: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: psensor (:1.61/org/x/StatusIcon/Icon_1)
Gjs-Message: 18:40:32.299: JS LOG: Unknown network device type, is 32
Gjs-Message: 18:40:32.317: JS LOG: Unknown network device type, is 30
Free 349MB, buffers/cached 3126MB, , available 2987MB
Exception in thread Thread-2 (wait_for_process):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/bin/cinnamon-launcher", line 88, in wait_for_process
    os.execvp(FALLBACK_COMMAND, (FALLBACK_COMMAND,) + FALLBACK_ARGS)
  File "<frozen os>", line 574, in execvp
  File "<frozen os>", line 616, in _execvpe
  File "<frozen os>", line 607, in _execvpe
FileNotFoundError: [Errno 2] No such file or directory
Free 686MB, buffers/cached 2888MB, , available 3112MB
Free 634MB, buffers/cached 2911MB, , available 3092MB
Free 597MB, buffers/cached 2942MB, , available 3095MB
Free 556MB, buffers/cached 2938MB, , available 3053MB

``` 
[cinnamon_calendar_crash.tar.gz](https://github.com/user-attachments/files/15873985/cinnamon_calendar_crash.tar.gz)

**Comment by anttitleppanen** [comment]
Now any applet causes Cinnamon to crash.
