### ISSUE TITLE
Power and Night Light module in cinnamon-settings do not start

### ISSUE THREAD

**Issue by hsbasu** [linuxmint/cinnamon#12556]
### Distribution

Self build Linux MamoLinux

### Package version

6.4.1

### Frequency

Always

### Bug description

cinnamon-settings power module crashing with following error:
```
himadri@himadri:~$ cinnamon-settings power
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:458: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.window.set_wmclass(wm_class, wm_class)
Loading Power module
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 811, in <module>
    window = MainWindow()
             ^^^^^^^^^^^^
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 330, in __init__
    if self.load_sidepage_as_standalone():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 464, in load_sidepage_as_standalone
    self.go_to_sidepage(sp_data.sp, user_action=False)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 185, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 212, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_power.py", line 138, in on_module_selected
    device_types = [x[UP_TYPE] for x in self.csd_power_proxy.GetDevices()]
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gi/overrides/Gio.py", line 349, in __call__
    result = self.dbus_proxy.call_sync(self.method_name, arg_variant,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.cinnamon.SettingsDaemon.Power was not provided by any .service files (2)
```
Similar error is there for in `cs_nightlight.py` when calling `Gio.DBusProxy.new_sync` at line: 77.

### Steps to reproduce

Run `cinnamon-settings power` from terminal.

### Expected behavior

These errors should not be there.

**Comment by corbin-auriti** [comment]
What was the solution to this?
