### ISSUE TITLE
cinnamon-menu-editor fails to open and crashes when editing non ascii records?

### ISSUE THREAD

**Issue by jabbany** [linuxmint/Cinnamon#2752]
I have menu records created by Wine and they are in asian character-set so not in ascii. Whenever I try to do any operation on them (disable or remove) cinnamon-menu-editor will crash with the following stack trace:

    Traceback (most recent call last):
      File "/usr/lib/cinnamon-menu-editor/cme/MainWindow.py", line 397, in on_item_tree_show_toggled
        self.editor.setVisible(item, False)
      File "/usr/lib/cinnamon-menu-editor/cme/MenuEditor.py", line 193, in setVisible
        self.save()
     File "/usr/lib/cinnamon-menu-editor/cme/MenuEditor.py", line 52, in save
        fd.write(self.dom.toprettyxml())
      File "/usr/lib/python2.7/xml/dom/minidom.py", line 61, in toprettyxml
        return writer.getvalue()
      File "/usr/lib/python2.7/StringIO.py", line 271, in getvalue
        self.buf += ''.join(self.buflist)
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 26: ordinal not in range(128)
    Traceback (most recent call last):
      File "/usr/lib/cinnamon-menu-editor/cme/MenuEditor.py", line 48, in menuChanged
        self.load()
      File "/usr/lib/cinnamon-menu-editor/cme/MenuEditor.py", line 44, in load
        if not self.tree.load_sync():
    gi._glib.GError: Error on line 1 char 1: Document was empty or contained only whitespace
    
    ** (cinnamon-menu-editor:14465): CRITICAL **: gmenu_tree_get_root_directory: assertion 'tree->loaded' failed
    Traceback (most recent call last):
      File "/usr/lib/cinnamon-menu-editor/cme/MainWindow.py", line 70, in menuChanged
        self.loadUpdates()
      File "/usr/lib/cinnamon-menu-editor/cme/MainWindow.py", line 99, in loadUpdates
        self.loadMenus()
      File "/usr/lib/cinnamon-menu-editor/cme/MainWindow.py", line 195, in loadMenus
        self.loadMenu({ None: None })
      File "/usr/lib/cinnamon-menu-editor/cme/MainWindow.py", line 206, in loadMenu
        name = cgi.escape(menu.get_name())
    AttributeError: 'NoneType' object has no attribute 'get_name'

Also this will dump an empty `cinnamon-applications.menu` in the `.config/menus` folder which causes any subsequent launches of cinnamon-menu-editor to fail.

    Traceback (most recent call last):
      File "/usr/bin/cinnamon-menu-editor", line 19, in <module>
        main()
      File "/usr/bin/cinnamon-menu-editor", line 15, in main
        app = MainWindow.MainWindow(datadir, version)
      File "/usr/lib/cinnamon-menu-editor/cme/MainWindow.py", line 43, in __init__
        self.editor = MenuEditor()
      File "/usr/lib/cinnamon-menu-editor/cme/MenuEditor.py", line 31, in __init__
        self.load()
      File "/usr/lib/cinnamon-menu-editor/cme/MenuEditor.py", line 44, in load
        if not self.tree.load_sync():
    gi._glib.GError: Error on line 1 char 1: Document was empty or contained only whitespace

**Comment by Vahan86** [comment]
@jabbany, is this still an issue for you in Cinnamon 3.0?

**Comment by jabbany** [comment]
Doesn't seem to break anymore.
