### ISSUE TITLE
Cannot add USB Printer in system-config-printer

### ISSUE THREAD

**Issue by ku3i** [linuxmint/Cinnamon#3044]
When I try to add my USB 2.0 port printer, model HL-2030, the application freezes and must be killed. Setting up the printer via CUS web interface works properly.

Here is the terminal output:

 $ system-config-printer
ERROR:root:Could not find any typelib for GnomeKeyring
No ID match for device usb://Brother/HL-2030%20series?serial=B6J882794:
MFG:Brother;MDL:HL-2030 series;CMD:PJL,HBP;
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gi/overrides/GLib.py", line 629, in <lambda>
    return (lambda data: callback(*data), user_data)
  File "/usr/share/system-config-printer/asyncipp.py", line 191, in send_reply
    handler (self._conn, result)
  File "/usr/share/system-config-printer/asyncpk1.py", line 163, in _ipp_reply_handler
    self._client_reply_handler (self._conn, *args)
  File "/usr/share/system-config-printer/asyncconn.py", line 91, in reply_handler
    self._reply_handler (self, self._reply_data, *args)
  File "/usr/share/system-config-printer/asyncconn.py", line 209, in _subst_reply_handler
    reply_handler (self, *args)
  File "/usr/share/system-config-printer/ppdsloader.py", line 180, in _cups_reply
    ppdname = ppdnamelist[0]
IndexError: list index out of range
Getötet

**Comment by ManIVIctorious** [comment]
System-config-printer is not part of the cinnamon core, therefore it is not possible for the cinnamon devs to fix this issue. Please file the bug to the system-config-printer devs.
