### ISSUE TITLE
cinnamon-slideshow.py:134:ensure_file_is_image:TypeError: cannot concatenate 'str' and 'NoneType' objects

### ISSUE THREAD

**Issue by leigh123linux** [linuxmint/Cinnamon#4280]
Forwarded from https://bugzilla.redhat.com/show_bug.cgi?id=1228963

```
Version-Release number of selected component:
cinnamon-2.6.6-1.fc21

Additional info:
reporter:       libreport-2.3.0
cmdline:        /usr/bin/python2 /usr/lib/cinnamon-slideshow/cinnamon-slideshow.py
executable:     /usr/lib/cinnamon-slideshow/cinnamon-slideshow.py
kernel:         4.0.4-202.fc21.x86_64
runlevel:       N 3
type:           Python
uid:            1000

Truncated backtrace:
#1 ensure_file_is_image in /usr/lib/cinnamon-slideshow/cinnamon-slideshow.py:134
#2 on_next_file_complete in /usr/lib/cinnamon-slideshow/cinnamon-slideshow.py:124
```
bt

```
cinnamon-slideshow.py:134:ensure_file_is_image:TypeError: cannot concatenate 'str' and 'NoneType' objects

Traceback (most recent call last):
  File "/usr/lib/cinnamon-slideshow/cinnamon-slideshow.py", line 124, in on_next_file_complete
    self.ensure_file_is_image(file_list)
  File "/usr/lib/cinnamon-slideshow/cinnamon-slideshow.py", line 134, in ensure_file_is_image
    self.add_image_to_playlist(self.collection_path + "/" + item.get_name())
TypeError: cannot concatenate 'str' and 'NoneType' objects

Local variables in innermost frame:
file_type: <enum G_FILE_TYPE_REGULAR of type GFileType>
item: <FileInfo object at 0x7f4048455780 (GFileInfo at 0x7f4038003ad0)>
file_contents: 'image/jpeg'
self: <__main__.CinnamonSlideshow at /org/Cinnamon/Slideshow at 0x7f404843c210>
file_list: [<FileInfo object at 0x7f4048455780 (GFileInfo at 0x7f4038003ad0)>, <FileInfo object at 0x7f40484557d0 (GFileInfo at 0x7f4038005aa0)>, <FileInfo object at 0x7f4048455820 (GFileInfo at 0x2021e40)>, <FileInfo object at 0x7f4048455870 (GFileInfo at 0x209c8c0)>, <FileInfo object at 0x7f40484558c0 (GFileInfo at 0x7f4038003cf0)>, <FileInfo object at 0x7f4048455910 (GFileInfo at 0x7f4038005b00)>, <FileInfo object at 0x7f4048455960 (GFileInfo at 0x7f4038003b60)>, <FileInfo object at 0x7f40484559b0 (GFileInfo at 0x7f4038003a40)>, <FileInfo object at 0x7f4048455a00 (GFileInfo at 0x7f4040008410)>, <FileInfo object at 0x7f4048455a50 (GFileInfo at 0x209c950)>, <FileInfo object at 0x7f4048455aa0 (GFileInfo at 0x219c4a0)>, <FileInfo object at 0x7f4048455af0 (GFileInfo at 0x219c260)>, <FileInfo object at 0x7f4048455b40 (GFileInfo at 0x7f4038005a70)>, <FileInfo object at 0x7f4048455b90 (GFileInfo at 0x7f4038005d20)>, <FileInfo object at 0x7f4048455be0 (GFileInfo at 0x7f4038005cc0)>, <FileInfo object at 0x7f4048455c30 (GFileInfo at 0x7f4038005f60)>, <FileInfo object at 0x7f4048455c80 (GFileInfo at 0x2021ea0)>, <FileInfo object at 0x7f4048455cd0 (GFileInfo at 0x7f4038003830)>, <FileInfo object at 0x7f4048455d20 (GFileInfo at 0x7f4040017190)>, <FileInfo object at 0x7f4048455d70 (GFileInfo at 0x219c720)>, <FileInfo object at 0x7f4048455dc0 (GFileInfo at 0x219c780)>, <FileInfo object at 0x7f4048455e10 (GFileInfo at 0x7f4038007030)>, <FileInfo object at 0x7f4048455e60 (GFileInfo at 0x7f4038007090)>, <FileInfo object at 0x7f4048455eb0 (GFileInfo at 0x7f40380070f0)>, <FileInfo object at 0x7f4048455f00 (GFileInfo at 0x7f4038007150)>, <FileInfo object at 0x7f4048455f50 (GFileInfo at 0x7f4038007210)>, <FileInfo object at 0x7f4048455fa0 (GFileInfo at 0x7f4038007270)>, <FileInfo object at 0x7f40459f5050 (GFileInfo at 0x7f40380072d0)>, <FileInfo object at 0x7f40459f50a0 (GFileInfo at 0x7f4038007330)>, <FileInfo object at 0x7f40459f50f0 (GFileInfo at 0x7f4038007390)>, <FileInfo object at 0x7f40459f5140 (GFileInfo at 0x7f4038007430)>, <FileInfo object at 0x7f40459f5190 (GFileInfo at 0x7f4038007490)>, <FileInfo object at 0x7f40459f51e0 (GFileInfo at 0x7f40380074f0)>, <FileInfo object at 0x7f40459f5230 (GFileInfo at 0x7f4038007550)>, <FileInfo object at 0x7f40459f5280 (GFileInfo at 0x7f4038007610)>, <FileInfo object at 0x7f40459f52d0 (GFileInfo at 0x7f4038007670)>, <FileInfo object at 0x7f40459f5320 (GFileInfo at 0x7f40380076d0)>, <FileInfo object at 0x7f40459f5370 (GFileInfo at 0x7f4038007730)>, <FileInfo object at 0x7f40459f53c0 (GFileInfo at 0x7f4038007790)>, <FileInfo object at 0x7f40459f5410 (GFileInfo at 0x7f4038007830)>, <FileInfo object at 0x7f40459f5460 (GFileInfo at 0x7f4038007890)>, <FileInfo object at 0x7f40459f54b0 (GFileInfo at 0x7f40380078f0)>, <FileInfo object at 0x7f40459f5500 (GFileInfo at 0x7f4038007950)>, <FileInfo object at 0x7f40459f5550 (GFileInfo at 0x7f4038007a10)>, <FileInfo object at 0x7f40459f55a0 (GFileInfo at 0x7f4038007a70)>, <FileInfo object at 0x7f40459f55f0 (GFileInfo at 0x7f4038007ad0)>, <FileInfo object at 0x7f40459f5640 (GFileInfo at 0x7f4038007b30)>, <FileInfo object at 0x7f40459f5690 (GFileInfo at 0x7f4038008c00)>, <FileInfo object at 0x7f40459f56e0 (GFileInfo at 0x7f40380088f0)>, <FileInfo object at 0x7f40459f5730 (GFileInfo at 0x7f4040016ca0)>, <FileInfo object at 0x7f40459f5780 (GFileInfo at 0x7f4040016f80)>, <FileInfo object at 0x7f40459f57d0 (GFileInfo at 0x7f4038008d20)>, <FileInfo object at 0x7f40459f5820 (GFileInfo at 0x7f4038008670)>, <FileInfo object at 0x7f40459f5870 (GFileInfo at 0x7f4038007c00)>, <FileInfo object at 0x7f40459f58c0 (GFileInfo at 0x7f4038005a40)>, <FileInfo object at 0x7f40459f5910 (GFileInfo at 0x7f4038008800)>, <FileInfo object at 0x7f40459f5960 (GFileInfo at 0x7f40380088c0)>, <FileInfo object at 0x7f40459f59b0 (GFileInfo at 0x7f4038008920)>, <FileInfo object at 0x7f40459f5a00 (GFileInfo at 0x7f4038008a70)>, <FileInfo object at 0x7f40459f5a50 (GFileInfo at 0x7f4038008760)>, <FileInfo object at 0x7f40459f5aa0 (GFileInfo at 0x7f4038008a40)>, <FileInfo object at 0x7f40459f5af0 (GFileInfo at 0x7f4040017040)>, <FileInfo object at 0x7f40459f5b40 (GFileInfo at 0x7f4040017070)>]
```

**Comment by gstlouis** [comment]
I found the issue. item.get_name() is returning None, which is causing the exception. This is because the enumerate_children_async call on line 103 is only requesting the type and content-type fields. Add standard::type to the list of requested fields and that fixes the issue.

```
--- /usr/share/cinnamon/cinnamon-slideshow/cinnamon-slideshow.py.orig	2016-02-21 16:03:26.812873506 -0600
+++ /usr/share/cinnamon/cinnamon-slideshow/cinnamon-slideshow.py	2016-02-21 16:01:33.196094974 -0600
@@ -100,7 +100,7 @@
             folder_at_path = Gio.file_new_for_path(self.collection_path)
 
             if folder_at_path.query_exists(None):
-                folder_at_path.enumerate_children_async("standard::type,standard::content-type",
+                folder_at_path.enumerate_children_async("standard::name,standard::type,standard::content-type",
                                                         Gio.FileQueryInfoFlags.NONE,
                                                         GLib.PRIORITY_LOW,
                                                         None,
```

**Comment by ian-bertolacci** [comment]
This bug is still present in Cinnamon 2.8.5

**Comment by dralley** [comment]
@dalcde fix was merged, this issue can be closed
