### ISSUE TITLE
Error when open Power Management, cinnamon 2.6.6

### ISSUE THREAD

**Issue by tkdchen** [linuxmint/Cinnamon#4299]
Version: `2.6.6`
Fedora 21

When open Power Management, following error occurs

```
Loading Power module
Traceback (most recent call last):
  File "/usr/lib/cinnamon-settings/cinnamon-settings.py", line 540, in button_press
    self.side_view_nav(widget, None, category)
  File "/usr/lib/cinnamon-settings/cinnamon-settings.py", line 108, in side_view_nav
    self.go_to_sidepage(cat, filtered_path)
  File "/usr/lib/cinnamon-settings/cinnamon-settings.py", line 121, in go_to_sidepage
    sidePage.build()
  File "/usr/lib/cinnamon-settings/bin/SettingsWidgets.py", line 328, in build
    self.module.on_module_selected()
  File "/usr/lib/cinnamon-settings/modules/cs_power.py", line 167, in on_module_selected
    self.build_battery_page()
  File "/usr/lib/cinnamon-settings/modules/cs_power.py", line 269, in build_battery_page
    widget = set_device_battery_additional(device)
NameError: global name 'set_device_battery_additional' is not defined
```

**Comment by dalcde** [comment]
Fixed in git master
