### ISSUE TITLE
Cinnamon 2.6.9 power manager don't start

### ISSUE THREAD

**Issue by marcogiannini** [linuxmint/Cinnamon#4355]
Linux Mint 17.2 RC 64-bit
Cinnamon 2.6.9

What happened:
If i run Cinnamon Power Setting application do not start.
If i run from terminal i have this error:

marco@mint ~ $ cinnamon-settings power
Python module
Loading Power module
Traceback (most recent call last):
  File "/usr/lib/cinnamon-settings/cinnamon-settings.py", line 597, in <module>
    window = MainWindow()
  File "/usr/lib/cinnamon-settings/cinnamon-settings.py", line 89, in wrapper
    res = func(*arg)
  File "/usr/lib/cinnamon-settings/cinnamon-settings.py", line 312, in __init__
    self.go_to_sidepage(cat, path)
  File "/usr/lib/cinnamon-settings/cinnamon-settings.py", line 126, in go_to_sidepage
    sidePage.stack.set_visible_child(l[0])
IndexError: list index out of range
marco@mint ~ $

**Comment by marcogiannini** [comment]
If i run with sudo

marco@mint ~ $ sudo cinnamon-settings power
Python module
Traceback (most recent call last):
  File "/usr/lib/cinnamon-settings/cinnamon-settings.py", line 38, in <module>
    modules = map(__import__, mod_files)
  File "/usr/lib/cinnamon-settings/modules/cs_startup.py", line 9, in <module>
    ENVIRON = os.environ['XDG_CURRENT_DESKTOP']
  File "/usr/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'XDG_CURRENT_DESKTOP'

**Comment by pixunil** [comment]
I could reproduce this also in Cinnamon version `2.6.9`, but after an update to `2.6.10`, it disappeared.

The second issue with `sudo cinnamon-settings` is a different and isn't imo worth for fixing as `cinnamon-setttings` doesn't need root rights and the startup module needs this environment variable, but doesn't find it.

**Comment by JosephMcc** [comment]
I believe this issue is fixed by this: https://github.com/linuxmint/Cinnamon/commit/3c40166eb8dd0c566fc520db8034f35d7559da2e

**Comment by ProfessorKaos64** [comment]
I have this as well, running on Arch Linux 4.0.6-1-ARCH. Same version as described. Guess I'll need to wait for the upstream fix to hit the maintainers package.

**Comment by marcogiannini** [comment]
I confirm, no more issue with Cinnamon 2.6.11
