### ISSUE TITLE
Segfault fault: Command '['cinnamon', '--version']' returned non-zero exit status -11

### ISSUE THREAD

**Issue by trusktr** [linuxmint/Cinnamon#4542]
I'm getting an error when trying to run cinnamon-settings, which tells me the error in the above title. `The output of`cinnamon --version`:

```
% cinnamon --version
Cinnamon 2.6.13
[1]    4991 segmentation fault (core dumped)  cinnamon --version
```

Here's gdb output:

```
% gdb python2
GNU gdb (GDB) 7.9.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python2...(no debugging symbols found)...done.
(gdb) run /usr/bin/cinnamon-settings
Starting program: /usr/bin/python2 /usr/bin/cinnamon-settings
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
process 4870 is executing new program: /usr/bin/env
process 4870 is executing new program: /usr/bin/python2.7
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Traceback (most recent call last):
  File "/usr/lib/cinnamon-settings/cinnamon-settings.py", line 38, in <module>
    modules = map(__import__, mod_files)
  File "/usr/lib/cinnamon-settings/modules/cs_applets.py", line 3, in <module>
    from ExtensionCore import ExtensionSidePage
  File "/usr/lib/cinnamon-settings/bin/ExtensionCore.py", line 29, in <module>
    curr_ver = subprocess.check_output(["cinnamon", "--version"]).splitlines()[0].split(" ")[1]
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['cinnamon', '--version']' returned non-zero exit status -11
[New Thread 0x7fffe830b700 (LWP 4874)]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff78087e0 in __lll_unlock_elision () from /usr/lib/libpthread.so.0
(gdb) bt
#0  0x00007ffff78087e0 in __lll_unlock_elision () from /usr/lib/libpthread.so.0
#1  0x00007fffeee5c26c in ?? () from /usr/lib/libEGL.so.1
#2  0x00007fffeedeca22 in ?? () from /usr/lib/libEGL.so.1
#3  0x00007fffffffd560 in ?? ()
#4  0x00007fffeee70ea1 in ?? () from /usr/lib/libEGL.so.1
#5  0x00007fffffffd560 in ?? ()
#6  0x00007ffff7dea885 in _dl_fini () from /lib64/ld-linux-x86-64.so.2
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb)
```

I'm running nvidia `352.30-3`, and linux `4.1.5-1`. Is there any more info that might help?

**Comment by GLolol** [comment]
Same issue as #4532, but this one a lot more verbose.

**Comment by ruthan** [comment]
My kernel version is 3.16 and im using proprietary Nvidia drivers too.

**Comment by leigh123linux** [comment]
This backtrace indicates a X issue


```
(gdb) bt
#0  0x00007ffff78087e0 in __lll_unlock_elision () from /usr/lib/libpthread.so.0
#1  0x00007fffeee5c26c in ?? () from /usr/lib/libEGL.so.1
#2  0x00007fffeedeca22 in ?? () from /usr/lib/libEGL.so.1
#3  0x00007fffffffd560 in ?? ()
#4  0x00007fffeee70ea1 in ?? () from /usr/lib/libEGL.so.1
#5  0x00007fffffffd560 in ?? ()
#6  0x00007ffff7dea885 in _dl_fini () from /lib64/ld-linux-x86-64.so.2
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb)
```

**Comment by jazzlyn** [comment]
hey guys,

on arch microcode for intel cpus is no longer loaded automatically:
https://wiki.archlinux.org/index.php/Microcode#Enabling_Intel_Microcode_Updates

Changes to Intel microcode updates
2014-10-22 - Thomas Bächler
Microcode on Intel CPUs is no longer loaded automatically, as it needs to be loaded very early in the boot process. This requires adjustments in the bootloader. If you have an Intel CPU, please follow the instructions in the wiki.

that fixed it for me.

**Comment by ManIVIctorious** [comment]
This works for me with cinnamon 3.0.7 on Arch Linux. Is this issue still relevant for some of you in latest cinnamon?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?
