### ISSUE TITLE
[cinnamon-settings effects] AttributeError: 'NoneType' object has no attribute 'get_selected'

### ISSUE THREAD

**Issue by leigh123linux** [linuxmint/Cinnamon#4552]
I am getting this error with the effects tab in fedora 23.

```
Loading Effects module
/usr/lib/cinnamon-settings/modules/cs_effects.py:80: PyGIDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "schema" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  self.schema = Gio.Settings(SCHEMA)
/usr/lib/cinnamon-settings/modules/cs_effects.py:182: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_("ms"))
Traceback (most recent call last):
  File "/usr/lib/cinnamon-settings/bin/ExtensionCore.py", line 179, in <lambda>
    self.settings.connect("changed::name", lambda x, y: self._enabled_extensions_changed())
  File "/usr/lib/cinnamon-settings/bin/ExtensionCore.py", line 1057, in _enabled_extensions_changed
    model, treeiter = self.treeview.get_selection().get_selected()
AttributeError: 'NoneType' object has no attribute 'get_selected'
Traceback (most recent call last):
  File "/usr/lib/cinnamon-settings/bin/ExtensionCore.py", line 179, in <lambda>
    self.settings.connect("changed::name", lambda x, y: self._enabled_extensions_changed())
  File "/usr/lib/cinnamon-settings/bin/ExtensionCore.py", line 1057, in _enabled_extensions_changed
    model, treeiter = self.treeview.get_selection().get_selected()
AttributeError: 'NoneType' object has no attribute 'get_selected'
Traceback (most recent call last):
  File "/usr/lib/cinnamon-settings/bin/ExtensionCore.py", line 179, in <lambda>
    self.settings.connect("changed::name", lambda x, y: self._enabled_extensions_changed())
  File "/usr/lib/cinnamon-settings/bin/ExtensionCore.py", line 1057, in _enabled_extensions_changed
    model, treeiter = self.treeview.get_selection().get_selected()
AttributeError: 'NoneType' object has no attribute 'get_selected'
Traceback (most recent call last):
  File "/usr/lib/cinnamon-settings/bin/ExtensionCore.py", line 179, in <lambda>
    self.settings.connect("changed::name", lambda x, y: self._enabled_extensions_changed())
  File "/usr/lib/cinnamon-settings/bin/ExtensionCore.py", line 1057, in _enabled_extensions_changed
    model, treeiter = self.treeview.get_selection().get_selected()
AttributeError: 'NoneType' object has no attribute 'get_selected'

```

**Comment by JosephMcc** [comment]
Does this still happen in Cinnamon 2.8?

**Comment by leigh123linux** [comment]
No it's fixed

```
[leigh@beta-pc ~]$ uname -r
4.2.3-300.fc23.x86_64
[leigh@beta-pc ~]$ cinnamon-settings effects
Python module
Could not find bluetooth module; is the cinnamon-control-center package installed?
Loading Effects module
__init__ took 280.222 ms
```
