### ISSUE TITLE
Unable to add app into startup  session apps

### ISSUE THREAD

**Issue by andrepontesmelo** [linuxmint/Cinnamon#5199]
Tested and could reproduce in two different installations with same following versions. 

# Version
 * Cinnamon 2.8.7
 * Fedora 23
 * Kernel 4.4.6-301.fc23.x86_64 

# How to reproduce

1. run cinnamon-settings startup,
1. click add personalized, 
1. and add as input "a" for name, command, and commend
1. finally click Add.

##  Expected
The popup should be closed and it would be expected the new app "a" to be inserted in the list.

## Current behavior
The popup is closed, and the list is not being changed. Additionally, the following call trace is displayed in the command line

# Traceback
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_startup.py", line 489, in on_add_custom
    filename = self.find_free_basename(info["name"])
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_startup.py", line 563, in find_free_basename
    while (self.find_app_with_basename(basename) is not None and
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_startup.py", line 576, in find_app_with_basename
    if basename == app.basename:
AttributeError: AutostartApp instance has no attribute 'basename'

This might be a duplicate of #4765.

**Comment by andrepontesmelo** [comment]
Adding pull request https://github.com/linuxmint/Cinnamon/pull/5200 that fixes this issue.

**Comment by andrepontesmelo** [comment]
thx, It's fixed now.
