### ISSUE TITLE
Not openning some windows, like sound settings

### ISSUE THREAD

**Issue by lucasmatheustesta** [linuxmint/Cinnamon#5345]
Hi, 
When I start my computer, a message saying that some of the extensions did not start correctly appears and also in the terminal i type "cinnamon-settings" the following error appear:

Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 40, in <module>
    modules = map(__import__, mod_files)
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py", line 4, in <module>
    gi.require_version('Cvc', '1.0')
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Cvc not available

Could you help me please ?

Thank very much.

**Comment by lucasmatheustesta** [comment]
I already fix it.
using apt-get dist-upgrade.
Thank you.
