### ISSUE TITLE
Missing bluetooth icons on Fedora Cinnamon

### ISSUE THREAD

**Issue by davidgfnet** [linuxmint/Cinnamon#5350]
Hello!

For some reason, after an update my bluetooth icons have disappeared (or something similar). Therefore I get this:

```
py sound
Loading Sound module
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py", line 722, in deviceAdded
    icon = iconTheme.load_icon("bluetooth", 32, 0)
GLib.Error: gtk-icon-theme-error-quark: Icon 'bluetooth' not present in theme gnome (0)
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py", line 722, in deviceAdded
    icon = iconTheme.load_icon("bluetooth", 32, 0)
GLib.Error: gtk-icon-theme-error-quark: Icon 'bluetooth' not present in theme gnome (0)

```

Whenever I run python2 /usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py sound
That means that my bluetooth device doesn't show up in the list. I hacked the script to make it work but I think it's a good idea to have a try/except block there (or something similar) to display a dummy icon in case the requested icon doesn't exist.

Thanks!

**Comment by davidgfnet** [comment]
Thanks for the fix!
Since it will take a while for this to propagate into Fedora repos, if someone is experiencing this just replace "bluetooth" for "audio-card" in the /usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py file and it should work.
