### ISSUE TITLE
Starting /usr/bin/sniff crashes cinnamon

### ISSUE THREAD

**Issue by Piiit** [linuxmint/Cinnamon#5395]
Related issue: https://github.com/linuxmint/xreader/issues/15

From dogtail docs: `A useful tool for writing dogtail scripts is Sniff (/usr/bin/sniff or "AT-SPI Browser" in your menu), a graphical browser of that hierarchy written using dogtail.`

I just start sniff in console and cinnamon crashes, gets in fallback mode and asks to restart. Restarting works without problems... 

This is the console output: 

```
(sniff:8142): Gtk-WARNING **: Failed to set property GtkHButtonBox.layout-style to : Could not parse enum: `'
/usr/lib/python2.7/dist-packages/gi/types.py:259: RuntimeWarning: Mixin class dogtail.tree.Application is an old style class, please update this to derive from "object".
  RuntimeWarning)
/usr/lib/python2.7/dist-packages/gi/types.py:259: RuntimeWarning: Mixin class dogtail.tree.Node is an old style class, please update this to derive from "object".
  RuntimeWarning)
/usr/lib/python2.7/dist-packages/gi/types.py:259: RuntimeWarning: Mixin class dogtail.tree.Root is an old style class, please update this to derive from "object".
  RuntimeWarning)
Traceback (most recent call last):
  File "/usr/bin/sniff", line 249, in rowExpanded
    self.treeModel.populateChildren(childRow.iter)
  File "/usr/bin/sniff", line 432, in populateChildren
    for child in node.children:
  File "/usr/lib/python2.7/dist-packages/dogtail/tree.py", line 217, in children
    if self.parent and self.parent.roleName == 'hyper link':
GError: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

Traceback (most recent call last):
  File "/usr/bin/sniff", line 249, in rowExpanded
    self.treeModel.populateChildren(childRow.iter)
  File "/usr/bin/sniff", line 432, in populateChildren
    for child in node.children:
  File "/usr/lib/python2.7/dist-packages/dogtail/tree.py", line 217, in children
    if self.parent and self.parent.roleName == 'hyper link':
GError: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```

**Comment by Piiit** [comment]
Please note: It does not crash when AT is enabled for cinnamon with gsettings set org.cinnamon.desktop.interface toolkit-accessibility true

**Comment by clefebvre** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (3.6). If the issue happens again, create a new issue and add a stracktrace.

**Comment by Piiit** [comment]
@clefebvre Tested... It did not crash on Cinnamon 3.6.7
