### ISSUE TITLE
Cannot open Power Management

### ISSUE THREAD

**Issue by ghost** [linuxmint/Cinnamon#5522]
When power management item on system settings window is clicked the window just dissappears. 

When cinnamon-settings power is issued on terminal it returns :
Loading Power module
Segmentation fault

When sudo cinnamon-settings power is issued the following is observed :
Loading Power module
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 609, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 313, in **init**
    self.go_to_sidepage(cat, path)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 123, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 333, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_power.py", line 114, in on_module_selected
    device_types = [x[UP_TYPE] for x in self.csd_power_proxy.GetDevices()]
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gio.py", line 171, in **call**
    None)
GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.cinnamon.SettingsDaemon was not provided by any .service files (2)

Using Cinnamon 3.0.4 on debian, also i tried every other item on system settings menu and each of them works except power management.

**Comment by morsok** [comment]
Same issue using cinnamon 3.0.6 on Ubuntu 16.04

**Comment by mainmachine** [comment]
Same here on 3.0.6 Ubuntu 16.04, stable build from the Kranich PPA

**Comment by rbag** [comment]
Confirmed on my gf laptop running Ubuntu.

**Comment by PhJmsa** [comment]
Confirmed on Cinnamon 3.0.6 Ubuntu 16.04, stable build from the Kranich PPA.

**Comment by PhJmsa** [comment]
Solved with update 3.07-1 from Kranish ppa.

**Comment by leigh123linux** [comment]
It was fixed in 3.0.7 release

https://github.com/linuxmint/Cinnamon/commit/7a97c28c652abe7a4e8a47787109e9ba9beeea51

**Comment by GeorgiKarapetrov** [comment]
I have this on Cinnamon 4 or later. What is a way to fix this manually
