### ISSUE TITLE
Launching the applets settings widget causes python error

### ISSUE THREAD

**Issue by nathan-b** [linuxmint/Cinnamon#5773]
```
[nathan@nathanb-nuc ~/bin] cinnamon-settings applets
Loading Applets module
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 603, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 316, in __init__
    self.go_to_sidepage(cat, path)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 123, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 333, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_applets.py", line 16, in on_module_selected
    self.sidePage.load()
  File "/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py", line 457, in load
    self.spices.scrubConfigDirs(self.enabled_extensions)
  File "/usr/share/cinnamon/cinnamon-settings/bin/Spices.py", line 727, in scrubConfigDirs
    panel, align, order, uuid, id = enabled.split(":")
ValueError: need more than 4 values to unpack

```
This is a fresh Cinnamon install on a fresh Arch Linux. I had a previous install of Cinnamon some months ago, though, so there could be an old setting in my homedir it picked up.

**Comment by nathan-b** [comment]
This seems relevant to bug #5008, though the root cause is not the same. I suspect in this case the root cause would be the residual settings from my previous install.

The question in this case would be why Cinnamon didn't detect and repair this problem as @mtwebster mentioned in that bug when it was first run.

**Comment by nathan-b** [comment]
Weirdly, Cinnamon appears to have fixed itself somehow. Sorry I don't have any more information for posterity. Since I can't repro this I'm going ahead and closing it.
