### ISSUE TITLE
cinnamon-settings power does not start with Xinerama enabled

### ISSUE THREAD

**Issue by adginz** [linuxmint/Cinnamon#6073]
This occurs on Linux Mint 17.x and Linux Mint 18 (up-to-date as of now to Level 3). Cinnamon version is 3.0.7+sarah.
I have two Nvidia GeForce GT 730 cards with 2 monitors on each = total 4 monitors and need to use Xinerama to have them working properly. Enabling Xinerama effectively turns off the RandR extension.
It appears that without Randr several parts of Cinnamon do not work - Power Settings (does not show). 
The issue is reproducible every time.
I suspect that Cinnamon just cannot get display devices without Randr.
Please note that before enabling Xinerama the Power settings window showed up ok and displayed the UPS and a wireless mouse battery level properly as well as power options.
Here is the command output.
~ $ cinnamon-settings power
Loading Power module
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 603, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 316, in __init__
    self.go_to_sidepage(cat, path)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 123, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 333, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_power.py", line 114, in on_module_selected
    device_types = [x[UP_TYPE] for x in self.csd_power_proxy.GetDevices()]
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gio.py", line 171, in __call__
    None)
GLib.Error: g-io-error-quark: Timeout was reached (24)

**Comment by leigh123linux** [comment]
Xinerama isn't support by nvidia so why should we support your unsupported use?

**Comment by adginz** [comment]
Nvidia does support Xinerama - please see the checkbox "Enable Xinerama" in the Nvidia X Server Settings tool on this screenshot.

![screenshot from 2016-12-08 06-34-16](https://cloud.githubusercontent.com/assets/24451933/21008622/7f3bd384-bd10-11e6-82d6-d9f010644ffd.png)

**Comment by adginz** [comment]
In my case I set each monitor to be in its own X screen, so I have 4 monitors and 4 X screens. Xinerama allows to re-arrange them according to their physical layout and use them e.g. in FreeRDP so that true multi-monitor setup works. Without Cinerama it does not work.
Thank you for your consideration.

**Comment by leigh123linux** [comment]
Try running this as standard user

```
gsettings set org.cinnamon.settings-daemon.plugins.xrandr active false
```

Xinerama has never played nice with xrandr

**Comment by adginz** [comment]
Thanks. I tried running it and also tried rebooting after that.
gsettings get org.cinnamon.settings-daemon.plugins.xrandr active    
returns false meaning the setting did get changed.
cinnamon-settings power still does not start and stops with similar or same output as before:
~ $ cinnamon-settings power
Loading Power module
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 603, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 316, in __init__
    self.go_to_sidepage(cat, path)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 123, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 333, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_power.py", line 114, in on_module_selected
    device_types = [x[UP_TYPE] for x in self.csd_power_proxy.GetDevices()]
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gio.py", line 171, in __call__
    None)
GLib.Error: g-io-error-quark: Timeout was reached (24)

Should I set some other similar parameter to true (instead of .xrandr)?

**Comment by adginz** [comment]
I guess I can use dconf-editor as a workaround for now for some of the settings.

**Comment by leigh123linux** [comment]
Does upower still see the ups

```
upower -d
```

**Comment by adginz** [comment]
Here is some additional info.
Given this 4 monitor setup if I enable Xinerama then I have the above described issue in Power Settings window not showing up as well as some other bugs - e.g. mouse over stops working in the menu categories column so I have to use keyboard after it occurs.
If I disable Xinerama then while MDM sees 4 monitors and I can move the mouse between them correctly at the Login screen level but after logging in the Cinnamon crashes right away on start and goes into the Fallback mode on the topmost screen ignoring the other 3 monitors below. I can still move the mouse to those 3 monitors but the Cinnamon DE occupies only one monitor and in the Fallback mode is very restricted. Also in this Fallback mode Power Settings window shows up without issues.
I would gladly disable Xinerama if there is a way to make Cinnamon work properly with 4 monitors.
Please let me know if I can provide additional information such as specific config files or something else.
Thanks again.

**Comment by gerrnot** [comment]
Same here!

> Xinerama isn't support by nvidia so why should we support your unsupported use?

I use Xinemera to get my DELL UP3214Q monitor running at 4k and 60 Hz via DisplayPort 1.2 in MST mode.
good reference:
https://developer.nvidia.com/4k-ultra-high-resolution-development

If I use only what is shipped with Mint, two Monitors are detected for my singe physical monitor, which is theoretically even correct because  the monitor is running in MST mode and MST seems to work that way. The problems are:
* The task bar only reaches one monitor
* If windows are maximed or videos played in fullscreen, they are only shown on one screen half.

Xinermera seems to allow me to make one monitor (or is that what is better called X screen) out of 2. I know no other method of achieving this and and even that took me quite some fiddling. Nevertheless, now things work very fine, except for that power manager issue!

If Linux Mint would support MST out of the box I would not need to use use Xinemera!
