### ISSUE TITLE
[3.2] Application 'cinnamon.desktop' failed to register before timeout.

### ISSUE THREAD

**Issue by daelvn** [linuxmint/Cinnamon#6076]
Hello.
I've recently installed Arch freshly and tried to install Cinnamon 3.2 with LightDM, but it won't start. Instead, a borderless window says "Cinnamon had an internal error. System is on recovery mode. Do you wish to restart Cinnamon? Yes | No", If I click yes, it pops up again. Fails both with Software Renderer and normal mode.

`journalctl`:
```
Dec 08 17:24:01 daelvn cinnamon-session[403]: WARNING: t+33.86712s: Application 'cinnamon.desktop' failed to register before timeout
Dec 08 17:24:01 daelvn cinnamon-session[403]: CRITICAL: t+33.86749s: We failed, but the fail whale is dead. Sorry...
 ```

`pacman -Qs cinnamon | grep cinnamon`:
```
local/cinnamon 3.2.1-4
local/cinnamon-control-center 3.2.0-1
local/cinnamon-desktop 3.2.0-1
local/cinnamon-menus 3.2.0-1
local/cinnamon-screensaver 3.2.2-1
local/cinnamon-session 3.2.0-1
local/cinnamon-settings-daemon 3.2.0-1
local/cinnamon-translations 3.2.0-1
```

I also know of another issue in this page but it's for version 2.0
Thanks in advance
~ daelvn

**Comment by leigh123linux** [comment]
post the errors in ~/.xsession-errors

**Comment by daelvn** [comment]
X functions, as far as I know. LightDM starts and that uses X.

My .xsession-errors:
```(process:396): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.

(process:430): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.

(cinnamon-launcher:483): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Window manager warning: Locale not understood by C library, internationalization will not work

(cinnamon:504): Clutter-WARNING **: Locale not supported by C library.
Using the fallback 'C' locale.

(cinnamon:504): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.

(cinnamon:504): GModule-CRITICAL **: g_module_close: assertion 'module->ref_count > 0' failed

(cinnamon:504): GModule-CRITICAL **: g_module_close: assertion 'module->ref_count > 0' failed

(cinnamon:504): GModule-CRITICAL **: g_module_close: assertion 'module->ref_count > 0' failed

(cinnamon:504): Clutter-CRITICAL **: Unable to initialize Clutter: Unable to initialize the Clutter backend: no available drivers found.
Window manager error: Unable to initialize Clutter.
Traceback (most recent call last):
  File "/usr/bin/cinnamon-launcher", line 42, in <module>
    os.execvp(FALLBACK_COMMAND, (FALLBACK_COMMAND,) + FALLBACK_ARGS)
  File "/usr/lib/python3.5/os.py", line 615, in execvp
    _execvpe(file, args)
  File "/usr/lib/python3.5/os.py", line 660, in _execvpe
    raise last_exc.with_traceback(tb)
  File "/usr/lib/python3.5/os.py", line 650, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(cinnamon-settings-daemon:430): mouse-plugin-WARNING **: Error while setting libinput Disable While Typing Enabled on "ETPS/2 Elantech Touchpad"
cinnamon-session[396]: WARNING: t+34.82839s: Application 'cinnamon.desktop' failed to register before timeout
cinnamon-session[396]: CRITICAL: t+34.82875s: We failed, but the fail whale is dead. Sorry....

(process:525): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.

(process:526): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Failed to play sound: Sound disabled

(cinnamon-killer-daemon:524): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.

(nemo:522): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.

(process:523): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.

(nm-applet:523): nm-applet-WARNING **: NetworkManager is not running

(nemo:522): Gtk-WARNING **: Allocating size to NemoWindowPane 0x1d60380 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(cinnamon-screensaver-main.py:555): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.```

**Comment by daelvn** [comment]
I can't edit on phone and I cannot edit with Elinks. the .xsession-errors is only missing the 1st line which is identical to the 4th but with a different PID

**Comment by leigh123linux** [comment]
What ever driver your using isn't good enough to satisfy clutter/cinnamon.

```
(cinnamon:504): Clutter-CRITICAL **: Unable to initialize Clutter: Unable to initialize the Clutter backend: no available drivers found.
Window manager error: Unable to initialize Clutter.
```
