### ISSUE TITLE
"Edit Launcher" fails when launcher icon is missing in Cinnamon 3.2

### ISSUE THREAD

**Issue by Shmoopty** [linuxmint/Cinnamon#6156]
When a launcher's icon file is not present, the launcher can no longer be edited/repaired.

To reproduce (fairly simple) :

- Add any launcher to any Cinnamon 3.2 panel
- Edit the launcher by right-clicking the launcher, selecting [Options], [Edit]
- Note that a window titled "Launcher Properties" appears
- In the "Launcher Properties" window, click the icon image and select any image file that could conveniently be deleted
- Click [OK] to dismiss the "Launcher Properties" window
- Delete the image file used as the launcher icon
- Attempt to edit the launcher again by right-clicking the launcher, selecting [Options], [Edit]
- Note that no window appears.  The deleted file must be restored to re-enable launcher editing

**Comment by Shmoopty** [comment]
Note: The same issue occurs if the image file is _moved_ or _renamed_.

**Comment by itzexor** [comment]
$ cinnamon-desktop-editor -mcinnamon-launcher -fcinnamon-custom-launcher-1.desktop /home/exor/.cinnamon/configs/panel-launchers@cinnamon.org/91.json
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-desktop-editor/cinnamon-desktop-editor.py", line 531, in <module>
    Main()
  File "/usr/share/cinnamon/cinnamon-desktop-editor/cinnamon-desktop-editor.py", line 462, in __init__
    editor = CinnamonLauncherEditor(self.orig_file, self.panel_launcher_cb)
  File "/usr/share/cinnamon/cinnamon-desktop-editor/cinnamon-desktop-editor.py", line 173, in __init__
    self.load()
  File "/usr/share/cinnamon/cinnamon-desktop-editor/cinnamon-desktop-editor.py", line 400, in load
    self.set_icon('icon-image', "Icon")
  File "/usr/share/cinnamon/cinnamon-desktop-editor/cinnamon-desktop-editor.py", line 238, in set_icon
    set_icon_string(self.builder.get_object(ctl), val)
  File "/usr/share/cinnamon/cinnamon-desktop-editor/cinnamon-desktop-editor.py", line 80, in set_icon_string
    pixbuf = GdkPixbuf.Pixbuf.new_from_file_at_size(icon, 64, 64)
GLib.Error: g-file-error-quark: Failed to open file '/home/exor/mpv-shot0004.jpg': No such file or directory (4)
