### ISSUE TITLE
Python 3.6 breaks Cinnamon (Cinnamon.Melange fails)

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/Cinnamon#6177]
I'm running Cinnamon under Arch and after the `python3.6` upgrade, many Cinnamon features stopped working. Log files have things like this in them:

```
Jan 06 15:06:30 notebook1 dbus-daemon[556]: Activating service name='org.Cinnamon.Melange'
Jan 06 15:06:30 notebook1 org.Cinnamon.Melange[556]: Traceback (most recent call last):
Jan 06 15:06:30 notebook1 org.Cinnamon.Melange[556]:   File "/usr/bin/cinnamon-looking-glass", line 11, in <module>
Jan 06 15:06:30 notebook1 org.Cinnamon.Melange[556]:     os.execvp("/usr/share/cinnamon/cinnamon-looking-glass/cinnamon-looking-glass.py", ("",) + tuple(sys.argv[1:]))
Jan 06 15:06:30 notebook1 org.Cinnamon.Melange[556]:   File "/usr/lib/python3.6/os.py", line 559, in execvp
Jan 06 15:06:30 notebook1 org.Cinnamon.Melange[556]:     _execvpe(file, args)
Jan 06 15:06:30 notebook1 org.Cinnamon.Melange[556]:   File "/usr/lib/python3.6/os.py", line 583, in _execvpe
Jan 06 15:06:30 notebook1 org.Cinnamon.Melange[556]:     exec_func(file, *argrest)
Jan 06 15:06:30 notebook1 org.Cinnamon.Melange[556]: ValueError: execv() arg 2 first element cannot be empty
Jan 06 15:06:30 notebook1 dbus-daemon[556]: Activated service 'org.Cinnamon.Melange' failed: Process org.Cinnamon.Melange exited with status 1
```

**Comment by Odyseus** [comment]
Hello, @nick-s-b.

Already reported (#6176) [and fixed](https://github.com/linuxmint/Cinnamon/commit/3936ac1e355e9a5f1c2edd1aae4e6da9d2855f45).
