### ISSUE TITLE
configure.ac: missing dep: libkeybinder3

### ISSUE THREAD

**Issue by lots0logs** [linuxmint/Cinnamon#6182]
```
Traceback (most recent call last):
  File "/usr/bin/cinnamon-killer-daemon", line 11, in <module>
    gi.require_version('Keybinder', '3.0')
  File "/usr/lib/python3.6/site-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Keybinder not available
```

**Comment by leigh123linux** [comment]
Why is this needed in configure?, it's not a compile dep.

**Comment by lots0logs** [comment]
Because if its not in configure file then it can go unnoticed by anyone who builds Cinnamon and more importantly, distro package maintainers.

**Comment by leigh123linux** [comment]
There as loads of undeclared  python deps

https://github.com/linuxmint/Cinnamon/blob/master/debian/control#L89

And others like metacity, gnome-panel, tint2 and more.

Adding keybinder is totally pointless!!

**Comment by lots0logs** [comment]
It's not pointless. You're right it's only one out of many that are missing but its a lot easier to add them as they are discovered and less time consuming than it is to go through and find all of them at once. Seems like you already know of several without even having to check, so why don't you submit a PR as well? Then we'd be even closer to solving the overall issue that is missing and undocumented deps for Cinnamon :smiley:

**Comment by leigh123linux** [comment]
As a distro package maintainer I know it is pointless to add crap to the buildroot that isn't required for the package to build.
I also know it's my duty as a distro package maintainer to check the package runs  and add any missing runtime deps to the packaging.

**Comment by lots0logs** [comment]
Well as a distro package maintainer myself, I know that its a PIA to have to waste time trying to figure out dependencies for a program because the developers couldn't take a few minutes to clearly document them. Also, just because a program runs does not mean you've packaged it with all the necessary dependencies. Case in point being libkeybinder. Cinnamon will run just fine without it. That is until you try and use the kill cinnamon keyboard shortcut and it doesn't work.

**Comment by leigh123linux** [comment]
Ok, why don't you document them instead of saddling configure with unneeded deps?

**Comment by clefebvre** [comment]
Hi,

I agree with you both. These should be listed but they're not build deps. Maybe in README.md instead?

**Comment by icarter09** [comment]
@lots0logs can this issue be closed?

**Comment by Vahan86** [comment]
@icarter09, can we close this issue since there is no response from OP?

**Comment by eli-schwartz** [comment]
Well, the issue seems pretty plain to me.

"The dependencies should be documented in some manner that enables distributors to easily check what is needed".

It may have been rejected to document this in configure.ac as build-time checks, but I would assume @lots0logs still wants to see them listed in e.g. the README.md

Has that happened? No. Does that mean the issue is no longer relevant just because the original submitter may not be actively reporting "yes, I still care about this"? I don't think so...

Admittedly, the best way to actually get these dependencies listed would be for @lots0logs to submit a PR.

**Comment by ItzSwirlz** [comment]
This can be closed now that we've ported to Meson
