### ISSUE TITLE
3.2.7 cinnamon --replace crash

### ISSUE THREAD

**Issue by chuinul** [linuxmint/Cinnamon#6371]
From sometime now (I couldn't say when it began), I experience a crash / restart in fallback mode of cinnamon when (left) clicking on some applet (especially ownCloud's one). Here is the backtrace I got:

```
Core was generated by `cinnamon --replace'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  gtk_socket_filter_func (gdk_xevent=0x7fff7c41afe0, event=0x55de602cb830, data=0x55de5d9cacb0) at /build/gtk+3.0-PCLr8A/gtk+3.0-3.18.9/./gtk/gtksocket.c:1385
1385	/build/gtk+3.0-PCLr8A/gtk+3.0-3.18.9/./gtk/gtksocket.c: Aucun fichier ou dossier de ce type.
[Current thread is 1 (Thread 0x7f5040f7eac0 (LWP 2236))]
(gdb) bt
#0  0x00007f503c48e5a0 in gtk_socket_filter_func (gdk_xevent=0x7fff7c41afe0, event=0x55de602cb830, data=0x55de5d9cacb0) at /build/gtk+3.0-PCLr8A/gtk+3.0-3.18.9/./gtk/gtksocket.c:1385
#1  0x00007f503be78d01 in gdk_event_apply_filters (xevent=xevent@entry=0x7fff7c41afe0, event=event@entry=0x55de602cb830, window=window@entry=0x7f50000038a0 [GdkX11Window])
    at /build/gtk+3.0-PCLr8A/gtk+3.0-3.18.9/./gdk/x11/gdkeventsource.c:81
#2  0x00007f503be78fdd in _gdk_x11_display_queue_events (xevent=0x7fff7c41afe0, event_source=0x55de5d9deab0) at /build/gtk+3.0-PCLr8A/gtk+3.0-3.18.9/./gdk/x11/gdkeventsource.c:207
#3  0x00007f503be78fdd in _gdk_x11_display_queue_events (display=0x55de5d9bf010 [GdkX11Display]) at /build/gtk+3.0-PCLr8A/gtk+3.0-3.18.9/./gdk/x11/gdkeventsource.c:343
#4  0x00007f503be4b0e9 in gdk_display_get_event (display=display@entry=0x55de5d9bf010 [GdkX11Display]) at /build/gtk+3.0-PCLr8A/gtk+3.0-3.18.9/./gdk/gdkdisplay.c:340
#5  0x00007f503be78d82 in gdk_event_source_dispatch (source=<optimized out>, callback=<optimized out>, user_data=<optimized out>) at /build/gtk+3.0-PCLr8A/gtk+3.0-3.18.9/./gdk/x11/gdkeventsource.c:365
#6  0x00007f503f57d197 in g_main_context_dispatch (context=0x55de5d9a1010) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:3154
#7  0x00007f503f57d197 in g_main_context_dispatch (context=context@entry=0x55de5d9a1010) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:3769
#8  0x00007f503f57d3f0 in g_main_context_iterate (context=0x55de5d9a1010, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:3840
#9  0x00007f503f57d712 in g_main_loop_run (loop=0x55de5d9a1150) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:4034
#10 0x00007f5040961938 in meta_run () at core/main.c:542
#11 0x000055de5b7f58c0 in main (argc=1, argv=0x7fff7c41b3d8) at main.c:329
```

The crash occurs only once per session. For an unknown reason, I can reproduce this only on my desktop. I have not that problem on my laptop, which runs Cinnamon 3.2.7 over Linux Mint 18.1 as well.

**Comment by chuinul** [comment]
I have not experienced this for some weeks now. I supposed it has been fixed somehow.
