### ISSUE TITLE
ValueError: Namespace AccountsService not available

### ISSUE THREAD

**Issue by hobarrera** [linuxmint/Cinnamon#6445]
When trying to run `cinnamon-screensaver`, I get the following error:

```
$ cinnamon-screensaver
Traceback (most recent call last):
  File "/usr/share/cinnamon-screensaver/cinnamon-screensaver-main.py", line 18, in <module>
    from service import ScreensaverService
  File "/usr/share/cinnamon-screensaver/service.py", line 9, in <module>
    from manager import ScreensaverManager
  File "/usr/share/cinnamon-screensaver/manager.py", line 10, in <module>
    from stage import Stage
  File "/usr/share/cinnamon-screensaver/stage.py", line 8, in <module>
    import singletons
  File "/usr/share/cinnamon-screensaver/singletons.py", line 19, in <module>
    from dbusdepot.accountsServiceClient import AccountsServiceClient as _AccountsServiceClient
  File "/usr/share/cinnamon-screensaver/dbusdepot/accountsServiceClient.py", line 4, in <module>
    gi.require_version('AccountsService', '1.0')
  File "/usr/lib/python3.6/site-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AccountsService not available
```

Not sure what other information can help here.

**Comment by leigh123linux** [comment]
First this isn't a cinnamon issue, it belongs

https://github.com/linuxmint/cinnamon-screensaver

Second, is AccountsService package installed?

Third, what distro are you using?, are you using their packages? (if so bug them instead!).

**Comment by hobarrera** [comment]
I'm using arch. And yeah, I'll open a bug for the Arch package instead, thanks.

**Comment by leigh123linux** [comment]
@hobarrera 

It's looking for /usr/lib*/girepository-1.0/AccountsService-1.0.typelib

Arch have forgot to list it as a dep

https://www.archlinux.org/packages/community/x86_64/cinnamon-screensaver/

**Comment by hobarrera** [comment]
Thanks. Installing `accountsservices` fixes it. I've [reported this](https://bugs.archlinux.org/task/53679) downstream.
