### ISSUE TITLE
cinnamon-settings - crash in applets and desklets modules

### ISSUE THREAD

**Issue by vladimir-didenko** [linuxmint/Cinnamon#6555]
I am using cinnamon 3.4 (but had the same problem with 3.2) and applets module of cinnamon-settings crashes every time in /usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py:1419

```Python
surface = Gdk.cairo_surface_create_from_pixbuf (img, self.window.get_scale_factor(), self.window.get_window())
```
Below is gdb backtrace
```
#0  0x00007ffff781a6d7 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#1  0x00007ffff782395c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#2  0x00007ffff781fa4c in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#3  0x00007ffff781fb7a in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#4  0x00007ffff782395c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#5  0x00007ffff781fa4c in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#6  0x00007ffff781fb7a in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#7  0x00007ffff782395c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#8  0x00007ffff781fa4c in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#9  0x00007ffff781fb7a in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#10 0x00007ffff781fb7a in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#11 0x00007ffff782395c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#12 0x00007ffff7799c4c in ?? () from /usr/lib64/libpython2.7.so.1.0
#13 0x00007ffff7768d93 in PyObject_Call () from /usr/lib64/libpython2.7.so.1.0
#14 0x00007ffff777a0d2 in ?? () from /usr/lib64/libpython2.7.so.1.0
#15 0x00007ffff7768d93 in PyObject_Call () from /usr/lib64/libpython2.7.so.1.0
#16 0x00007ffff7819317 in PyEval_CallObjectWithKeywords () from /usr/lib64/libpython2.7.so.1.0
#17 0x00007ffff1387faa in pygi_signal_closure_marshal (closure=0x1022890, return_value=0x7fffffffd680, n_param_values=2, param_values=0x7fffffffd730, invocation_hint=<optimized out>, marshal_data=<optimized out>)
    at pygi-signal-closure.c:196
#18 0x00007ffff0ee7575 in g_closure_invoke (closure=0x1022890, return_value=return_value@entry=0x7fffffffd680, n_param_values=2, param_values=param_values@entry=0x7fffffffd730, invocation_hint=invocation_hint@entry=0x7fffffffd6d0)
    at gclosure.c:804
#19 0x00007ffff0ef8ea2 in signal_emit_unlocked_R (node=<optimized out>, detail=detail@entry=0, instance=instance@entry=0xeea7a0, emission_return=emission_return@entry=0x7fffffffd810, 
    instance_and_params=instance_and_params@entry=0x7fffffffd730) at gsignal.c:3635
#20 0x00007ffff0f01590 in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffd8d8) at gsignal.c:3401
#21 0x00007ffff0f01f12 in g_signal_emit (instance=instance@entry=0xeea7a0, signal_id=<optimized out>, detail=detail@entry=0) at gsignal.c:3447
#22 0x00007fffe903e52c in gtk_widget_event_internal (widget=0xeea7a0, event=0x14d5a90) at gtkwidget.c:7724
#23 0x00007fffe8ef81de in propagate_event_up (topmost=<optimized out>, event=<optimized out>, widget=0xeea7a0) at gtkmain.c:2568
#24 propagate_event (widget=<optimized out>, event=0x14d5a90, captured=<optimized out>, topmost=0x0) at gtkmain.c:2670
#25 0x00007fffe8efa1ed in gtk_main_do_event (event=0x14d5a90) at gtkmain.c:1901
#26 0x00007fffef33da05 in _gdk_event_emit (event=event@entry=0x14d5a90) at gdkevents.c:73
#27 0x00007fffef36dc22 in gdk_event_source_dispatch (source=<optimized out>, callback=<optimized out>, user_data=<optimized out>) at gdkeventsource.c:367
#28 0x00007ffff5e59917 in g_main_dispatch (context=0x8e42d0) at gmain.c:3234
#29 g_main_context_dispatch (context=context@entry=0x8e42d0) at gmain.c:3887
#30 0x00007ffff5e59b48 in g_main_context_iterate (context=0x8e42d0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3960
#31 0x00007ffff5e59e62 in g_main_loop_run (loop=0xc3d870) at gmain.c:4156
#32 0x00007fffe8ef93c5 in gtk_main () at gtkmain.c:1312
#33 0x00007ffff0cd3f80 in ffi_call_unix64 () at ../src/x86/unix64.S:76
#34 0x00007ffff0cd39eb in ffi_call (cif=cif@entry=0xffb518, fn=<optimized out>, rvalue=rvalue@entry=0x7fffffffdd50, avalue=<optimized out>) at ../src/x86/ffi64.c:525
#35 0x00007ffff1388d0c in pygi_invoke_c_callable (function_cache=0xffb470, state=<optimized out>, py_args=<optimized out>, py_kwargs=<optimized out>) at pygi-invoke.c:679
#36 0x00007ffff138a7da in pygi_function_cache_invoke (function_cache=<optimized out>, py_args=<optimized out>, py_kwargs=<optimized out>) at pygi-cache.c:861
#37 0x00007ffff7768d93 in PyObject_Call () from /usr/lib64/libpython2.7.so.1.0
#38 0x00007ffff781eefd in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#39 0x00007ffff782395c in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#40 0x00007ffff7823a59 in PyEval_EvalCode () from /usr/lib64/libpython2.7.so.1.0
#41 0x00007ffff78489da in PyRun_FileExFlags () from /usr/lib64/libpython2.7.so.1.0
#42 0x00007ffff7849db5 in PyRun_SimpleFileExFlags () from /usr/lib64/libpython2.7.so.1.0
#43 0x00007ffff786038c in Py_Main () from /usr/lib64/libpython2.7.so.1.0
#44 0x00007ffff738f661 in __libc_start_main (main=0x400620 <main>, argc=2, argv=0x7fffffffe308, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe2f8) at ../csu/libc-start.c:295
#45 0x000000000040065a in _start ()
```
I will appreciate if someone will help with debugging.

**Comment by vladimir-didenko** [comment]
One addition - issue only could be reproduced in Gnome 3.24 environment. The same package works fine with Gnome 3.22.

**Comment by leigh123linux** [comment]
I don't see the issue here using python3-gobject-3.24.1 with gtk3-3.22.15

**Comment by mtwebster** [comment]
Is this a segfault?  Is there any python portion of the log or is this from a reporting tool?  Can you run cinnamon-settings from a terminal to show if there is any other relevant output?

**Comment by vladimir-didenko** [comment]
@mtwebster  Yes, it is segfault. Backtrace output is actually output of gdb "bt" command.

Below is output from terminal
```
$ cinnamon-settings

** (cinnamon-settings.py:6153): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-MB5O3Jyukf: Connection refused
Loading Applets module
Segmentation fault
```

**Comment by vladimir-didenko** [comment]
Actually it was bug in python gobject build. So there is no bug in cinnamon-settings. Closing this issue.
