### ISSUE TITLE
Panel settings does not load (after upgrade to Mint 18.2)

### ISSUE THREAD

**Issue by emiliedancer** [linuxmint/Cinnamon#6692]
```
 * Cinnamon version 3.4.4
 * Mint 18.2
 * NVidia GeForce GTX 765M (nvidia-375, intel profile)
 * 64 bit
 ```

**Issue**
After updating to Linux Mint 18.2, the panel settings menu will not open.  This is true when trying to open it from Cinnamon Settings or right-clicking on the panel and choosing panel settings.

**Steps to reproduce**
Try to open panel settings.  Expect that the settings menu opens, instead nothing happens.

**Other information**
Terminal output from cinnamon-settings when clicking on panel-settings: 

```
Loading Panel module
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 554, in button_press
    self.side_view_nav(widget, None, category)

  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 114, in side_view_nav
    self.go_to_sidepage(cat, filtered_path)

  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 127, in go_to_sidepage
    sidePage.build()

  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 123, in build
    self.module.on_module_selected()

  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 141, in on_module_selected
    self.on_panel_list_changed()

  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 220, in on_panel_list_changed
    panel_page = PanelSettingsPage(panel_id, self.settings, position)

  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 49, in __init__
    widget = PanelSpinButton(_("Hide delay"), "org.cinnamon", "panels-hide-delay", self.panel_id, _("milliseconds"), 0, 2000, 50, 200)#, dep_key="org.cinnamon/panels-autohide")

  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 370, in __init__
    self.connect_to_settings(schema, key)

  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 306, in connect_to_settings
    self.on_setting_changed()

  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 386, in on_setting_changed
    self.content_widget.set_value(value)

TypeError: Argument 1 does not allow None as a value
```

**Comment by collinss** [comment]
Please run `gsettings get org.cinnamon panels-hide-delay` in terminal and post the output here.

**Comment by emiliedancer** [comment]
```
 $ gsettings get org.cinnamon panels-hide-delay
['1:0']
```

**Comment by collinss** [comment]
How many panels do you have?

**Comment by emiliedancer** [comment]
I have two, top and bottom.

**Comment by collinss** [comment]
Ok, try `gsettings set org.cinnamon panels-hide-delay "['1:0','2:0']"` and see if that fixes it.

**Comment by emiliedancer** [comment]
Yes, thank you, that fixed it!

I figured it had to be something to do with the hide-delay but did not know how to adjust it.

**Comment by collinss** [comment]
You're welcome. I'm not sure how that ended up that way, but we should probably add some checks to make sure that doesn't crash in the future.

**Comment by emiliedancer** [comment]
I upgraded from 17.3 so I am not sure which step along the way did it. Is it a new parameter in Cinnamon?  At some point in the upgrade it must just have not took multiple panels into consideration.

Sorry I cannot be more helpful for patching.

**Comment by collinss** [comment]
That's OK, I was the one who wrote the code in question (that and several other changes to the handling of panels by other devs were made in the most recent release , so it could have been any number of things that caused your faulty value). I was saying it more as a mental note to self than anything.
