### ISSUE TITLE
Power manager missing

### ISSUE THREAD

**Issue by hd-scania** [linuxmint/Cinnamon#6728]
```
 * Cinnamon version: 3.4.4
 * Distribution: Tumbleweed
 * Graphics hardware AND driver used: Intel LVDS1
 * x64 architecture
 ```

**Issue**

```
hd_scania@kiwi:~> cinnamon-settings
Loading Power module
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 552, in button_press
    self.side_view_nav(widget, None, category)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 112, in side_view_nav
    self.go_to_sidepage(cat, filtered_path)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 125, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 123, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_power.py", line 115, in on_module_selected
    device_types = [x[UP_TYPE] for x in self.csd_power_proxy.GetDevices()]
  File "/usr/lib64/python2.7/site-packages/gi/overrides/Gio.py", line 172, in __call__
    None)
GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.cinnamon.SettingsDaemon.Power was not provided by any .service files (2)
hd_scania@kiwi:~>
```
**Steps to reproduce**
```
CC-BY SA 4.0
```
**Expected behaviour**
Needs to dim the screen and lock my session and without power manager they could not be done
**Other information**
LXQt and Xfce are my alternative desktops also installed in Tumbleweed

**Comment by raphael141714** [comment]
Same problem on cinnamon 3.2.7 on debian sid with linux 4.11.0.2 rt.
Seems to be related to cinnamon-settings-daemon, as running `cinamon-settings-daemon` resolves the problem.
I don't want to use a cron tab as it seems quite dumb for that type of problem.

**Comment by jkdf2** [comment]
More details here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=871460

**Comment by leigh123linux** [comment]
@jkdf2 That was fixed

https://github.com/linuxmint/cinnamon-session/commit/402355658665f5d544452e39902213c1d9027895

@hd-scania If the issue still exists file it against your distro's bug tracker or cinnamon-settings-daemon.
