### ISSUE TITLE
[[Bug]] Panel Settings Does Not Load (after upgrade to Mint 18.3 from 18)

### ISSUE THREAD

**Issue by WammKD** [linuxmint/cinnamon#7100]
```
 * Cinnamon version                   : 3.6.6
 * Distribution                       : Mint 18.3
 * Graphics hardware *and* driver used: VGA compatible controller [0300]: Intel Corporation Sky Lake Integrated Graphics [8086:1916] *and* Intel Open Source Technology Center (0x8086) (I believe…)
 * 32 or 64 bit                       : 64-bit
 ```

**Issue**
After upgrading to Linux Mint 18.3 from 18, the panel settings menu won't open; clicking on the option from the System Settings window does nothing except highlighting the panel option until clicking elsewhere and trying to launch it through, say, the menu doesn't nothing.

**Steps to reproduce**
Just try to open the Panel Settings in any means possible.

**Expected behaviour**
Panel settings should show.

**Other information**
Terminal output of `cinnamon-settings panel` are:

```Loading Panel module
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 610, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 322, in __init__
    self.go_to_sidepage(cat, path)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 130, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 123, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 143, in on_module_selected
    self.on_panel_list_changed()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 222, in on_panel_list_changed
    panel_page = PanelSettingsPage(panel_id, self.settings, position)
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 49, in __init__
    section.add_reveal_row(widget, "org.cinnamon", "panels-autohide", check_func=can_show)
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 428, in add_reveal_row
    revealer = SettingsRevealer(schema, key, values, check_func)
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 322, in __init__
    self.on_settings_changed(self.settings, key)
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 333, in on_settings_changed
    self.set_reveal_child(self.check_func(value, self.values))
TypeError: Argument 1 does not allow None as a value
```

I did find #6692; I have one panel, on the bottom (and `tint2` but I assume that doesn't really affect anything, here), and running `gsettings get org.cinnamon panels-hide-delay` outputs `['1:0', '2:0']`.

I have no idea what this means but I tried setting it to `['1:0']` and `['2:0']`, restarting Cinnamon each time, and it didn't make a difference.

**Comment by WammKD** [comment]
Based off of #6692, I guess @collinss wrote the respective code so tagging; sorry if that's not helpful in any way.

**Comment by icarter09** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (4.2). 

https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/
