### ISSUE TITLE
IF  HAVE 2 panels: cinnamon-setttings panel crashes

### ISSUE THREAD

**Issue by rik-shaw** [linuxmint/Cinnamon#7212]
```
 * Cinnamon version (cinnamon --version)
3.6.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Ubuntu 16.04
 * Graphics hardware *and* driver used
Intel
 * 32 or 64 bit
64 bit
 ```

**Issue**
If I have 2 panels (a left one and a top one), then attempting to bring up cinnamon-settings panel crashes.  If I remove 1 panel, then it will start correctly.

**Other information**
Here is the output from a terminal:
```
~$ cinnamon-settings panel
Loading Panel module
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 610, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 322, in __init__
    self.go_to_sidepage(cat, path)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 130, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 123, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 143, in on_module_selected
    self.on_panel_list_changed()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 222, in on_panel_list_changed
    panel_page = PanelSettingsPage(panel_id, self.settings, position)
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 51, in __init__
    widget = PanelSpinButton(_("Hide delay"), "org.cinnamon", "panels-hide-delay", self.panel_id, _("milliseconds"), 0, 2000, 50, 200)#, dep_key="org.cinnamon/panels-autohide")
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 372, in __init__
    self.connect_to_settings(schema, key)
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 308, in connect_to_settings
    self.on_setting_changed()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 388, in on_setting_changed
    self.content_widget.set_value(value)
TypeError: Argument 1 does not allow None as a value
```

**Comment by rik-shaw** [comment]
FALSE ALERT: I had somehow messed up a dconf value and the panel-hide-delay did not reference 2 panels but just one.  It is my guess that this confusion (having 2 panels but only one panel referenced in the panle-hide-delay) caused the issue.

**Comment by rik-shaw** [comment]
I am going to re-open this issue.  I am pretty certain the problem is only with 'org.cinnamon panels-hide-delay'.  When it is manually set to reference only 1 panel when 2 are active, it will cause the above crash when opening 'cinnamon-settings panel'.  The reason I am leaving the bug open is because other settings such as 'org.cinnamon panels-show-delay' automatically get updated to add the second panel setting IF they are manually set by the user to only reference one panel.  So somehow panels-hide-delay should use that same logic in order to harden 'cinnamon-settings panel'
