### ISSUE TITLE
xlet-settings does not works with some applets

### ISSUE THREAD

**Issue by cranes-bill** [linuxmint/Cinnamon#7343]
```
Cinnamon 3.6.7
64 bit
 ```

**Issue**
Settings for some applets do not work

**Steps to reproduce**
Right click on `workspace-switcher@cinnamon.org` or `weather@mockturtl` applet
Choose „_Configure_“

**Expected behaviour**
Showing settings window.

**Other information**
**_Full command line:_**
`/usr/bin/python2 /usr/share/cinnamon/cinnamon-settings/xlet-settings.py applet applet@id [0-9]{2}
`

**_It generates the following error:_**
```
Gtk.py:943:__init__:TypeError: Item 0: Must be gobject.GType, not type

Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 434, in <module>
    window = MainWindow(xlet_type, *sys.argv[2:])
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 91, in __init__
    self.load_instances()
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 275, in load_instances
    self.build_from_order(settings_map, info, instance_box, first_key)
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 338, in build_from_order
    widget = globals()[XLET_SETTINGS_WIDGETS[settings_type]](key, info["settings"], item)
  File "/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py", line 246, in __init__
    super(NewClass, self).__init__(**kwargs)
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 771, in __init__
    self.set_options(options)
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 797, in set_options
    self.model = Gtk.ListStore(var_type, str)
  File "/usr/lib64/python2.7/site-packages/gi/overrides/Gtk.py", line 943, in __init__
    self.set_column_types(column_types)
TypeError: Item 0: Must be gobject.GType, not type

Local variables in innermost frame:
column_types: (<type 'unicode'>, <type 'str'>)
self: <Gtk.ListStore object at 0x2868050 (GtkListStore at 0x2c842c0)>
```

**Comment by NikoKrause** [comment]
I reproduced your error message.
You need to use `python3` not `python2`

**Comment by cranes-bill** [comment]
Well, thanks!
