### ISSUE TITLE
Fairly common crash when opening Jetbrains Rider

### ISSUE THREAD

**Issue by Sejsel** [linuxmint/cinnamon#7367]
```
Cinnamon 3.6.7
Arch
RX 580 with AMDGPU
64bit
 ```

**Issue**
Sometimes cinnamon crashes when opening Jetbrains Rider, immediately before the solution selection window appears. A cinnamon restart is offered and after selecting "Yes" everything works fine (no crash loop).

**Steps to reproduce**
Repeatedly try opening Jetbrains Rider (maybe happens with other Jetbrains IDEs too). Any recent version will trigger this, maybe even very old ones (I think it has been happening ever since the first EAP versions).

**Expected behaviour**
No crash

**Other information**
From journalctl log:
```
mar 17 22:40:20 serval kernel: cinnamon[1213]: segfault at c0 ip 00007fba27a3d870 sp 00007fff58d0c4c8 error 4 in libgio-2.0.so.0.5400.3[7fba27943000+1a2000]
mar 17 22:40:20 serval systemd[1]: Started Process Core Dump (PID 24302/UID 0).
mar 17 22:40:21 serval systemd-coredump[24305]: Process 1213 (cinnamon) of user 1000 dumped core.
                                                 
                                                 Stack trace of thread 1213:
                                                 #0  0x00007fba27a3d870 g_desktop_app_info_get_is_hidden (libgio-2.0.so.0)
                                                 #1  0x00007fba2692837c n/a (libcinnamon-menu-3.so.0)
                                                 #2  0x00007fba26928202 n/a (libcinnamon-menu-3.so.0)
                                                 #3  0x00007fba2692b77c gmenu_tree_load_sync (libcinnamon-menu-3.so.0)
                                                 #4  0x00007fba28ad86b9 n/a (libcinnamon.so)
                                                 #5  0x00007fba276fdc5d g_closure_invoke (libgobject-2.0.so.0)
                                                 #6  0x00007fba27711b50 n/a (libgobject-2.0.so.0)
                                                 #7  0x00007fba2771a806 g_signal_emit_valist (libgobject-2.0.so.0)
                                                 #8  0x00007fba2771b240 g_signal_emit (libgobject-2.0.so.0)
                                                 #9  0x00007fba2692c6e8 n/a (libcinnamon-menu-3.so.0)
                                                 #10 0x00007fba27423ca6 g_main_context_dispatch (libglib-2.0.so.0)
                                                 #11 0x00007fba27424081 n/a (libglib-2.0.so.0)
                                                 #12 0x00007fba274243b2 g_main_loop_run (libglib-2.0.so.0)
                                                 #13 0x00007fba2883b91a meta_run (libmuffin.so.0)
                                                 #14 0x000055a57c13b733 n/a (cinnamon)
                                                 #15 0x00007fba26e24f4a __libc_start_main (libc.so.6)
                                                 #16 0x000055a57c13b83a n/a (cinnamon)
```

**Comment by leigh123linux** [comment]
Here's a complete backtrace forwarded from https://bugzilla.redhat.com/show_bug.cgi?id=1515298

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `cinnamon --replace'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  g_desktop_app_info_get_is_hidden (info=0x0) at gdesktopappinfo.c:2027
[Current thread is 1 (Thread 0x7fdb6bf77f80 (LWP 5946))]

Thread 1 (Thread 0x7fdb6bf77f80 (LWP 5946)):
#0  g_desktop_app_info_get_is_hidden (info=0x0) at gdesktopappinfo.c:2027
No locals.
#1  0x00007fdb6b3a8b01 in desktop_entry_get_hidden (entry=<optimized out>) at desktop-entries.c:616
No locals.
#2  0x00007fdb6b3ab76b in process_layout (tree=tree@entry=0x564fe156a250, parent=parent@entry=0x564fe4abf4f0, layout=layout@entry=0x564fe15bf960, allocated=allocated@entry=0x564fe18e4370) at gmenu-tree.c:3442
        entry = 0x564fe4ecfed0
        next = 0x564fe3e40070
        delete = 0
        layout_iter = <optimized out>
        entry_pool = 0x564fe18c89b0
        entries = 0x564fe4e5ca80
        allocated_set = 0x564fe1c9a2a0
        excluded_set = <optimized out>
        deleted = 0
        only_unallocated = <optimized out>
        tmp = 0x564fe3e40050
#3  0x00007fdb6b3ab645 in process_layout (tree=tree@entry=0x564fe156a250, parent=parent@entry=0x0, layout=<optimized out>, allocated=allocated@entry=0x564fe18e4370) at gmenu-tree.c:3218
        child_dir = <optimized out>
        layout_iter = 0x564fe15bf960
        entry_pool = 0x564fe18c89b0
        entries = 0x564fe18de1e0
        allocated_set = 0x564fe18c50f0
        excluded_set = 0x0
        deleted = 0
        only_unallocated = 0
        tmp = <optimized out>
#4  0x00007fdb6b3ae02c in gmenu_tree_build_from_layout (error=0x7fffe6410d48, tree=0x564fe156a250) at gmenu-tree.c:4519
        allocated = 0x564fe18e4370
#5  gmenu_tree_load_sync (tree=0x564fe156a250, error=error@entry=0x7fffe6410e08) at gmenu-tree.c:745
        local_error = 0x0
#6  0x00007fdb6bb6d413 in on_apps_tree_changed_cb (tree=<optimized out>, user_data=0x564fe15b54a0) at cinnamon-app-system.c:354
        self = 0x564fe15b54a0
        error = 0x0
        iter = {dummy1 = 0x564fe45f1560, dummy2 = 0x7fdb638cadad <g_slice_alloc+29>, dummy3 = 0x0, dummy4 = -1748936704, dummy5 = 2076294190, dummy6 = 0x7fffe6411200}
        key = 0x7fffe6410fa0
        value = 0x564fe0fcd560
        removed_apps = 0x0
        removed_node = <optimized out>
        __func__ = "on_apps_tree_changed_cb"
#7  0x00007fdb63b8673d in g_closure_invoke (closure=0x564fe15b8dd0, return_value=0x0, n_param_values=1, param_values=0x7fffe6411050, invocation_hint=0x7fffe6410fd0) at gclosure.c:804
        marshal = 0x7fdb63b88640 <g_cclosure_marshal_VOID__VOID>
        marshal_data = 0x0
        in_marshal = 0
        real_closure = 0x564fe15b8db0
        __func__ = "g_closure_invoke"
#8  0x00007fdb63b994de in signal_emit_unlocked_R (node=node@entry=0x564fe16f6390, detail=detail@entry=0, instance=instance@entry=0x564fe156a250, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fffe6411050) at gsignal.c:3635
        tmp = <optimized out>
        handler = 0x564fe1517680
        accumulator = 0x0
        emission = {next = 0x0, instance = 0x564fe156a250, ihint = {signal_id = 316, detail = 0, run_type = G_SIGNAL_RUN_FIRST}, state = EMISSION_RUN, chain_type = 4}
        class_closure = 0x0
        handler_list = 0x564fe1517680
        return_accu = 0x0
        accu = {g_type = 0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        signal_id = 316
        max_sequential_handler_number = 82825
        return_value_altered = 0
#9  0x00007fdb63ba1d05 in g_signal_emit_valist (instance=0x564fe156a250, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7fffe6411220) at gsignal.c:3391
        instance_and_params = 0x7fffe6411050
        signal_return_type = 4
        param_values = 0x7fffe6411068
        node = <optimized out>
        i = <optimized out>
        n_params = 0
        __func__ = "g_signal_emit_valist"
#10 0x00007fdb63ba266f in g_signal_emit (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at gsignal.c:3447
        var_args = {{gp_offset = 24, fp_offset = 48, overflow_arg_area = 0x7fffe6411300, reg_save_area = 0x7fffe6411240}}
#11 0x00007fdb6b3ae6e0 in menu_layout_invoke_monitors (nr=nr@entry=0x564fe15bd1a0) at menu-layout.c:154
        monitor = <optimized out>
        next = 0x0
        tmp = <optimized out>
#12 0x00007fdb638aa597 in g_idle_dispatch (source=0x564fe4ea6380, callback=0x7fdb6b3ae6b0 <menu_layout_invoke_monitors>, user_data=0x564fe15bd1a0) at gmain.c:5504
        again = <optimized out>
#13 0x00007fdb638adbb7 in g_main_dispatch (context=0x564fe0e29a40) at gmain.c:3148
        dispatch = 0x7fdb638aa580 <g_idle_dispatch>
        prev_source = 0x0
        was_in_call = 0
        user_data = 0x564fe15bd1a0
        callback = 0x7fdb6b3ae6b0 <menu_layout_invoke_monitors>
        cb_funcs = 0x7fdb63b75280 <g_source_callback_funcs>
        cb_data = 0x564fe3d4e380
        need_destroy = <optimized out>
        source = 0x564fe4ea6380
        current = 0x564fe0e70830
        i = 0
#14 g_main_context_dispatch (context=context@entry=0x564fe0e29a40) at gmain.c:3813
No locals.
#15 0x00007fdb638adf60 in g_main_context_iterate (context=0x564fe0e29a40, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3886
        max_priority = 200
        timeout = 0
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = 11
        fds = 0x564fe4ac3c80
#16 0x00007fdb638ae272 in g_main_loop_run (loop=0x564fe0e2a790) at gmain.c:4082
        __func__ = "g_main_loop_run"
#17 0x00007fdb6b8cce2c in meta_run () at core/main.c:542
        log_domains = {0x0, 0x7fdb6b9179c4 "muffin", 0x7fdb6b916af4 "Gtk", 0x7fdb6b916af8 "Gdk", 0x7fdb6b916afc "GLib", 0x7fdb6b916b01 "Pango", 0x7fdb6b916b07 "GLib-GObject", 0x7fdb6b916b14 "GThread"}
        i = <optimized out>
#18 0x0000564fe06abcf0 in main (argc=<optimized out>, argv=<optimized out>) at main.c:330
        ctx = <optimized out>
        error = 0x0
        ecode = <optimized out>
```

**Comment by itzexor** [comment]
I can't reproduce this with Rider evaluation or PyCharm on Arch's Cinnamon packages or on git packages

**Comment by Clovis-Portron** [comment]
I have the same problem. I've installed Rider throught the Jetbrain's toolbox app.

OS: Debian 9.4 (x86-64)
Cinnamon: 3.2.7
Linux kernel: 4.9.0-6-amd64

**Comment by Sejsel** [comment]
I have also installed Rider through the Jetbrains' toolbox app and added the desktop file through Rider's menu option to add one.

The .desktop file looks like this:
```
[Desktop Entry]
Version=1.0
Type=Application
Name=Rider
Icon=/home/sejsel/programming/ides/jetbrains/apps/Rider/ch-0/181.4952.142/.icon.svg
Exec="/home/sejsel/programming/ides/jetbrains/apps/Rider/ch-0/181.4952.142/bin/rider.sh" %f
Comment=A cross-platform .NET IDE based on the IntelliJ platform and ReSharper
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-rider
```

**Comment by icarter09** [comment]
@eli-schwartz

**Comment by Sejsel** [comment]
I haven't seen the crash in a long while, it might be fixed already. I keep up with cinnamon updates, and I can't recall it happening since around cinnamon 4 release.

**Comment by icarter09** [comment]
@Sejsel thanks for the update.
