### ISSUE TITLE
Cinnamon crashes upon login

### ISSUE THREAD

**Issue by gothicVI** [linuxmint/Cinnamon#7430]
```
 * Cinnamon 3.6.7
 * Mint 18.3
 * GT218M [GeForce 310M], driver nvidia-340 340.106-0ubuntu0+gpu16.04.2
 * 64 bit
 ```

**Issue**

After installing above driver cinnamon crashes after each login.

**Steps to reproduce**

reboot and login

**Expected behavior**

no crash

**Other information**

```
===================================================================
 GDB Log                                                           
===================================================================
[New LWP 7790]
[New LWP 7798]
[New LWP 7799]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `cinnamon --replace --replace'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __strstr_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strstr-sse2-unaligned.S:40
40	../sysdeps/x86_64/multiarch/strstr-sse2-unaligned.S: No such file or directory.
[Current thread is 1 (Thread 0x7f7cbb0baac0 (LWP 7790))]

===================================================================
 GDB Backtrace                                                     
===================================================================
[New LWP 7790]
[New LWP 7798]
[New LWP 7799]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `cinnamon --replace --replace'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __strstr_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strstr-sse2-unaligned.S:40
40	../sysdeps/x86_64/multiarch/strstr-sse2-unaligned.S: No such file or directory.
[Current thread is 1 (Thread 0x7f7cbb0baac0 (LWP 7790))]
#0  0x00007f7cb913d0bd in __strstr_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strstr-sse2-unaligned.S:40
#1  0x00007f7cbaaa874d in meta_init () at core/main.c:461
#2  0x0000563f5e246668 in main (argc=1, argv=0x7ffefa266c98) at main.c:291

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
[New LWP 7790]
[New LWP 7798]
[New LWP 7799]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `cinnamon --replace --replace'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __strstr_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strstr-sse2-unaligned.S:40
40	../sysdeps/x86_64/multiarch/strstr-sse2-unaligned.S: No such file or directory.
[Current thread is 1 (Thread 0x7f7cbb0baac0 (LWP 7790))]

Thread 3 (Thread 0x7f7ca395e700 (LWP 7799)):
#0  0x00007f7cb918e74d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f7cb96c438c in g_main_context_iterate (priority=2147483647, n_fds=2, fds=0x7f7c940010c0, timeout=<optimized out>, context=0x563f60324300) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:4135
        poll_func = 0x7f7cb96d3280 <g_poll>
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 2
        allocated_nfds = 2
        fds = 0x7f7c940010c0
#2  0x00007f7cb96c438c in g_main_context_iterate (context=0x563f60324300, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:3835
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 2
        allocated_nfds = 2
        fds = 0x7f7c940010c0
#3  0x00007f7cb96c4712 in g_main_loop_run (loop=0x563f604bbda0) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:4034
        __func__ = "g_main_loop_run"
#4  0x00007f7cb9cc29d6 in gdbus_shared_thread_func (user_data=0x563f603242d0) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./gio/gdbusprivate.c:246
        data = 0x563f603242d0
#5  0x00007f7cb96eabb5 in g_thread_proxy (data=0x563f602afd40) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gthread.c:780
        thread = 0x563f602afd40
#6  0x00007f7cb94646ba in start_thread (arg=0x7f7ca395e700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7f7ca395e700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140173297182464, 2342989141768205207, 0, 140733095237743, 140173297183168, 94830196835024, -2415408113404284009, -2415465720821648489}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#7  0x00007f7cb919a41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7f7ca415f700 (LWP 7798)):
#0  0x00007f7cb918e74d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f7cb96c438c in g_main_context_iterate (priority=2147483647, n_fds=1, fds=0x7f7c9c0008e0, timeout=<optimized out>, context=0x563f60251370) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:4135
        poll_func = 0x7f7cb96d3280 <g_poll>
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 1
        allocated_nfds = 1
        fds = 0x7f7c9c0008e0
#2  0x00007f7cb96c438c in g_main_context_iterate (context=context@entry=0x563f60251370, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:3835
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 1
        allocated_nfds = 1
        fds = 0x7f7c9c0008e0
#3  0x00007f7cb96c449c in g_main_context_iteration (context=0x563f60251370, may_block=may_block@entry=1) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:3901
        retval = <optimized out>
#4  0x00007f7cb96c44d9 in glib_worker_main (data=<optimized out>) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:5672
#5  0x00007f7cb96eabb5 in g_thread_proxy (data=0x563f602afcf0) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gthread.c:780
        thread = 0x563f602afcf0
#6  0x00007f7cb94646ba in start_thread (arg=0x7f7ca415f700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7f7ca415f700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140173305575168, 2342989141768205207, 0, 140733095237391, 140173305575872, 0, -2415424606615571561, -2415465720821648489}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#7  0x00007f7cb919a41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7f7cbb0baac0 (LWP 7790)):
#0  0x00007f7cb913d0bd in __strstr_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strstr-sse2-unaligned.S:40
#1  0x00007f7cbaaa874d in meta_init () at core/main.c:461
        act = {__sigaction_handler = {sa_handler = 0x7f7cbaaa81c0 <sigterm_handler>, sa_sigaction = 0x7f7cbaaa81c0 <sigterm_handler>}, sa_mask = {__val = {0 <repeats 16 times>}}, sa_flags = 0, sa_restorer = 0xfffffffa}
        empty_mask = {__val = {0 <repeats 16 times>}}
        channel = <optimized out>
        renderer = 0x0
#2  0x0000563f5e246668 in main (argc=1, argv=0x7ffefa266c98) at main.c:291
        ctx = 0x563f602a5430
        error = 0x0
        ecode = <optimized out>
#0  0x00007f7cb913d0bd in __strstr_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strstr-sse2-unaligned.S:40
#1  0x00007f7cbaaa874d in meta_init () at core/main.c:461
#2  0x0000563f5e246668 in main (argc=1, argv=0x7ffefa266c98) at main.c:291


-------------------------------------------------------------------------------------------------------------------------------------------
```

see attached crash.tar.gz:
[crash.tar.gz](https://github.com/linuxmint/Cinnamon/files/1869277/crash.tar.gz)

**Comment by leigh123linux** [comment]
File your report against nvidia-340 340.106-0ubuntu0+gpu16.04.2
