### ISSUE TITLE
[Bug] Unable to add autostart programs

### ISSUE THREAD

**Issue by ManIVIctorious** [linuxmint/Cinnamon#7539]
I'm not completely sure if this doesn't belong to cinnamon-settings-daemon, so please tell me if i should file it against an other repository...

**Issue**
On my two installations of Arch Linux with the cinnamon desktop I am not able to add new entries via the autostart settings.

**Further information**
By launching cinnamon-settings in the terminal and trying to add a new entry I get the following error message:

```
Using pam module (python3-pampy)
Loading Startup Applications module
Failed to load /home/manuel/.config/autostart/Geary.desktop
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_startup.py", line 545, in on_add_custom
    key = get_appname(app)
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_startup.py", line 31, in get_appname
    basename = os.path.basename(filename)
  File "/usr/lib/python3.6/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not AutostartApp
```

**System information**

```
 * Distribution - Arch 64bit
  Cinnamon version (pacman -Qs cinnamon | grep ^local)
    local/cinnamon 3.8.1-1
    local/cinnamon-control-center 3.8.0-1
    local/cinnamon-desktop 3.8.0-1
    local/cinnamon-menus 3.8.0-1
    local/cinnamon-screensaver 3.8.0-1
    local/cinnamon-session 3.8.1-1
    local/cinnamon-settings-daemon 3.8.0-1
    local/cinnamon-translations 3.8.0-1
    local/cjs 3.8.0-1
    local/muffin 3.8.0-1
    local/nemo 3.8.1-1
```

**Comment by leigh123linux** [comment]
Same issue reported here https://bugzilla.redhat.com/show_bug.cgi?id=1574550

**Comment by clefebvre** [comment]
https://github.com/linuxmint/Cinnamon/commit/53a32206662d0fd31a46bab16c4e9d50df6ea808

**Comment by ManIVIctorious** [comment]
Thanks for the quick response
