### ISSUE TITLE
Power Managment Breaks Suddenly

### ISSUE THREAD

**Issue by vladipus** [linuxmint/cinnamon#7851]
* Cinnamon version (cinnamon --version)
Cinnamon 3.8.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 19
 * Graphics hardware *and* driver used
Dell Inspiron
 * 32 or 64 bit
64 bit
 * When running `/usr/bin/python3 /usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py power`, I get:
    ```
Using PAM module (python3-pam)
Loading Power module
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 607, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 319, in __init__
    self.go_to_sidepage(cat, path)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 132, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 123, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_power.py", line 118, in on_module_selected
    device_types = [x[UP_TYPE] for x in self.csd_power_proxy.GetDevices()]
  File "/usr/lib/python3/dist-packages/gi/overrides/Gio.py", line 191, in __call__
    None)
GLib.Error: g-io-error-quark: Timeout was reached (24)
    ```

**Issue**
Power management, monitor/keyboard backlight no longer work.

**Steps to reproduce**
Not sure what causes this issue.

**Comment by icarter09** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (4.2). 

https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/
