### ISSUE TITLE
The panel settings are not displayed.

### ISSUE THREAD

**Issue by claudiux** [linuxmint/Cinnamon#7976]
```
 * Cinnamon version (cinnamon --version)
Cinnamon 3.8.9
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 19
 * Graphics hardware *and* driver used
           Card-1: Intel HD Graphics 5500 bus-ID: 00:02.0 chip-ID: 8086:1616
           Card-2: NVIDIA GK208M [GeForce 920M] bus-ID: 04:00.0 chip-ID: 10de:1299
           Display Server: x11 (X.Org 1.19.6 ) driver: intel Resolution: 1366x768@60.00hz
           OpenGL: renderer: Mesa DRI Intel HD Graphics 5500 (Broadwell GT2)
           version: 4.5 Mesa 18.0.5 (compat-v: 3.0) Direct Render: Yes
Driver:
video                  45056  2 asus_wmi,i915
 * 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
No message about this issue.
 ```

**Issue**
The Panel Settings window does not open.

**Steps to reproduce**
Right-click on a panel (I have 3 panels: top, bottom and right) and select Panel Settings. Nothing appeared. No windows open.

**Expected behaviour**
Displaying of Panel Settings window.

**Other information**
I have upgraded Linux Mint with mintupgrade, from 17 to 18, then from 18 to 19.

**Comment by smurphos** [comment]
What happens if you launch panel settings from the menu?

What happens if you launch panel settings from the terminal with the command `cinnamon-settings panel`?

**Comment by claudiux** [comment]
When I launch panel settings from the menu, the top panel becomes highlighted, and then nothing else.

When I launch panel settings from the terminal with the command `cinnamon-settings panel`, these lines appear:
```
Using PAM module (python3-pam)
Loading Panel module
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 607, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 319, in __init__
    self.go_to_sidepage(cat, path)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 132, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 123, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 143, in on_module_selected
    self.on_panel_list_changed()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 222, in on_panel_list_changed
    panel_page = PanelSettingsPage(panel_id, self.settings, position)
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 57, in __init__
    widget = PanelSwitch(scale_dimension_text, "org.cinnamon", "panels-scale-text-icons", self.panel_id)#, "org.cinnamon/panels-resizable")
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 344, in __init__
    self.connect_to_settings(schema, key)
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 308, in connect_to_settings
    self.on_setting_changed()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 355, in on_setting_changed
    self.content_widget.set_active(value)
TypeError: Argument 1 does not allow None as a value
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: '/var/crash/_usr_share_cinnamon_cinnamon-settings_cinnamon-settings.py.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 607, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 319, in __init__
    self.go_to_sidepage(cat, path)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 132, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 123, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 143, in on_module_selected
    self.on_panel_list_changed()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 222, in on_panel_list_changed
    panel_page = PanelSettingsPage(panel_id, self.settings, position)
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 57, in __init__
    widget = PanelSwitch(scale_dimension_text, "org.cinnamon", "panels-scale-text-icons", self.panel_id)#, "org.cinnamon/panels-resizable")
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 344, in __init__
    self.connect_to_settings(schema, key)
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 308, in connect_to_settings
    self.on_setting_changed()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_panel.py", line 355, in on_setting_changed
    self.content_widget.set_active(value)
TypeError: Argument 1 does not allow None as a value
```

**Comment by claudiux** [comment]
I solved this issue.

With `deconf-editor`, I have modified the value of `/org/cinnamon/panels-scale-text-icons`.
It was: `['1:true', '2:true', '4:true']`. I don't know why.
The correct value is: `['1:true', '2:true', '3:true']`

Then, all is OK.
