### ISSUE TITLE
Removing or Adding a Screen During Standby crashes Cinnamon on Resume

### ISSUE THREAD

**Issue by H8to** [linuxmint/Cinnamon#8053]
```
 * Cinnamon version - Cinnamon 4.0.0
 * Distribution - Arch
 * Lenovo T460p Nvidia prop. drivers
 * 64 bit
 ```
I had a look at the other issues opened. However, there is no "Cinnamon has Crashed" warning. It's just killing + core dumping all applications opened and taking me to the login screen. I have this issue since I use the T460p, which is two years now.

**Issue**
When I resume the laptop from standby and added or removed my external screen from the device, it crashes the session and presents me the login window without any error message.

**Steps to reproduce**
1. put the device to standby
2. add a second screen or remove the screen that had been attached
3. Crash

**Expected behaviour**
No crash on resume, all applications resume.

**Other information**
I can provide more details of course, but I don't know which makes sense. There is no .xsession-error file in my system.

Journalctl:
``` 
Nov 22 09:44:07 box systemd-coredump[27334]: Process 27316 (cinnamon-screen) of user 1000 dumped core.
                                             
                                             Stack trace of thread 27324:
                                             #0  0x00007f1c209cc715 __strlen_avx2 (libc.so.6)
                                             #1  0x000055a56cc7a47e n/a (cinnamon-screensaver-pam-helper)
                                             #2  0x00007f1c20c8dcd6 n/a (libgio-2.0.so.0)
                                             #3  0x00007f1c20a91bd6 n/a (libglib-2.0.so.0)
                                             #4  0x00007f1c20a8a3eb n/a (libglib-2.0.so.0)
                                             #5  0x00007f1c20a3aa9d start_thread (libpthread.so.0)
                                             #6  0x00007f1c20968b23 __clone (libc.so.6)
                                             
                                             Stack trace of thread 27325:
                                             #0  0x00007f1c209634ed syscall (libc.so.6)
                                             #1  0x00007f1c20a6f461 g_cond_wait (libglib-2.0.so.0)
                                             #2  0x00007f1c214df766 n/a (libcscreensaver.so.0)
                                             #3  0x00007f1c1faa3cf0 pam_vprompt (libpam.so.0)
                                             #4  0x00007f1c1faa3f3b pam_prompt (libpam.so.0)
                                             #5  0x00007f1c1faa0368 n/a (libpam.so.0)
                                             #6  0x00007f1c1a459811 pam_sm_authenticate (pam_unix.so)
                                             #7  0x00007f1c1fa9eb5d n/a (libpam.so.0)
                                             #8  0x00007f1c1fa9e3b0 pam_authenticate (libpam.so.0)
                                             #9  0x00007f1c214dfbff n/a (libcscreensaver.so.0)
                                             #10 0x00007f1c20a8a3eb n/a (libglib-2.0.so.0)
                                             #11 0x00007f1c20a3aa9d start_thread (libpthread.so.0)
                                             #12 0x00007f1c20968b23 __clone (libc.so.6)
                                             
                                             Stack trace of thread 27316:
                                             #0  0x00007f1c209356a8 __nanosleep (libc.so.6)
                                             #1  0x00007f1c20960d08 usleep (libc.so.6)
                                             #2  0x000055a56cc7a81b n/a (cinnamon-screensaver-pam-helper)
                                             #3  0x00007f1c214dfaa6 n/a (libcscreensaver.so.0)
                                             #4  0x00007f1c20abf271 g_main_context_dispatch (libglib-2.0.so.0)
                                             #5  0x00007f1c20ac0f89 n/a (libglib-2.0.so.0)
                                             #6  0x00007f1c20ac1f62 g_main_loop_run (libglib-2.0.so.0)
                                             #7  0x00007f1c20fad1af gtk_main (libgtk-3.so.0)
                                             #8  0x00007f1c214e0035 cs_auth_verify_user (libcscreensaver.so.0)
                                             #9  0x000055a56cc7a5eb n/a (cinnamon-screensaver-pam-helper)
                                             #10 0x00007f1c20abf271 g_main_context_dispatch (libglib-2.0.so.0)
                                             #11 0x00007f1c20ac0f89 n/a (libglib-2.0.so.0)
                                             #12 0x00007f1c20ac1f62 g_main_loop_run (libglib-2.0.so.0)
                                             #13 0x00007f1c20fad1af gtk_main (libgtk-3.so.0)
                                             #14 0x000055a56cc7a185 n/a (cinnamon-screensaver-pam-helper)
                                             #15 0x00007f1c20891223 __libc_start_main (libc.so.6)
                                             #16 0x000055a56cc7a27e n/a (cinnamon-screensaver-pam-helper)
                                             
                                             Stack trace of thread 27321:
                                             #0  0x00007f1c2095dc21 __poll (libc.so.6)
                                             #1  0x00007f1c20ac0ee0 n/a (libglib-2.0.so.0)
                                             #2  0x00007f1c20ac0fce g_main_context_iteration (libglib-2.0.so.0)
                                             #3  0x00007f1c20ac1022 n/a (libglib-2.0.so.0)
                                             #4  0x00007f1c20a8a3eb n/a (libglib-2.0.so.0)
                                             #5  0x00007f1c20a3aa9d start_thread (libpthread.so.0)
                                             #6  0x00007f1c20968b23 __clone (libc.so.6)
                                             
                                             Stack trace of thread 27322:
                                             #0  0x00007f1c2095dc21 __poll (libc.so.6)
                                             Stack trace of thread 27322:
                                             #0  0x00007f1c2095dc21 __poll (libc.so.6)
                                             #1  0x00007f1c20ac0ee0 n/a (libglib-2.0.so.0)
                                             #2  0x00007f1c20ac1f62 g_main_loop_run (libglib-2.0.so.0)
                                             #3  0x00007f1c20c27c28 n/a (libgio-2.0.so.0)
                                             #4  0x00007f1c20a8a3eb n/a (libglib-2.0.so.0)
                                             #5  0x00007f1c20a3aa9d start_thread (libpthread.so.0)
                                             #6  0x00007f1c20968b23 __clone (libc.so.6)
Nov 22 09:44:07 box pulseaudio[27359]: E: [pulseaudio] backend-ofono.c: Failed to register as a handsfree audio agent with ofono: org.freedesktop.DBus.Error.ServiceUnknown: The name org.ofono was not provided by any .service files
Nov 22 09:44:07 box systemd[1594]: Started Sound Service.
Nov 22 09:44:07 box rtkit-daemon[1100]: Recovering from system lockup, not allowing further RT threads.
Nov 22 09:44:07 box rtkit-daemon[1100]: Supervising 0 threads of 0 processes of 0 users.
Nov 22 09:44:07 box rtkit-daemon[1100]: Recovering from system lockup, not allowing further RT threads.
Nov 22 09:44:07 box rtkit-daemon[1100]: Supervising 0 threads of 0 processes of 0 users.
Nov 22 09:44:07 box rtkit-daemon[1100]: Recovering from system lockup, not allowing further RT threads.
Nov 22 09:44:07 box rtkit-daemon[1100]: Supervising 0 threads of 0 processes of 0 users.
Nov 22 09:44:07 box rtkit-daemon[1100]: Recovering from system lockup, not allowing further RT threads.
Nov 22 09:44:07 box rtkit-daemon[1100]: Supervising 0 threads of 0 processes of 0 users.
Nov 22 09:44:07 box rtkit-daemon[1100]: Recovering from system lockup, not allowing further RT threads.
Nov 22 09:44:07 box rtkit-daemon[1100]: Supervising 0 threads of 0 processes of 0 users.
Nov 22 09:44:07 box audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@5-27389-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Nov 22 09:44:07 box systemd[1]: Started Process Core Dump (PID 27389/UID 0).
Nov 22 09:44:07 box rtkit-daemon[1100]: Recovering from system lockup, not allowing further RT threads.
Nov 22 09:44:07 box rtkit-daemon[1100]: Supervising 0 threads of 0 processes of 0 users.
Nov 22 09:44:07 box rtkit-daemon[1100]: Recovering from system lockup, not allowing further RT threads.
Nov 22 09:44:07 box rtkit-daemon[1100]: Supervising 0 threads of 0 processes of 0 users.
Nov 22 09:44:07 box rtkit-daemon[1100]: Recovering from system lockup, not allowing further RT threads.
Nov 22 09:44:07 box rtkit-daemon[1100]: Supervising 0 threads of 0 processes of 0 users.
Nov 22 09:44:07 box rtkit-daemon[1100]: Recovering from system lockup, not allowing further RT threads.
Nov 22 09:44:07 box rtkit-daemon[1100]: Supervising 0 threads of 0 processes of 0 users.
Nov 22 09:44:07 box rtkit-daemon[1100]: Recovering from system lockup, not allowing further RT threads.
Nov 22 09:44:07 box rtkit-daemon[1100]: Supervising 0 threads of 0 processes of 0 users.
Nov 22 09:44:07 box /usr/lib/gdm-x-session[1606]: FileNotFoundError: [Errno 2] No such file or directory
Nov 22 09:44:07 box /usr/lib/gdm-x-session[1606]:     exec_func(fullname, *argrest)
Nov 22 09:44:07 box /usr/lib/gdm-x-session[1606]:   File "/usr/lib/python3.7/os.py", line 604, in _execvpe
Nov 22 09:44:07 box /usr/lib/gdm-x-session[1606]:     raise last_exc
Nov 22 09:44:07 box /usr/lib/gdm-x-session[1606]:   File "/usr/lib/python3.7/os.py", line 613, in _execvpe
Nov 22 09:44:07 box /usr/lib/gdm-x-session[1606]:     _execvpe(file, args)
Nov 22 09:44:07 box /usr/lib/gdm-x-session[1606]:   File "/usr/lib/python3.7/os.py", line 571, in execvp
Nov 22 09:44:07 box /usr/lib/gdm-x-session[1606]:     os.execvp(FALLBACK_COMMAND, (FALLBACK_COMMAND,) + FALLBACK_ARGS)
Nov 22 09:44:07 box /usr/lib/gdm-x-session[1606]:   File "/usr/bin/cinnamon-launcher", line 55, in <module>
Nov 22 09:44:07 box /usr/lib/gdm-x-session[1606]: Traceback (most recent call last):
Nov 22 09:44:07 box audit[27368]: ANOM_ABEND auid=1000 uid=1000 gid=985 ses=2 pid=27368 comm="cinnamon-launch" exe="/usr/bin/python3.7" sig=11 res=1
Nov 22 09:44:07 box /usr/lib/gdm-x-session[1606]: Cinnamon error: Unable to open X display :0
Nov 22 09:44:07 box /usr/lib/gdm-x-session[1606]: Unable to init server: Could not connect: Connection refused
Nov 22 09:44:07 box /usr/lib/gdm-x-session[1606]: Unable to init server: Could not connect: Connection refused
Nov 22 09:44:07 box /usr/lib/gdm-x-session[1606]: Unable to init server: Could not connect: Connection refused
Nov 22 09:44:07 box at-spi-bus-launcher[1650]:       after 37491 requests (37491 known processed) with 0 events remaining.
Nov 22 09:44:07 box at-spi-bus-launcher[1650]: XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]: Cannot open display:
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]: Cannot open display:
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]: Cannot open display:
Nov 22 09:44:06 box kernel: IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
Nov 22 09:44:06 box NetworkManager[560]: <info>  [1542876246.9727] device (wlan0): state change: unavailable -> disconnected (reason 'supplicant-available', sys-iface-state: 'managed')
Nov 22 09:44:06 box NetworkManager[560]: <info>  [1542876246.9727] device (wlan0): supplicant interface state: starting -> ready
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]: Cannot open display:
Nov 22 09:44:06 box NetworkManager[560]: <info>  [1542876246.9718] sup-iface[0x55819d834ae0,wlan0]: supports 5 scan SSIDs
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]: Cannot open display:
Nov 22 09:44:06 box cinnamon-session[1615]: WARNING: t+25438.77333s: Detected that screensaver has left the bus
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]: cinnamon-session[1615]: WARNING: t+25438.77333s: Detected that screensaver has left the bus
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]: Cannot open display:
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]: Cannot open display:
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]: Could not parse arguments: Cannot open display:
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]: Cannot open display:
Nov 22 09:44:06 box cinnamon-launch[1784]: cinnamon-launcher: Fatal IO error 2 (No such file or directory) on X server :0.
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]: Cannot open display:
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]: Cannot open display:
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]: Cannot open display:
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]: Cannot open display:
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]: Cannot open display:
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]: Cannot open display:
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]: Cannot open display:
Nov 22 09:44:06 box pulseaudio[27359]: W: [pulseaudio] pid.c: Stale PID file, overwriting.
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]: Cannot open display:
Nov 22 09:44:06 box rtkit-daemon[1100]: Recovering from system lockup, not allowing further RT threads.
Nov 22 09:44:06 box rtkit-daemon[1100]: Recovering from system lockup, not allowing further RT threads.
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]: Cannot open display:
Nov 22 09:44:06 box rtkit-daemon[1100]: Recovering from system lockup, not allowing further RT threads.
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]: Cannot open display:
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]: Cannot open display:
Nov 22 09:44:06 box rtkit-daemon[1100]: Recovering from system lockup, not allowing further RT threads.
Nov 22 09:44:06 box kernel: IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
Nov 22 09:44:06 box rtkit-daemon[1100]: Recovering from system lockup, not allowing further RT threads.
Nov 22 09:44:06 box rtkit-daemon[1100]: Recovering from system lockup, not allowing further RT threads.
Nov 22 09:44:06 box rtkit-daemon[1100]: Recovering from system lockup, not allowing further RT threads.
Nov 22 09:44:06 box rtkit-daemon[1100]: Recovering from system lockup, not allowing further RT threads.
Nov 22 09:44:06 box rtkit-daemon[1100]: Recovering from system lockup, not allowing further RT threads.
Nov 22 09:44:06 box rtkit-daemon[1100]: Recovering from system lockup, not allowing further RT threads.
Nov 22 09:44:06 box rtkit-daemon[1100]: Recovering from system lockup, not allowing further RT threads.
Nov 22 09:44:06 box systemd[1594]: Starting Sound Service...
Nov 22 09:44:06 box systemd[1594]: Stopped Sound Service.
Nov 22 09:44:06 box systemd[1594]: pulseaudio.service: Scheduled restart job, restart counter is at 1.
Nov 22 09:44:06 box systemd[1594]: pulseaudio.service: Service RestartSec=100ms expired, scheduling restart.
Nov 22 09:44:06 box audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@4-27350-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Nov 22 09:44:06 box systemd[1]: Started Process Core Dump (PID 27350/UID 0).
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]: FileNotFoundError: [Errno 2] No such file or directory
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]:     exec_func(fullname, *argrest)
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]:   File "/usr/lib/python3.7/os.py", line 604, in _execvpe
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]:     raise last_exc
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]:   File "/usr/lib/python3.7/os.py", line 613, in _execvpe
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]:     _execvpe(file, args)
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]:   File "/usr/lib/python3.7/os.py", line 571, in execvp
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]:     os.execvp(FALLBACK_COMMAND, (FALLBACK_COMMAND,) + FALLBACK_ARGS)
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]:   File "/usr/bin/cinnamon-launcher", line 55, in <module>
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]: Traceback (most recent call last):
Nov 22 09:44:06 box audit[2066]: ANOM_ABEND auid=1000 uid=1000 gid=985 ses=2 pid=2066 comm="Chrome_~dThread" exe="/usr/lib/firefox/firefox" sig=11 res=1
Nov 22 09:44:06 box cinnamon-session[1615]: WARNING: t+25438.54758s: Child process 1703 was already dead.
Nov 22 09:44:06 box /usr/lib/gdm-x-session[1606]: cinnamon-session[1615]: WARNING: t+25438.54758s: Child process 1703 was already dead.
Nov 22 09:44:06 box audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@2-27340-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Nov 22 09:44:06 box systemd[1]: Started Process Core Dump (PID 27340/UID 0).
Nov 22 09:44:06 box audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@3-27339-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Nov 22 09:44:06 box systemd[1]: Started Process Core Dump (PID 27339/UID 0).
Nov 22 09:44:06 box audit[27104]: ANOM_ABEND auid=1000 uid=1000 gid=985 ses=3 pid=27104 comm="Chrome_~dThread" exe="/usr/lib/firefox/firefox" sig=11 res=1
Nov 22 09:44:06 box audit[27072]: ANOM_ABEND auid=1000 uid=1000 gid=985 ses=3 pid=27072 comm="Chrome_~dThread" exe="/usr/lib/firefox/firefox" sig=11 res=1
Nov 22 09:44:06 box audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@1-27332-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Nov 22 09:44:06 box systemd[1]: Started Process Core Dump (PID 27332/UID 0).
Nov 22 09:44:06 box systemd[1594]: pulseaudio.service: Failed with result 'exit-code'.
Nov 22 09:44:06 box audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@0-27333-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success
``` 

There is this error on the bottom with os.py but the file exists:
Permissions Size User Group Date Modified Name
.rw-r--r--   37k root root  22 Oct 12:41  /usr/lib/python3.7/os.py

**Comment by leigh123linux** [comment]
File the issue against cinnamon-screensaver
