### ISSUE TITLE
cinnamon settings don't open

### ISSUE THREAD

**Issue by qiray** [linuxmint/Cinnamon#8203]
```
 * Cinnamon 4.0.8
 * Distribution - Mint 19.1
 * Pitcairn XT [Radeon HD 7870 GHz Edition], Radeon driver
 * 64 bit
 ```

**Issue**

cinnamon-settings don't start after upgrading to Cinnamon 4

**Steps to reproduce**

Upgrade to Mint 19.1 from Mint 19 using these commands.

```bash
sudo apt update && sudo apt upgrade
sudo sed -i 's/tara/tessa/' /etc/apt/sources.list 
sudo sed -i 's/tara/tessa/' /etc/apt/sources.list.d/official-package-repositories.list
sudo apt update && sudo apt upgrade
sudo apt-get dist-upgrade
```

Then open Cinnamon session and try to open settings panel. Terminal output:
```
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 619, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 247, in __init__
    for module in modules:
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_desktop.py", line 6, in <module>
    gi.require_version('Nemo', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Nemo not available
```

**Expected behaviour**

I expect settings panel to work.

**Other information**

File [cs_desktop.py](https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/modules/cs_desktop.py) has line:

```python
gi.require_version('Nemo', '3.0')
```
Is it correct for cinnamon 4? Commenting this line makes settings work.

[xsession-errors.log](https://github.com/linuxmint/Cinnamon/files/2707462/xsession-errors.log)

**Comment by jaszhix** [comment]
Was nemo uninstalled? You're supposed to upgrade through the update manager. It might have been removed during the upgrade.

**Comment by qiray** [comment]
@jaszhix Nemo was updated too. It has version 4 now.

**Comment by qiray** [comment]
Well, I installed gir1.2-nemo-3.0 and it works now.

**Comment by LinuxOnTheDesktop** [comment]
I'm getting the same error, after upgrading some packages with 

```
su
pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U
```

The problem:
```
$  cinnamon-settings
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 619, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 247, in __init__
    for module in modules:
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_backgrounds.py", line 5, in <module>
    import imtools
  File "/usr/share/cinnamon/cinnamon-settings/bin/imtools.py", line 623, in <module>
    if Image.VERSION == '1.1.7':
AttributeError: module 'PIL.Image' has no attribute 'VERSION'
```

The following did not seem to help.

`sudo apt install gir1.2-nemo-3.0 --reinstall`

**Comment by JosephMcc** [comment]
@LinuxOnTheDesktop there is a fix on git master for this at the moment: https://github.com/linuxmint/cinnamon/commit/c843f3664064742e2672e0fea528571a882d84ad

**Comment by LinuxOnTheDesktop** [comment]
Yes, that is part of what I meant. But I take it that the fix has not been deployed. What I was going to do (as I tried to say above) was to manually apply that fix to my system, i.e. to alter, on my computer, the relevant .py file myself. Now, in the meantime, I _did_ do that. And it works.

Thanks.

**Comment by Odyseus** [comment]
Hello, everybody.

@LinuxOnTheDesktop: You should **never** use `pip` as you did to upgrade your global Python modules (except maybe on alpha distributions like Fedora or ArchLinux). `pip` will upgrade **all** Python modules, whether they were installed through `pip` or through `apt`. `pip` packages are always in their latest versions, whereas `apt` packages are feature frozen.

**Comment by LinuxOnTheDesktop** [comment]
@Odyseus 

Thanks. However, when I ran the command that I posted, some of the output said, in effect: you've installed this via apt, so we'll leave it alone.

**Comment by Odyseus** [comment]
@LinuxOnTheDesktop: Oh, good to know. It must be a new improvement on `pip`'s side. What I wrote before is based on my own experience from a couple of years ago. Luckily, in my case, I just had to reinstall a couple of Python modules (some through `pip` and some through `apt`).

Anyway, thanks for the info, LinuxOnTheDesktop. And sorry for the off-topic, everybody.

**Comment by smurphos** [comment]
There's a few reports of this popping on the Mint Forum - various Cinnamon versions. Hopefully https://github.com/linuxmint/cinnamon/commit/c843f3664064742e2672e0fea528571a882d84ad  will be rolled out and will perhaps be a candidate for a maintenance patch for older Cinnamon versions?

**Comment by rt3norio** [comment]
I had this same problem after installing cinnamon in a MATE 19.1. 
`gir1.2-nemo-3.0 solved the problem`

**Comment by MoatazAbdAlmageed** [comment]
`sudo apt-get install gir1.2-nemo-3.0`
