### ISSUE TITLE
Cinnamon Settings does not open 

### ISSUE THREAD

**Issue by bechain9** [linuxmint/Cinnamon#8266]
```
 * Cinnamon version (cinnamon --version) 4.0.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) ubuntu 18.04
 * Graphics hardware *and* driver used 
 * 32 or 64 bit 64bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
Cinnamon settings does not open after upgrade to 4.0.8. Similar issue has been reported on the linuxmint forums. 

**Steps to reproduce**
Opening cinnamon settings via terminal produces an error 
```
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 619, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 247, in __init__
    for module in modules:
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_desktop.py", line 6, in <module>
    gi.require_version('Nemo', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Nemo not available
```

**Expected behaviour**

Cinnamon settings should open. 

**Other information**
Simply commenting out line 6 which is the nemo version check fixes the bug. The nemo version needs to be updated probably. Current nemo version in use is 4.0.6

**Comment by jaszhix** [comment]
#8203

> Check if gir1.2-nemo-3.0 is at 4.0.6. 3.0 is the correct typelib version.
