### ISSUE TITLE
Arch lock screen no password prompt

### ISSUE THREAD

**Issue by Strum355** [linuxmint/cinnamon#8685]
```
 * Cinnamon version (cinnamon --version) - 4.2.0
 * Distribution - Arch
 * Graphics hardware *and* driver used - VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07)
 * 32 or 64 bit - 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog: below 
```

 [xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/3355217/xsession-errors.txt)

**Issue**
Lock screen doesnt prompt for password, mouse move reveals desktop
```
 ~  cinnamon-screensaver-command -l
Traceback (most recent call last):
  File "/usr/share/cinnamon-screensaver/cinnamon-screensaver-command.py", line 73, in on_client_ready
    self.perform_action()
  File "/usr/share/cinnamon-screensaver/cinnamon-screensaver-command.py", line 90, in perform_action
    self.client.proxy.call_lock_sync(self.message)
gi.repository.GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method Lock is not implemented on interface org.cinnamon.ScreenSaver (19)
```

**Steps to reproduce**
- Lock screen with `cinnamon-screensaver-command -l` or ctrl+alt+L
- Move mouse

**Expected behaviour**
Prompts for password before revealing desktop

**Comment by Strum355** [comment]
Issue related to https://github.com/nir0s/distro/issues/222
Commented out the monkeypatching stdlib line in `/usr/lib/python3.7/site-packages/subprocess.run.pth` and restarted OS and was fine again
