### ISSUE TITLE
cinnamon-settings default crashing with UnboundLocalError

### ISSUE THREAD

**Issue by antipatico** [linuxmint/cinnamon#8853]
* Cinnamon version (cinnamon --version)
`Cinnamon 4.2.4`
 * Distribution 
`Fedora 30`
 * Graphics hardware *and* driver used
`Mesa DRI Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2)`
 * 32 or 64 bit
`64bit`
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
[xsession-errors.log](https://github.com/linuxmint/cinnamon/files/3612716/xsession-errors.log)

**Issue**

`cinnamon-settings default` (also known as `Preferred Applications`) crashes with UnboundLocalError.

**Steps to reproduce**
Run `cinnamon-settings default` in a terminal or open the `Preferred Applications` from the menu. The software does not open, and immediately crashes.

**Expected behaviour**
The default application settings should open.

**Other information**
Logs from the terminal:
```
user@host $ cinnamon-settings default
True
Using pam module (python3-pampy)
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:423: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.window.set_wmclass(wm_class, wm_class)
Loading Default module
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 724, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 428, in __init__
    self.go_to_sidepage(cat, path, user_action=False)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 185, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 123, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_default.py", line 520, in on_module_selected
    self.other_type_dialog = OtherTypeDialog(self.media_settings, self.sidePage.window)
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_default.py", line 419, in __init__
    list_store.append([self.getDescription(content_type), content_type])
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_default.py", line 455, in getDescription
    if description == None:
UnboundLocalError: local variable 'description' referenced before assignment
```

**Comment by leigh123linux** [comment]
@antipatico  fix is being pushed to testing

https://bodhi.fedoraproject.org/updates/FEDORA-2019-85c1d5e85d
