### ISSUE TITLE
[Arch] Unable to start "cinnamon-menu-editor"

### ISSUE THREAD

**Issue by Davetheraveuk** [linuxmint/cinnamon#8962]
**Cinnamon 4.2.4**
**Updated via Arch Linux repos.**
**Arch**
**Hardware: Nvidia Geforce 1050 Ti**
**Driver: nvidia  440.31-2**
**64 Bit**

Error message from terminal:
```
[dave@RebornOS Desktop]$ cinnamon-menu-editor
Traceback (most recent call last):
  File "/usr/bin/cinnamon-menu-editor", line 29, in <module>
    main()
  File "/usr/bin/cinnamon-menu-editor", line 24, in main
    app.run()
  File "/usr/share/cinnamon/cinnamon-menu-editor/cme/MainWindow.py", line 66, in run
    self.loadMenus()
  File "/usr/share/cinnamon/cinnamon-menu-editor/cme/MainWindow.py", line 201, in loadMenus
    self.loadMenu({ None: None })
  File "/usr/share/cinnamon/cinnamon-menu-editor/cme/MainWindow.py", line 212, in loadMenu
    name = cgi.escape(menu.get_name())
AttributeError: module 'cgi' has no attribute 'escape'
[dave@RebornOS Desktop]$
```
**Issue**
Unable to start **cinnamon-menu-editor** from terminal or right click **configure** from start menu.

**Steps to reproduce**
???

**Expected behaviour**
cinnamon-menu-editor should start as normal.

**Other information**
I hope the terminal output is enough to help you guys.

Thanks, Dave.

**Comment by Davetheraveuk** [comment]
Thanks man.
