### ISSUE TITLE
Themes in Settings don't open

### ISSUE THREAD

**Issue by PhpMadman** [linuxmint/cinnamon#8969]
```
 * Cinnamon version: Cinnamon 4.2.4
   - Regular one from Mint 19.2 release
 * Mint 19.2 upgraded from 18.3
 * Graphics:  Device-1: AMD Kaveri [Radeon R7 Graphics] vendor: Hewlett-Packard driver: radeon 
           v: kernel bus ID: 00:01.0 chip ID: 1002:1313 
           Display: x11 server: X.Org 1.19.6 driver: ati,radeon unloaded: fbdev,modesetting,vesa 
           resolution: 1920x1080~60Hz 
           OpenGL: renderer: AMD KAVERI (DRM 2.50.0 4.15.0-51-generic LLVM 8.0.0) 
           v: 4.5 Mesa 19.0.8 direct render: Yes
 * 64 bit
 ```

**Some background info**
After updating from Mint 18.3 to 19.3 Themes in Settings don't open. 
I ran gsettings set org.cinnamon.theme name 'Linux Mint', and that changed my theme slightly, it is still black, but it does not look exactly as in 18.3. I don't remeber if had any custom theme. But i know I changed to a Mint X/Y Dark setup. When I started with this problem I had a Mint-Y-Dark-Red-Custom in /.themes, but that is now removed, so the /.themes folder is now empty.
Also, I did not use that theme at upgrade (I think), my theme is black / blue.

I also have a reddit thread where we tried to solve this.
https://www.reddit.com/r/linuxmint/comments/dxqjp8/mint_192_cinnamon_system_settings_themes_config/

**Issue**
After updating from Mint 18.3 to 19.3 Themes in Settings don't open. When I click on it, the System Settings window appears to freeze and then it closes. Trying to open it from terminal gives thousands of lines of codes.

Here are the highlights. Scrolling tru it, it seems to be the same errors, repeated, except for the first 
`File "/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py", line 834, in sort_score
return row2.score - row1.score`
and the last one
`OSError: [Errno 24] Too many open files: '/home/madman/.config/gtk-3.0/gtk.css'`

```
madman@RedDragon ~ $ cinnamon-settings themes
True
Using PAM module (python3-pam)
Loading Themes module
There was an error processing one of the images. Try refreshing the cache.
There was an error processing one of the images. Try refreshing the cache.
Traceback (most recent call last):
File "/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py", line 834, in sort_score
return row2.score - row1.score
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Error in sys.excepthook:
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_share_cinnamon_cinnamon-settings_cinnamon-settings.py.1000.crash'

Original exception was:
Traceback (most recent call last):
File "/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py", line 834, in sort_score
TypeError: unsupported operand type(s) for -: 'str' and 'str'

Traceback (most recent call last):
File "/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py", line 834, in sort_score
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Error in sys.excepthook:

Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 109, in apport_excepthook
File "/usr/lib/python3/dist-packages/apport/report.py", line 537, in add_proc_info
OSError: [Errno 24] Too many open files: '/proc/17405'

Original exception was:
Traceback (most recent call last):
File "/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py", line 834, in sort_score
TypeError: unsupported operand type(s) for -: 'str' and 'str'
There was an error processing one of the images. Try refreshing the cache.

Traceback (most recent call last):
File "/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py", line 834, in sort_score
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Error in sys.excepthook:

Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 109, in apport_excepthook
File "/usr/lib/python3/dist-packages/apport/report.py", line 537, in add_proc_info
OSError: [Errno 24] Too many open files: '/proc/17405'

Original exception was:
Traceback (most recent call last):
File "/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py", line 834, in sort_score
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
File "/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py", line 834, in sort_score
TypeError: unsupported operand type(s) for -: 'str' and 'str'
Error in sys.excepthook:
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 109, in apport_excepthook
File "/usr/lib/python3/dist-packages/apport/report.py", line 537, in add_proc_info
OSError: [Errno 24] Too many open files: '/proc/17580'

Original exception was:
Traceback (most recent call last):
File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 724, in <module>
File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 428, in __init__
File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 185, in go_to_sidepage
File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 123, in build
File "/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py", line 113, in on_module_selected
File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 189, in sync_initial_switch_state
File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 81, in get_css_editor
File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 94, in __init__
File "/usr/lib/python3/dist-packages/tinycss/css21.py", line 351, in parse_stylesheet_file
OSError: [Errno 24] Too many open files: '/home/madman/.config/gtk-3.0/gtk.css'
```
In addition to that I tried to print out any output to a text file using 
`cinnamon-settings themes > themes.txt`

That gave a text like this.

```
True
Using PAM module (python3-pam)
Loading Themes module
There was an error processing one of the images. Try refreshing the cache.
-- Repeated ~400 times --
There was an error processing one of the images. Try refreshing the cache.
Could not load ~/.gtkrc-2.0 file: Error opening file /home/madman/.gtkrc-2.0: Too many open files
```

Also, My Applets and Desklets caches was out of date, but thoose asked to refresh them without any issue.

**Comment by claudiux** [comment]
@PhpMadman 

In each subfolder of your `~/.themes` folder, check if the "last-edited" field value in the `metadata.json` or the `cinnamon/metadata.json` file is well an integer, not a string.

Example:
```
cat ~/.themes/CBlack/cinnamon/metadata.json
```
returns:
```
{
    "last-edited": "1480523529", 
    "uuid": "589"
}
```
Then replace it by:
```
{
    "last-edited": 1480523529, 
    "uuid": "589"
}
```

But this bug has been fixed by #8459. Are you sure you have installed all the Cinnamon updates?

**Comment by PhpMadman** [comment]
@claudiux 
My ~/.themes is empty. I have nothing there.
However I searched and found /usr/share/.themes and none of the themes there have any metadata.json at all. Does that matter?

I just upgraded to Mint 19.2 and the update manager says my install is up to date.

**Comment by claudiux** [comment]
@PhpMadman 
Then try:
```
cd ~/.local/share/cinnamon

for d in applets desklets extensions; do if [ -d $d ]; then for s in $(ls $d -1A); do if [ -f $d/$s/metadata.json ]; then (echo "$d/$s/metadata.json"; cat $d/$s/metadata.json | grep "last-edited");fi; done;fi;done 
```

**Comment by claudiux** [comment]
@PhpMadman Are there any .zip (or other) files in the `applets`, `desklets`, `extensions` subfolders of `~/.local/share/cinnamon`? If so, remove them.

**Comment by PhpMadman** [comment]
I tried the commands, and they did not return anything. Also, All the folders you mentioned was empty, so I assume I'm missing alot of files?

**Comment by smurphos** [comment]
@PhpMadman - try deleting the folder `~/.cinnamon/spices.cache/theme` then reopening the themes settings module.

**Comment by PhpMadman** [comment]
@smurphos 
Thank you. That fixed it. 

I checked the folder before deleting and almost all the images was broken.
So all errors must have come from reading cinnamon trying to read a .png file that was not a complete .png file.

**Comment by claudiux** [comment]
@PhpMadman 

> I tried the commands, and they did not return anything. Also, All the folders you mentioned was empty, so I assume I'm missing alot of files?

Theses commands (https://github.com/linuxmint/cinnamon/issues/8969#issuecomment-555530626) return, on my computer:
```
applets/batterymonitor@pdcurtis/metadata.json
    "last-edited": 1574101668
applets/brightness-and-gamma-applet@cardsurf/metadata.json
    "last-edited": 1571770165
applets/Cinnamenu@json/metadata.json
    "last-edited": 1571504427
[...]
desklets/accudesk@logan/metadata.json
    "last-edited": 1419803530
desklets/bbcwx@oak-wood.co.uk/metadata.json
    "last-edited": 1571511575,
desklets/calculator@scollins/metadata.json
    "last-edited": 1571741506
desklets/clock@schorschii/metadata.json
    "last-edited": 1573919045
desklets/diskspace@schorschii/metadata.json
    "last-edited": 1573919258
[...]
extensions/DesktopCube@yare/metadata.json
  "last-edited": 1574254352
extensions/watermark@germanfr/metadata.json
    "last-edited": 1573375682
```
