### ISSUE TITLE
AttributeError: module 'platform' has no attribute 'linux_distribution'

### ISSUE THREAD

**Issue by lekma** [linuxmint/cinnamon#9170]
* Cinnamon version: Cinnamon 4.4.8
 * Distribution: Ubuntu 20.04 LTS (Focal Fossa)

Python [deprecated platform.linux_distribution() in 3.5](https://bugs.python.org/issue1322) and [removed it in 3.8](https://bugs.python.org/issue28167).

Python 3.8.2rc1 seems to be the current default in Ubuntu 20.04.

lekma/cinnamon@8e9cbd055a1d4b4ee1da2e783b93e690f6526549 might fix it (untested).

edit:
I forgot to mention that this affects `cinnamon-settings info`

full traceback:
```
~$ cinnamon-settings info
True
Using pam module (python3-pampy)
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:427: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.window.set_wmclass(wm_class, wm_class)
Loading Info module
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 727, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 432, in __init__
    self.go_to_sidepage(cat, path, user_action=False)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 189, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 213, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_info.py", line 149, in on_module_selected
    infos = createSystemInfos()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_info.py", line 108, in createSystemInfos
    s = '%s (%s)' % (' '.join(platform.linux_distribution()), arch)
AttributeError: module 'platform' has no attribute 'linux_distribution'
```

**Comment by leigh123linux** [comment]
@lekma I have tested your fix and it works ok, can you submit it as a PR please?

**Comment by lekma** [comment]
@leigh123linux: done (pr #9171)

**Comment by lekma** [comment]
fixed by https://github.com/linuxmint/cinnamon/commit/664c12d13f70c1e304859c1ec3f1268772b92500
