### ISSUE TITLE
Settings for desklets won't open

### ISSUE THREAD

**Issue by YungDaVinci** [linuxmint/cinnamon#9312]
* Cinnamon version: 4.6.0
   - Please specify if you are using the daily builds PPA: No
 * Distribution - Arch
 * Graphics hardware *and* driver used - GTX 1060 6GB, nvidia 440.82
 * 64bit
 *  ~/.xsession-errors was empty

**Issue**
Attempting to open the settings for any desklet results in the following error:
```
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 17, in <module>
    from JsonSettingsWidgets import *
  File "/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py", line 332, in <module>
    globals()["JSONSettings"+widget] = json_settings_factory(widget)
  File "/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py", line 313, in json_settings_factory
    class NewClass(globals()[subclass], JSONSettingsBackend):
KeyError: 'SoundFileChooser'
```

**Steps to reproduce**
1. Go into Desklets menu
2. Attempt to open the settings for a desklet

**Expected behaviour**
The settings for the desklet opens.

**Comment by leigh123linux** [comment]
https://github.com/linuxmint/cinnamon/issues/9305
