### ISSUE TITLE
Cinnamon settings: cs_info: Failure when detecting CPU name leads to crash

### ISSUE THREAD

**Issue by Cyanoxygen** [linuxmint/cinnamon#9754]
Hi, 
I just encountered an issue trying to open the System Info page of Cinnamon Settings, this page can not be opened.

### Environment
ARM64 Raspberry Pi 4, Cinnamon 4.8.0

### Troubleshooting
I run `cinnamon-settings info` in the terminal and get this output:

```
Using pam module (python3-pampy)
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:427: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.window.set_wmclass(wm_class, wm_class)
Loading Info module
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 731, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 432, in __init__
    self.go_to_sidepage(cat, path, user_action=False)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 189, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 212, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_info.py", line 154, in on_module_selected
    infos = createSystemInfos()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_info.py", line 95, in createSystemInfos
    processorName = procInfos['cpu_name'].replace("(R)", "\u00A9").replace("(TM)", "\u2122")
KeyError: 'cpu_name'
```
I then looked into the code detecting the CPU name:

https://github.com/linuxmint/cinnamon/blob/fa2293b25657a26808513431809434128febef43/files/usr/share/cinnamon/cinnamon-settings/modules/cs_info.py#L70

I do think this code can not work on some platforms (for my instance it is arm64). Then I referred the [code from neofetch](https://github.com/dylanaraps/neofetch/blob/6dd85d67fc0d4ede9248f2df31b2cd554cca6c2f/neofetch#L2163), and wrote a simple fix for it: https://github.com/Cyanoxygen/cinnamon/commit/b60b93165f76ef370bb248e37525863facb71e74.

Here's the result:
![image](https://user-images.githubusercontent.com/29174191/101477035-9bac5f80-3989-11eb-9af8-c8cef3c8e43b.png)

**Comment by Cyanoxygen** [comment]
BTW here's the `/proc/cpuinfo` from my Raspberry Pi:
```
processor	: 0
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 1
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 2
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 3
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

Hardware	: BCM2835
Revision	: c03112
Serial		: 1000000049796edf
Model		: Raspberry Pi 4 Model B Rev 1.2
```

There's no `cpu model` here so System Info module would crash under this circumstance.

**Comment by Cyanoxygen** [comment]
Closing as #9755 merged.
