### ISSUE TITLE
Cinnamon apps are crashing on launch saying some Module are missing

### ISSUE THREAD

**Issue by Flaburgan** [linuxmint/cinnamon#9991]
For a few days, I'm not able to launch some Cinnamon apps. Firefox, Folder, Signal, Terminal... are all working fine. This isn't a freshly installation, I don't know what made it break. I tried to force the usage of python3 by installing `python-is-python3` but that didn't change anything.

```
fla@enigma:~$ cinnamon-settings
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 27, in <module>
    import SettingsWidgets
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 13, in <module>
    from ChooserButtonWidgets import DateChooserButton, TweenChooserButton, EffectChooserButton, TimeChooserButton
  File "/usr/share/cinnamon/cinnamon-settings/bin/ChooserButtonWidgets.py", line 4, in <module>
    import cairo
ModuleNotFoundError: No module named 'cairo'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
ModuleNotFoundError: No module named 'apport'

Original exception was:
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 27, in <module>
    import SettingsWidgets
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 13, in <module>
    from ChooserButtonWidgets import DateChooserButton, TweenChooserButton, EffectChooserButton, TimeChooserButton
  File "/usr/share
```

System infos:
```
cinnamon --version
Cinnamon 4.6.7
```

```
System:    Kernel: 5.11.7-051107-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 4.6.7 wm: muffin 
           dm: LightDM Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal 
Machine:   Type: Desktop Mobo: ASUSTeK model: PRIME Z270-P v: Rev X.0x serial: <filter> UEFI: American Megatrends 
           v: 1205 date: 05/11/2018 
CPU:       Topology: Quad Core model: Intel Core i5-7600K bits: 64 type: MCP arch: Kaby Lake rev: 9 
           L2 cache: 6144 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 bogomips: 30399 
           Speed: 800 MHz min/max: 800/4200 MHz Core speeds (MHz): 1: 800 2: 800 3: 800 4: 800 
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] 
           vendor: ASUSTeK driver: amdgpu v: kernel bus ID: 01:00.0 chip ID: 1002:67df 
           Display: x11 server: X.Org 1.20.9 driver: amdgpu,ati unloaded: fbdev,modesetting,vesa 
           resolution: 2560x1440~60Hz, 1920x1080~60Hz 
           OpenGL: renderer: Radeon RX 580 Series (POLARIS10 DRM 3.40.0 5.11.7-051107-generic LLVM 11.0.1) 
           v: 4.6 Mesa 21.1.0-devel (git-684f97d 2021-03-12 focal-oibaf-ppa) direct render: Yes 
Audio:     Device-1: Intel 200 Series PCH HD Audio vendor: ASUSTeK driver: snd_hda_intel v: kernel bus ID: 00:1f.3 
           chip ID: 8086:a2f0 
           Device-2: AMD Ellesmere HDMI Audio [Radeon RX 470/480 / 570/580/590] vendor: ASUSTeK 
           driver: snd_hda_intel v: kernel bus ID: 01:00.1 chip ID: 1002:aaf0 
           Device-3: Logitech B525 HD Webcam type: USB driver: snd-usb-audio,uvcvideo bus ID: 1-10:4 
           chip ID: 046d:0836 
           Sound Server: ALSA v: k5.11.7-051107-generic 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: ASUSTeK driver: r8169 v: kernel 
           port: d000 bus ID: 04:00.0 chip ID: 10ec:8168 
           IF: enp4s0 state: up speed: 100 Mbps duplex: full mac: <filter> 
           IF-ID-1: anbox0 state: unknown speed: -1 duplex: unknown mac: <filter> 
Drives:    Local Storage: total: 2.05 TiB used: 204.96 GiB (9.8%) 
           ID-1: /dev/sda vendor: Samsung model: SSD 850 EVO M.2 250GB size: 232.89 GiB speed: 6.0 Gb/s 
           serial: <filter> 
           ID-2: /dev/sdb vendor: Samsung model: SSD 860 EVO 1TB size: 931.51 GiB speed: 6.0 Gb/s serial: <filter> 
           ID-3: /dev/sdc vendor: Seagate model: ST1000DM010-2EP102 size: 931.51 GiB speed: 6.0 Gb/s 
           serial: <filter> 
Partition: ID-1: / size: 227.74 GiB used: 204.95 GiB (90.0%) fs: ext4 dev: /dev/sda2 
Sensors:   System Temperatures: cpu: 29.8 C mobo: 27.8 C gpu: amdgpu temp: 52 C 
           Fan Speeds (RPM): N/A gpu: amdgpu fan: 1253 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/bhdouglass-clickable-focal.list 
           1: deb http://ppa.launchpad.net/bhdouglass/clickable/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/nodesource.list 
           1: deb https://deb.nodesource.com/node_14.x focal main
           2: deb-src https://deb.nodesource.com/node_14.x focal main
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http://mirror6.layerjet.com/linuxmint/packages ulyana main upstream import backport
           2: deb http://ftp.rezopole.net/ubuntu focal main restricted universe multiverse
           3: deb http://ftp.rezopole.net/ubuntu focal-updates main restricted universe multiverse
           4: deb http://ftp.rezopole.net/ubuntu focal-backports main restricted universe multiverse
           5: deb http://security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
           6: deb http://archive.canonical.com/ubuntu/ focal partner
           Active apt repos in: /etc/apt/sources.list.d/oibaf-graphics-drivers-focal.list 
           1: deb http://ppa.launchpad.net/oibaf/graphics-drivers/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/signal-xenial.list 
           1: deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main
           Active apt repos in: /etc/apt/sources.list.d/spotify.list 
           1: deb http://repository.spotify.com stable non-free
Info:      Processes: 307 Uptime: 9h 59m Memory: 15.58 GiB used: 7.93 GiB (50.9%) Init: systemd v: 245 runlevel: 5 
           Compilers: gcc: 9.3.0 alt: 7/9 Shell: upload-system-i running in: gnome-terminal inxi: 3.0.38 
```

`.xsession-errors`:
```
dbus-update-activation-environment: setting DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
dbus-update-activation-environment: setting DISPLAY=:0
dbus-update-activation-environment: setting XAUTHORITY=/home/fla/.Xauthority
dbus-update-activation-environment: setting GTK_MODULES=gail:atk-bridge
dbus-update-activation-environment: setting QT_ACCESSIBILITY=1
dbus-update-activation-environment: setting SHELL=/bin/bash
dbus-update-activation-environment: setting QT_ACCESSIBILITY=1
dbus-update-activation-environment: setting XDG_CONFIG_DIRS=/etc/xdg/xdg-cinnamon:/etc/xdg
dbus-update-activation-environment: setting XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
dbus-update-activation-environment: setting LANGUAGE=fr_FR
dbus-update-activation-environment: setting MANDATORY_PATH=/usr/share/gconf/cinnamon.mandatory.path
dbus-update-activation-environment: setting LC_ADDRESS=fr_FR.UTF-8
dbus-update-activation-environment: setting LC_NAME=fr_FR.UTF-8
dbus-update-activation-environment: setting DESKTOP_SESSION=cinnamon
dbus-update-activation-environment: setting LC_MONETARY=fr_FR.UTF-8
dbus-update-activation-environment: setting GTK_MODULES=gail:atk-bridge
dbus-update-activation-environment: setting PWD=/home/fla
dbus-update-activation-environment: setting XDG_SESSION_DESKTOP=cinnamon
dbus-update-activation-environment: setting LOGNAME=fla
dbus-update-activation-environment: setting XDG_SESSION_TYPE=x11
dbus-update-activation-environment: setting GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
dbus-update-activation-environment: setting XAUTHORITY=/home/fla/.Xauthority
dbus-update-activation-environment: setting XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/fla
dbus-update-activation-environment: setting GDM_LANG=fr_FR
dbus-update-activation-environment: setting HOME=/home/fla
dbus-update-activation-environment: setting IM_CONFIG_PHASE=1
dbus-update-activation-environment: setting LC_PAPER=fr_FR.UTF-8
dbus-update-activation-environment: setting LANG=fr_FR.UTF-8
dbus-update-activation-environment: setting XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
dbus-update-activation-environment: setting XDG_SESSION_CLASS=user
dbus-update-activation-environment: setting LC_IDENTIFICATION=fr_FR.UTF-8
dbus-update-activation-environment: setting DEFAULTS_PATH=/usr/share/gconf/cinnamon.default.path
dbus-update-activation-environment: setting USER=fla
dbus-update-activation-environment: setting DISPLAY=:0
dbus-update-activation-environment: setting SHLVL=1
dbus-update-activation-environment: setting LC_TELEPHONE=fr_FR.UTF-8
dbus-update-activation-environment: setting LC_MEASUREMENT=fr_FR.UTF-8
dbus-update-activation-environment: setting PAPERSIZE=a4
dbus-update-activation-environment: setting XDG_RUNTIME_DIR=/run/user/1000
dbus-update-activation-environment: setting LC_TIME=fr_FR.UTF-8
dbus-update-activation-environment: setting XDG_DATA_DIRS=/usr/share/cinnamon:/usr/share/gnome:/home/fla/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop
dbus-update-activation-environment: setting PATH=/home/fla/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
dbus-update-activation-environment: setting GDMSESSION=cinnamon
dbus-update-activation-environment: setting DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
dbus-update-activation-environment: setting LC_NUMERIC=fr_FR.UTF-8
dbus-update-activation-environment: setting _=/usr/bin/dbus-update-activation-environment
[cinnamon-settings-daemon-smartcard] Failed to start: impossible de trouver un pilote de carte à puce adapté
xrandr-plugin-Message: 20:49:17.884: Existing monitor config (/home/fla/.config/cinnamon-monitors.xml) not found at startup. Looking for legacy configuration (monitors.xml)
[cinnamon-settings-daemon-smartcard] Failed to start: impossible de trouver un pilote de carte à puce adapté
Cinnamon warning: Log level 128: unsetenv() is not thread-safe and should not be used after threads are created
Clutter-Message: 20:49:18.362: Sync method: PRESENTATION TIME
Cjs-Message: 20:49:18.478: JS LOG: About to start Cinnamon
Cjs-Message: 20:49:18.750: JS LOG: [LookingGlass/info] Cinnamon.AppSystem.get_default() started in 270 ms
Cjs-Message: 20:49:18.758: JS LOG: [LookingGlass/info] loading user theme: /usr/share/themes/Mint-Y-Dark/cinnamon/cinnamon.css
Cjs-Message: 20:49:18.777: JS LOG: [LookingGlass/info] added icon directory: /usr/share/themes/Mint-Y-Dark/cinnamon

(cinnamon:2052): Cjs-WARNING **: 20:49:18.777: Some code accessed the property 'BackgroundManager' on the module 'backgroundManager'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Cinnamon warning: Log level 128: posix_spawn avoided (fd close requested) 

(cinnamon:2052): Cjs-WARNING **: 20:49:18.903: Some code accessed the property 'EdgeFlipper' on the module 'edgeFlip'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Cjs-Message: 20:49:18.905: JS LOG: [LookingGlass/info] loaded at Thu Mar 18 2021 20:49:18 GMT+0100 (CET)
Cjs-Message: 20:49:18.905: JS LOG: Cinnamon started at Thu Mar 18 2021 20:49:18 GMT+0100 (CET)
Cjs-Message: 20:49:18.916: JS LOG: [LookingGlass/info] ExtensionSystem started in 2 ms
Cjs-Message: 20:49:18.916: JS LOG: [LookingGlass/info] DeskletManager started in 2 ms
Cjs-Message: 20:49:18.916: JS LOG: [LookingGlass/info] SearchProviderManager started in 2 ms
openGL version 4.6 detected (GL3 Cogl Driver)
MetaSyncRing disabled: couldn't find required GL extensions, or the minimum safe openGL version was not met
Cjs-Message: 20:49:18.942: JS LOG: [LookingGlass/info] Role locked: tray
Cjs-Message: 20:49:18.944: JS LOG: [LookingGlass/info] Loaded applet systray@cinnamon.org in 10 ms
Cjs-Message: 20:49:18.966: JS LOG: [LookingGlass/info] Loaded applet show-desktop@cinnamon.org in 22 ms
Cjs-Message: 20:49:18.973: JS LOG: [LookingGlass/info] Loaded applet removable-drives@cinnamon.org in 6 ms
St-Message: 20:49:18.974: cogl npot texture sizes SUPPORTED
Cjs-Message: 20:49:18.995: JS LOG: [LookingGlass/info] Loaded applet keyboard@cinnamon.org in 22 ms
Cjs-Message: 20:49:19.005: JS LOG: [LookingGlass/info] Role locked: notifications
Cjs-Message: 20:49:19.019: JS LOG: [LookingGlass/info] Loaded applet notifications@cinnamon.org in 24 ms
Cjs-Message: 20:49:19.038: JS LOG: [LookingGlass/info] Loaded applet user@cinnamon.org in 18 ms
Cinnamon warning: Log level 128: setenv()/putenv() are not thread-safe and should not be used after threads are created
Cinnamon warning: Log level 128: setenv()/putenv() are not thread-safe and should not be used after threads are created
Cinnamon warning: Log level 128: setenv()/putenv() are not thread-safe and should not be used after threads are created
Cinnamon warning: Log level 128: setenv()/putenv() are not thread-safe and should not be used after threads are created
Cinnamon warning: Log level 128: setenv()/putenv() are not thread-safe and should not be used after threads are created
Cinnamon warning: Log level 128: setenv()/putenv() are not thread-safe and should not be used after threads are created
Cjs-Message: 20:49:19.065: JS LOG: [LookingGlass/info] Loaded applet calendar@cinnamon.org in 26 ms
Cjs-Message: 20:49:19.080: JS LOG: [LookingGlass/info] Loaded applet power@cinnamon.org in 16 ms
Cjs-Message: 20:49:19.116: JS LOG: [LookingGlass/info] Role locked: panellauncher
Cjs-Message: 20:49:19.118: JS LOG: [LookingGlass/info] Loaded applet panel-launchers@cinnamon.org in 38 ms
Cjs-Message: 20:49:19.122: JS LOG: [LookingGlass/info] Loaded applet xapp-status@cinnamon.org in 4 ms
Cinnamon warning: Log level 128: posix_spawn avoided (automatic reaping requested) (fd close requested) 
Cjs-Message: 20:49:19.137: JS LOG: [LookingGlass/info] Loaded applet window-list@cinnamon.org in 14 ms

(csd-power:1896): power-plugin-CRITICAL **: 20:49:19.141: abs_to_percentage: assertion 'max > min' failed
Cjs-Message: 20:49:19.173: JS LOG: [LookingGlass/info] Loaded applet sound@cinnamon.org in 34 ms
Cjs-Message: 20:49:19.188: JS LOG: [LookingGlass/info] Loaded applet network@cinnamon.org in 16 ms
Cjs-Message: 20:49:19.378: JS LOG: [LookingGlass/info] Loaded applet menu@cinnamon.org in 190 ms
Cjs-Message: 20:49:19.378: JS LOG: [LookingGlass/info] AppletManager started in 472 ms
Cjs-Message: 20:49:19.379: JS LOG: [LookingGlass/info] Cinnamon took 900 ms to start
Cjs-Message: 20:49:19.391: JS LOG: Unknown network device type, is 14
Cjs-Message: 20:49:19.395: JS LOG: Unknown network device type, is 13
Cjs-Message: 20:49:19.810: JS LOG: [LookingGlass/info] Hiding XAppStatusIcon (we have an applet): nm-applet
20:49:19.919 › Current working directory is /home/fla, changing into /opt/Mattermost
** Message: 20:49:19.942: nemo-desktop: session is cinnamon, establishing proxy
Nemo-Share-Message: 20:49:20.929: Called "net usershare info" but it failed: « net usershare » a retourné l'erreur 255 : net usershare: cannot open usershare directory /var/lib/samba/usershares. Error Aucun fichier ou dossier de ce type
Please ask your system administrator to enable user sharing.

Traceback (most recent call last):
  File "/usr/bin/cinnamon-screensaver", line 117, in <module>
    main = Main()
  File "/usr/bin/cinnamon-screensaver", line 61, in __init__
    from service import ScreensaverService
  File "/usr/share/cinnamon-screensaver/service.py", line 9, in <module>
    from manager import ScreensaverManager
  File "/usr/share/cinnamon-screensaver/manager.py", line 10, in <module>
    from stage import Stage
  File "/usr/share/cinnamon-screensaver/stage.py", line 12, in <module>
    from monitorView import MonitorView
  File "/usr/share/cinnamon-screensaver/monitorView.py", line 5, in <module>
    import cairo
ModuleNotFoundError: No module named 'cairo'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
ModuleNotFoundError: No module named 'apport'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/cinnamon-screensaver", line 117, in <module>
    main = Main()
  File "/usr/bin/cinnamon-screensaver", line 61, in __init__
    from service import ScreensaverService
  File "/usr/share/cinnamon-screensaver/service.py", line 9, in <module>
    from manager import ScreensaverManager
  File "/usr/share/cinnamon-screensaver/manager.py", line 10, in <module>
    from stage import Stage
  File "/usr/share/cinnamon-screensaver/stage.py", line 12, in <module>
    from monitorView import MonitorView
  File "/usr/share/cinnamon-screensaver/monitorView.py", line 5, in <module>
    import cairo
ModuleNotFoundError: No module named 'cairo'
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintUpdate/mintUpdate.py", line 24, in <module>
    from kernelwindow import KernelWindow
  File "/usr/lib/linuxmint/mintUpdate/kernelwindow.py", line 2, in <module>
    import apt
ModuleNotFoundError: No module named 'apt'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
ModuleNotFoundError: No module named 'apport'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintUpdate/mintUpdate.py", line 24, in <module>
    from kernelwindow import KernelWindow
  File "/usr/lib/linuxmint/mintUpdate/kernelwindow.py", line 2, in <module>
    import apt
ModuleNotFoundError: No module named 'apt'
/usr/lib/python3/dist-packages/mintcommon/installer/_flatpak.py:13: PyGIWarning: AppStreamGlib was imported without specifying a version first. Use gi.require_version('AppStreamGlib', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import AppStreamGlib, GLib, GObject, Gtk, Gio
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintinstall/mintinstall-update-flatpak.py", line 20, in <module>
    from mintcommon.installer import _flatpak
  File "/usr/lib/python3/dist-packages/mintcommon/installer/_flatpak.py", line 22, in <module>
    from . import dialogs
  File "/usr/lib/python3/dist-packages/mintcommon/installer/dialogs.py", line 12, in <module>
    from aptdaemon.gtk3widgets import AptConfirmDialog
ModuleNotFoundError: No module named 'aptdaemon'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
ModuleNotFoundError: No module named 'apport'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintinstall/mintinstall-update-flatpak.py", line 20, in <module>
    from mintcommon.installer import _flatpak
  File "/usr/lib/python3/dist-packages/mintcommon/installer/_flatpak.py", line 22, in <module>
    from . import dialogs
  File "/usr/lib/python3/dist-packages/mintcommon/installer/dialogs.py", line 12, in <module>
    from aptdaemon.gtk3widgets import AptConfirmDialog
ModuleNotFoundError: No module named 'aptdaemon'
Cjs-Message: 20:50:00.202: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: mintreport (org.x.StatusIcon.PID-3226-0)
Cinnamon warning: Log level 128: posix_spawn avoided (fd close requested) 
Cinnamon warning: Log level 128: posix_spawn avoided (fd close requested) 
Cinnamon warning: Log level 128: posix_spawn avoided (fd close requested) 
Cjs-Message: 20:50:28.022: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: :1.74 (org.x.StatusIcon.PID-2089-0)
Cinnamon warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3800003 (S'authenti)
Cinnamon warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x4e000fc (Prêt - Ag)
Cinnamon warning: Log level 128: posix_spawn avoided (fd close requested) 
Cjs-Message: 20:56:06.852: JS LOG: [LookingGlass/info] Removing XAppStatusIcon: steam (org.x.StatusIcon.PID-2089-0)
Cinnamon warning: Log level 128: posix_spawn avoided (fd close requested) 
Cjs-Message: 20:56:13.585: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: :1.88 (org.x.StatusIcon.PID-2089-1)
Cinnamon warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x4e000fa (Age of Emp)
Cinnamon warning: Log level 128: posix_spawn avoided (fd close requested) 
Cinnamon warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x4e00109 (Age of Emp)
Cjs-Message: 21:40:17.296: JS LOG: pushModal: invocation of begin_modal failed
Cinnamon warning: Log level 128: posix_spawn avoided (fd close requested) 
Cjs-Message: 21:47:18.777: JS LOG: pushModal: invocation of begin_modal failed
Cjs-Message: 21:48:02.480: JS LOG: pushModal: invocation of begin_modal failed
Cinnamon warning: Log level 128: posix_spawn avoided (fd close requested) 
Cinnamon warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x7400003 (Firefox De)
```

**Comment by leigh123linux** [comment]
It isn't  a cinnamon issue, **you** have screwed up your python install.

**Comment by mtwebster** [comment]
Not much to go on... If you've messed with your python  - like attempting to install a newer version, building yourself, etc... this is probably the cause. Check `which python3` it should be /usr/bin/python3.

python3 --version should be 3.8.x

Check your apt log (install log) - /var/log/apt/history.log - maybe you accidentally did something.

**Comment by Flaburgan** [comment]
@leigh123linux well I agree that I probably did something for sure, but you message isn't helpful, I wasn't doing any python thing manually when this started to happen. Please don't be rude.

@mtwebster 
```
fla@enigma:~$ which python3
/usr/bin/python3
fla@enigma:~$ python3 --version
Python 3.8.5
```
Thank you for pointing me to `less /var/log/apt/history.log`, indeed, that date of the 12th of march match with the start of the problem, and `apt` installed some related python package. 
```
Start-Date: 2021-03-12  08:58:11
Commandline: /usr/bin/apt full-upgrade
Requested-By: fla (1000)
Upgrade: libgles2-mesa:amd64 (21.1~git2103100600.cbd5d8~oibaf~f, 21.1~git2103120600.684f97~oibaf~f), libegl-mesa0:amd64 (21.1~git2103100600.cbd5d8~oibaf~f, 21.1~git2103120600.684f97~oibaf~f), libglapi-mesa:i386 (21.1~git2103100600.cbd5d8~oibaf~f, 21.1~git2103120600.684f97~oibaf~f), libglapi-mesa:amd64 (21.1~git2103100600.cbd5d8~oibaf~f, 21.1~git2103120600.684f97~oibaf~f), python2.7-minimal:amd64 (2.7.18-1~20.04, 2.7.18-1~20.04.1), libpython2.7:amd64 (2.7.18-1~20.04, 2.7.18-1~20.04.1), python2.7:amd64 (2.7.18-1~20.04, 2.7.18-1~20.04.1), python3-pil:amd64 (7.0.0-4ubuntu0.2, 7.0.0-4ubuntu0.3), libxatracker2:amd64 (21.1~git2103100600.cbd5d8~oibaf~f, 21.1~git2103120600.684f97~oibaf~f), libegl1-mesa:amd64 (21.1~git2103100600.cbd5d8~oibaf~f, 21.1~git2103120600.684f97~oibaf~f), libgbm1:amd64 (21.1~git2103100600.cbd5d8~oibaf~f, 21.1~git2103120600.684f97~oibaf~f), libwayland-egl1-mesa:amd64 (21.1~git2103100600.cbd5d8~oibaf~f, 21.1~git2103120600.684f97~oibaf~f), libgl1-mesa-dri:i386 (21.1~git2103100600.cbd5d8~oibaf~f, 21.1~git2103120600.684f97~oibaf~f), libgl1-mesa-dri:amd64 (21.1~git2103100600.cbd5d8~oibaf~f, 21.1~git2103120600.684f97~oibaf~f), libgl1-mesa-glx:i386 (21.1~git2103100600.cbd5d8~oibaf~f, 21.1~git2103120600.684f97~oibaf~f), libgl1-mesa-glx:amd64 (21.1~git2103100600.cbd5d8~oibaf~f, 21.1~git2103120600.684f97~oibaf~f), libpython2.7-minimal:amd64 (2.7.18-1~20.04, 2.7.18-1~20.04.1), mesa-vdpau-drivers:amd64 (21.1~git2103100600.cbd5d8~oibaf~f, 21.1~git2103120600.684f97~oibaf~f), linux-firmware:amd64 (1.187.9, 1.187.10), mesa-vulkan-drivers:amd64 (21.1~git2103100600.cbd5d8~oibaf~f, 21.1~git2103120600.684f97~oibaf~f), mesa-vulkan-drivers:i386 (21.1~git2103100600.cbd5d8~oibaf~f, 21.1~git2103120600.684f97~oibaf~f), libpython2.7-stdlib:amd64 (2.7.18-1~20.04, 2.7.18-1~20.04.1), libglx-mesa0:amd64 (21.1~git2103100600.cbd5d8~oibaf~f, 21.1~git2103120600.684f97~oibaf~f), libglx-mesa0:i386 (21.1~git2103100600.cbd5d8~oibaf~f, 21.1~git2103120600.684f97~oibaf~f)
End-Date: 2021-03-12  09:01:36
```

So as my installation was initially on Mint 18, I still have python2 installed. Can this cause a problem? Should I try to remove entirely python2?

**Comment by leigh123linux** [comment]
Post

```
python3
import cairo
```

**Comment by Flaburgan** [comment]
```
fla@enigma:~$ python3
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cairo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'cairo'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
ModuleNotFoundError: No module named 'apport'

Original exception was:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'cairo'
```

```
fla@enigma:~$ ls -l /usr/bin/python3
lrwxrwxrwx 1 root root 9 mars  13  2020 /usr/bin/python3 -> python3.8
```

Thank you for your help.

**Comment by Flaburgan** [comment]
So, I guess this is not a Cinnamon issue but still is a Mint issue, as I did nothing else than an apt dist-upgrade, how could that have broken python that hard?

**Comment by leigh123linux** [comment]
Is python3-cairo installed and intact?

https://packages.ubuntu.com/focal/amd64/python3-cairo/filelist

**Comment by Flaburgan** [comment]
```
/usr/lib/python3/dist-packages/pycairo-1.16.2.egg-info
/usr/share/doc/python3-cairo/changelog.Debian.gz
/usr/share/doc/python3-cairo/copyright
```

Are there, but not the `/usr/lib/python3/dist-packages/cairo/` folder. `apt install python3-cairo` says I already have the most recent version, 1.16.2-2ubuntu2

**Comment by leigh123linux** [comment]
Try

```
apt-get --reinstall install python3-cairo
```

**Comment by Flaburgan** [comment]
That solved it! Thank you very much. I have no idea what could have caused this honestly
